### ISSUE TITLE
Attempting to add Hass.io Repository fails; shows name as "Unknown"

### ISSUE THREAD

**Issue by grantalewis** [hassio-addons/addon-vscode#10]
# Problem/Motivation

I have this add-on working in HA 0.84.6; cannot add repository in 0.90.2. (Hass.io, VirtualBox, Ubuntu 64)

## Expected behavior

Ability to add repository and add-on. 

## Actual behavior

Supplying the repository shows "unknown." No add-on available to install.

## Steps to reproduce

Attempt to install the add-on in 0.90.2. (Not sure if my config, described above, is significant.)

## Proposed changes

none

![Screen Shot 2019-03-28 at 9 19 10 AM](https://user-images.githubusercontent.com/9505044/55161147-4095f300-513b-11e9-86d0-29f814b00ab7.png)

**Comment by tjorim** [comment]
Please read [the installation instructions](https://github.com/hassio-addons/addon-vscode/blob/master/README.md#installation) carefully. Step 1 mentions which repo you should add, you already have it.

**Comment by grantalewis** [comment]
OK, you're right -- I already had the repository. My bad. But there are no add-ons on the page for "Visual Studio Code."

**Comment by tjorim** [comment]
Hit the refresh button in the top right to check for updates and new add-ons.
