### ISSUE TITLE
hass-cli behaves like HASS_TOKEN and HASS_SERVER are not configured

### ISSUE THREAD

**Issue by mikenabhan** [hassio-addons/addon-vscode#100]
# Problem/Motivation

> (Why the issue was filed)
hass-cli behaves as if HASS_TOKEN and HASS_SERVER are not configured

## Expected behavior

> (What you expected to happen)
Previously, this addon was configured with HASS_TOKEN and HASS_SERVER auto configured, but they do not function.  If I echo these variables, they are correct.
## Actual behavior

> (What actually happened)
hass-cli behaves as if this information is not configured.  I cannot see anything in addon logs.  I have not made any configuration changes to this addon.
## Steps to reproduce

> (How can someone else make/see it happen)
![image](https://user-images.githubusercontent.com/13139061/80890963-2acbf900-8c7e-11ea-9c3d-54e9beab850a.png)

If I echo these variables, they are configured.

![image](https://user-images.githubusercontent.com/13139061/80891077-f60c7180-8c7e-11ea-9cb1-99cc3f865a77.png)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Looks to be an issue specific to the state history function.  Also likely to be an issue upstream on the cli itself.

**Comment by mikenabhan** [comment]
You know, you are right, I will close here and reopen at hass-cli.  I didn't even think to check other functions 😬
