### ISSUE TITLE
rPi4 Support

### ISSUE THREAD

**Issue by eltriplet** [hassio-addons/addon-vscode#101]
It would be great if you could add support for rPi4, there seems to be already some good builds for it like https://code.headmelted.com

I can help if needed.

<blockquote><div>code.headmelted</div><div><strong><a href="https://code.headmelted.com/">Visual Studio Code for Chromebooks and Raspberry Pi</a></strong></div><div>Builds of Visual Studio Code for Chromebooks and Raspberry Pi</div></blockquote>

**Comment by frenck** [comment]
It already has Raspberry Pi 4 support.

**Comment by eltriplet** [comment]
Then I may 

> It already has Raspberry Pi 4 support.

It appears greyed out with the message "This add-on is not available on your system."

I guess the problem is that I'm using Raspbian + Hassio docker install. Do you know if there is any way to use the add-on in this case?

**Comment by frenck** [comment]
It requires a 64 bit system.
