### ISSUE TITLE
Warnings in scripts for description, icon and fields

### ISSUE THREAD

**Issue by fribse** [hassio-addons/addon-vscode#102]
# Problem/Motivation

When I edit a script I see warnings that these properties are not allowed

## Expected behavior

They should be accepted

## Actual behavior

They show up with red warnings
![image](https://user-images.githubusercontent.com/13660621/81291848-db653e80-906a-11ea-8007-cc1b32f4b4e0.png)

According to the docs https://www.home-assistant.io/integrations/script/ they should be allowed.

## Steps to reproduce

I guess add the properties

## Proposed changes

<blockquote><img src="https://www.home-assistant.io/images/default-social.png" width="48" align="right"><div><img src="/images/favicon-192x192.png" height="14"> Home Assistant</div><div><strong><a href="https://www.home-assistant.io/integrations/script/">Scripts</a></strong></div><div>Instructions on how to setup scripts within Home Assistant.</div></blockquote>

**Comment by frenck** [comment]
The error is caused by the vscode extension for Home Assistant.
Please report your issue there: <https://github.com/keesschollaart81/vscode-home-assistant>
