### ISSUE TITLE
Could direct access be re-enabled?

### ISSUE THREAD

**Issue by cbho** [hassio-addons/addon-vscode#103]
# Problem/Motivation

Until release [v2.0.0](https://github.com/hassio-addons/addon-vscode/releases/tag/v2.0.0) direct access to the addon was possible.
This was removed with 2.0.0:

> Direct access to the add-on has been removed in favor of easier maintenance and Ingress. With Home Assistant now having Safe Mode, direct access has lost its importance.

Being able to edit files while Home Assistant Core is not running is still useful in some cases (e.g. tweaking z-wave issues or device naming issues).

## Actual behavior

When stopping Home Assistant Core, access to the addon is lost.

## Proposed changes

Re-enable the possibility for direct access.

**Comment by frenck** [comment]
You don't have to shutdown Core to edit z-wave files... Just saying.

It won't be added back, as it adds overhead to the add-on.
