### ISSUE TITLE
Include a build for arm32v7 architecure

### ISSUE THREAD

**Issue by sermayoral** [hassio-addons/addon-vscode#104]
# Problem/Motivation

It's not an issue, it would be a great feature request. Due to the IDE addon was deprecated and some days ago people working on the code_server project found the way of making a compilation that it seems it works perfectly in the arm32v7 architecture (see https://github.com/cdr/code-server/issues/1337#issuecomment-622457413)

It would be possible to add this build in a future release of addon-vscode?

**Comment by frenck** [comment]
Considering the devices that support that and their available resources, I will not add this.

**Comment by sermayoral** [comment]
I have a 32 bit version on Home Assistant in a Raspberry Pi 4 with 4GB RAM that cannot use vscode. The 32bit version of Home Assistant is the recommended version. I consider the rpi4 4gb is not poor in resources.

**Comment by frenck** [comment]
It depends on your use case if you can use the 64 bits or not.

As stated before, I won't be shipping an ARMv7 version, as the general devices supporting that architecture have not enough resources. I'm not going to handle the issues and support questions raised as a result of people still installing it, even when not recommended.

**Comment by sermayoral** [comment]
Ok. Thank you.

**Comment by sermayoral** [comment]
But it has no sense. Ok, you don't want problem, so why dont you delete the entire ARM architecture??

Because if I buy a Raspberry Pi 3 with a 1GB of RAM and I install the 64 bit version of Home Assistant, that actually is possible, i will got in trouble. 

Documentation is clear: "Don't use this addon with less than 4GB RAM". I think this sentence is enough

**Comment by frenck** [comment]
Feel free to fork if you don’t agree 🤷‍♂️

**Comment by sermayoral** [comment]
I will, @frenck, but it won't have official support. And you know that if I do a PR, it would be rejected.

In the last days it seems that issues are a big problem for Home Assistant maintainers. Issues are good, they help improving the opensource. Kubernetes has hundreds of issues every day. And as you know, it is one ot the best opensource softwares available in github. I think for everyone it is better to have a feature with issues than not to have it. Who does not wash, does not break dishes. Is it better not to wash the dishes?

If you don't want to handle an issue, just ignore it. If this issue could be fixed, Home Assistant community will do a PR for fixing it. If the issue cannot be fixed, just do as you did in https://github.com/hassio-addons/addon-vscode/issues/87

Documentation of Home Assistant is clear, concise, and great. Me and many people read it and follow the steps. If people don't follow the steps, the problem is theirs, not ours. I am a long-time Supervised Home Assistant user, without having a single issue. Logically, I have not mixed Home Assistant containers with personal containers. I have a Raspbian system with a Kodi server installed directly on Raspbian in addition to Supervised Home Assistant and some services running under Raspbian, without having any issue (I will always be grateful to Pascal for the great work he has done). Now its an almost deprecated system due to irresponsible people who "open issues". I think it would be enough documenting the method as "This is an advanced method and you are responsible for the performance and problems of your computer", thing that you did a day before and that would be enough, but it seems that it was not enough.

I need the 32 bit version because i'm using the RPI gpios, and I have several problems in the 64 bit architecture in the past due to driver problem. I was a Cloud9 user until it was deprecated. I have been following the code-server developing to get it working in a official way on my rpi4, and you know that it would work perfectly, but it is not going to be possible due to irresponsible people who "open issues".

Do not take it bad @frenck , it's only an opinion. But it's a pitty and I think it's not fair for the Home Assistant Community.

**Comment by frenck** [comment]
For the record, this is my personal project, it always has been.
