### ISSUE TITLE
VS Code won't start

### ISSUE THREAD

**Issue by fonix232** [hassio-addons/addon-vscode#105]
# Problem/Motivation

VS Code completely fails to start on a fresh install of 64 bit HomeAssistant OS on a Raspberry Pi 4 B. Logs are completely empty, the start button flashes red immediately after clicking it.

## Expected behavior

> VS Code should start

## Actual behavior

> VS Code refuses to start, without any logs

## Steps to reproduce

1. Take a Raspberry Pi 4B
2. Install latest HomeAssistant OS 64bit image
3. Set it up as usual
4. Install VS Code from Supervisor - Add-ons
5. Start VS Code
6. Observe it not starting

**Comment by sinclairpaul** [comment]
Please post the supervisor logs

**Comment by frenck** [comment]
Please open a new issue with the supervisor logs when ready. The new version just got released, which you could test as well.

👍
