### ISSUE TITLE
VSC add-on incorrectly flags valid use of new 'not' condition

### ISSUE THREAD

**Issue by grantalewis** [hassio-addons/addon-vscode#106]
# Problem/Motivation

VSC Add-On flags use of the new 'not' condition as invalid

## Actual behavior

<img width="806" alt="Screen Shot 2020-05-23 at 8 31 46 AM" src="https://user-images.githubusercontent.com/9505044/82730843-aeeb2c80-9cd0-11ea-990f-e2e9d50d4731.png">

## Proposed changes

**Comment by sinclairpaul** [comment]
It isn't the addon, its the Extension, please log your issue at https://github.com/keesschollaart81/vscode-home-assistant

**Comment by grantalewis** [comment]
Will do. Thanks.
