### ISSUE TITLE
apt broken

### ISSUE THREAD

**Issue by haberda** [hassio-addons/addon-vscode#107]
# Problem/Motivation

I attempted to install packages with apt but it failed

## Expected behavior

apt package manager installs requested package

## Actual behavior

apt returns:
~~~
apt: /usr/local/lib/code-server/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libapt-private.so.0.0)
apt: /usr/local/lib/code-server/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0)
~~~
## Steps to reproduce

run apt in the terminal

**Comment by frenck** [comment]
Upstream issue, awaiting a fix:

<https://github.com/cdr/code-server/issues/1742>

**Comment by haberda** [comment]
Thank you.

Deleting the *.so* files as indicated in your link appears to fix the issue.
