### ISSUE TITLE
GitHub Auth Fails (latest release)

### ISSUE THREAD

**Issue by RichFoley** [hassio-addons/addon-vscode#109]
# Problem/Motivation

> GitHub auth fails when synchronizing changes. Last version worked with username/password auth, but new version seems to have changed to OAuth.

## Expected behavior

> After selecting "continue" on the GitHub OAuth page that opens, the app should then be authorized.

## Actual behavior

> An error page appears:
![image](https://user-images.githubusercontent.com/6298485/83914607-89820800-a73f-11ea-9f27-c6a0bb3f18f3.png)

## Steps to reproduce

> Initiate a Git push/pull

## Proposed changes

> Revert to username/password authentication? I will attempt to troubleshoot.

**Comment by foley803** [comment]
Workaround: I was able to toggle `git.githubAuthentication` to revert to username/pass authentication.

**Comment by mcinnes01** [comment]
I'm seeing this too, thanks for the work around :)

**Comment by tamet83** [comment]
It doesn't work for me either :/

**Comment by tamet83** [comment]
I've changed this option and the system reverted to the old authentication method username/password 
![Cattura](https://user-images.githubusercontent.com/7949570/93323466-f57f0c80-f814-11ea-9b19-0e4cf1281ccb.JPG)

**Comment by coolguymatt** [comment]
> Workaround: I was able to toggle `git.githubAuthentication` to revert to username/pass authentication.

How do I go about doing this?

**Comment by RichFoley** [comment]
> How do I go about doing this?

Looks like the setting I mentioned was depreciated, now you can:
Go to settings and search for `github.gitAuthentication` ; uncheck it.
or using the menu:
Go to Settings>Extensions>GitHub>Git Authentication

**Comment by frenck** [comment]
According to the upstream changelog, this has been fixed.
The latest version of code-server has been included in the latest add-on release:

<https://github.com/hassio-addons/addon-vscode/releases/tag/v3.0.0>

**Comment by tamet83** [comment]
Sorry but for me still doesn't work.
