### ISSUE TITLE
Unable to connect to the Extensions Marketplace

### ISSUE THREAD

**Issue by rpitera** [hassio-addons/addon-vscode#11]
# Problem/Motivation

When trying to search the Extensions Marketplace, I receive an error.  I'm trying to determine if this is an issue, or expected behavior.

## Expected behavior

Expected to get the list of available extensions.

## Actual behavior

I receive the error "We cannot connect to the Extensions Marketplace at this time, please try again later.

## Steps to reproduce

Try to search for an extension or add a language support module.

## Proposed changes

Unsure.  This is all I can see in the logs for VSC:

`[error] An unknown error occurred. Please consult the log for more details.`

Not seeing anything of note in the add-on logs.

**Comment by rpitera** [comment]
I should add that to test, I reinstalled my desktop version and checked from the same machine and am able to get to the marketplace without issue.

**Comment by rpitera** [comment]
Updated to 0.2.0 - Now it just searches and doesn't even display the installed extensions.  The extensions icon in the left pane shows a little clock overlay and doesn't time out; it just keeps showing the progress indicator at the top.

[https://i.imgur.com/mme7sBW.png](url)

**Comment by rpitera** [comment]
Update.  After rebooting for another unrelated reason, clicking on extensions is back to showing installed extensions like normal.  However searching for an extension now not only locks up search, but causes an Out of Memory error.  I've been able to reproduce this error twice in a row doing a simple search.  As long as I don't use the extensions search menu, everything works fine.

For more detail on setup:  Hass.IO 0.90.2 on a Virtualbox VM (Ubuntu 64, 2048mb RAM, 2 CPUs)

**Comment by frenck** [comment]
2Gb of ram might be on the low end (by looking at your screenshot, you run a lot more add-ons as well).
Running out of ram, will cause issues across the board.

**Comment by rpitera** [comment]
I'll up the RAM and continue testing then and get back to you.  I hadn't realized that 2048 would be too low, but since you mention it I do run a lot of add ons.  Thanks for getting back to me.  I'll keep you posted.

**Comment by rpitera** [comment]
OK, so I upped it to 4Gb.  I'm no longer getting lock ups or out of memory errors, but it still cannot find the Extensions Marketplace.  Let me know if there is any specific information I can give you to help.  I'm assuming that since you didn't state otherwise, it SHOULD connect to the Marketplace without an issue.

Also, I am using the default port and I've tried forwarding the port temporarily on my router to see if it made any difference.  (It didn't.)

**Comment by frenck** [comment]
Somebody at Discord reported a weird solution, of which I have a hard time to believe, nevertheless, worth a shot?

Add this to your add-on config:

`"log_level": "debug",`

And restart...

**Comment by rpitera** [comment]
Man, do I feel like an ass.  I figured out the problem and of course it wasn't your work.  It was a script blocker that I forgot to check.  

Sorry for wasting your time Franck; I thought I had enabled all scripts on my domain but forgot to check after I added the new addon.  I'm closing this but at least it's in the knowledge base for anyone else who might experience a similar issue.

**Comment by frenck** [comment]
Thanks for letting me know @rpitera! Happy you got it resolved.
