### ISSUE TITLE
Support for RPi3b+

### ISSUE THREAD

**Issue by craiq** [hassio-addons/addon-vscode#111]
# Problem/Motivation

missing support for RaspberryPi 3b+

## Proposed changes

use vscode from https://code.headmelted.com/
it has support for it

<blockquote><div>code.headmelted</div><div><strong><a href="https://code.headmelted.com/">Visual Studio Code for Chromebooks and Raspberry Pi</a></strong></div><div>Builds of Visual Studio Code for Chromebooks and Raspberry Pi</div></blockquote>

**Comment by sinclairpaul** [comment]
It already does, you just need a 64 bit OS (though you should look at the recommended memory requirements in the documentation)

If you are asking for 32 bit support please see #104

**Comment by craiq** [comment]
thanks for the hint!
Would love to see a comment to this in the readme :)

**Comment by sinclairpaul** [comment]
In all honesty, it is:

![image](https://user-images.githubusercontent.com/24625998/83981935-6ba7d500-a8f0-11ea-9e57-fd57e3b848b3.png)

Challenge may be around knowing what aarch64 is 😄
