### ISSUE TITLE
VSCode remote SSH feature

### ISSUE THREAD

**Issue by mihaiblaga89** [hassio-addons/addon-vscode#113]
# Problem/Motivation

Any plans on opening this up to VSCode SSH remote? I see this image is based on debian and it will work with this. Tried using the usual SSH extensions for this but both of them are based on alpine and that doesn't support it. [Docs](https://code.visualstudio.com/docs/remote/linux)

## Expected behavior

To be able to configure an SSHD server on this container to accept a SSH connection from VSCode.

## Proposed changes

While I can do this manually with `init_commands` it would be nice if there would be a config section to allow this.

**Comment by sinclairpaul** [comment]
But why?, so you can access the container?

Surely any VSCode remote setup would only be of value at the OS layer?, which you can do easily with a supervised install.

**Comment by frenck** [comment]
That is not in scope for this add-on, I do not have plans on adding that.

**Comment by mihaiblaga89** [comment]
@sinclairpaul So I can access the config files from SSH and have support for VSCode remote SSH, which requires another distro than alpine, which is what both SSH addons are based on. Don't know what you mean by `supervised install` but I'm using hassos and my only way to make a SSH connection is through the above mentioned addons. Or at least that's the only option that I know of.

**Comment by mihaiblaga89** [comment]
@frenck thanks.
