### ISSUE TITLE
Cant find the app on home assistant nor the HACS?

### ISSUE THREAD

**Issue by LogeshNaidoo** [hassio-addons/addon-vscode#115]
# Problem/Motivation

The app cant be found in the normal store nor the Hacs  @`store`

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
HACS = Integrations, themes and stuff. Not add-ons.

This is an add-on, thus not provided by HACS. Add-ons are provided by the Supervisor. See add-on installation instructions.
