### ISSUE TITLE
This add-on is not available on your system.

### ISSUE THREAD

**Issue by LogeshNaidoo** [hassio-addons/addon-vscode#116]
# Problem/Motivation
I have done a fresh installation of home assistant on raspberry pi. In order to install "visual studio code" I have followed your instructions by searching for it in the supervisor-add on store via the community add on. Visual studio code is visible but not accessible. it says its not available on my system? 

![image](https://user-images.githubusercontent.com/43524861/85218291-45c30b80-b399-11ea-89e3-97a45ce8a6e3.png)

**Comment by frenck** [comment]
Well, that is correct. It is only available on aarch64 and amd64 systems.
