### ISSUE TITLE
MDI Extension configured to use mismatched version

### ISSUE THREAD

**Issue by trankillity** [hassio-addons/addon-vscode#117]
# Problem/Motivation

> MDI extension is configured to use "latest" tag, rather than the version used in Home Assistant (4.5.95 according to [this docs link](https://www.home-assistant.io/docs/configuration/customizing-devices/#icon)). This causes issues when customising entities with new or changed icons. 

## Expected behavior

> MDI extension is configured to match the included MDI package in Home Assistant.

## Actual behavior

> MDI extension intellisense completes for latest release.

## Steps to reproduce

>  `mdi:playstation` (4.5.95) is now called `mdi:sony-playstation`. VSCode reports `mdi:playstation` as an invalid icon, but `mdi:sony-playstation` doesn't actually exist in HA.

## Proposed changes

> Modify `materialdesigniconsIntellisense.mdiVersion` to match the version in HA (or update/include `latest` tag for MDI in HA)

**Comment by frenck** [comment]
Good point! We should make sure it matches

**Comment by frenck** [comment]
Locked it down in the upcoming version. Thanks m8! 👍
