### ISSUE TITLE
Unable to use Git Push feature

### ISSUE THREAD

**Issue by SiliconAvatar** [hassio-addons/addon-vscode#12]
# Problem/Motivation

I'm unsure if this is expected behaviour (and there's a configuration step I missed) or an issue with the addon.

When using git inside VSCode, I can commit changes using the GUI, but when I use the push command I get an error that I cannot find the askpass.sh file.

## Expected behavior

It should ask for a username and password for the git repository.

## Actual behavior

The command fails with an error message. ([screenshot](https://i.imgur.com/ckgTRR7.png))
If I open the git log, this is the error I see:

```
> git push origin master
fatal: cannot run /home/travis/build/codercom/code-server/packages/server/build/extensions/git/dist/askpass.sh: No such file or directory
fatal: could not read Username for 'https://github.com': No such device or address
```

If I go directly to the terminal and type in the same command (`git push origin master`) it correctly asks for my authentication and the push succeeds.

**Comment by frenck** [comment]
This is an upstream codercom/code-server#208

For a workaround in the comment of the upstream issue:

> run `git config --global credential.helper cache` and manually do a git pull/clone/etc (from the CLI) where you'll have to enter your password. Once you do that, git operations in the GUI should work.

**Comment by raulvasquez** [comment]
> To be honest, please use a public/private key pair instead of username/passwords... 😉

I have hass.io installed on my ubuntu server with docker. 

How do you get the keys to persist? They are removed when the container is restarted. I tried symlinking the hosts keys folder to my homeassistant config folder, but they didn't work. Appeared to be permission related.

**Comment by frenck** [comment]
@raulvasquez The `.ssh` folder (where your keys should go), persists across restarts.

**Comment by rogersmj** [comment]
> The .ssh folder (where your keys should go), persists across restarts.

What .ssh folder are you referring to? I have the SSH add-on too, so I tried adding my key in my user's .ssh folder, but VScode showed no change. I know very little about docker.

I tried googling around for how to setup an SSH key between this add-on and GitHub, and I wind up at this thread :)

**Comment by sverleysen** [comment]
I also have this issue. I created a key in the .ssh folder, added the key into my github account. But how do I say to vscode to use this key instead of the username/password?

**Comment by sverleysen** [comment]
> > The .ssh folder (where your keys should go), persists across restarts.
> 
> What .ssh folder are you referring to? I have the SSH add-on too, so I tried adding my key in my user's .ssh folder, but VScode showed no change. I know very little about docker.
> 
> I tried googling around for how to setup an SSH key between this add-on and GitHub, and I wind up at this thread :)

I found my .ssh folder in the hassio root /addons/data/xxxx_vscode/.ssh

**Comment by rockinglama** [comment]
> I also have this issue. I created a key in the .ssh folder, added the key into my github account. But how do I say to vscode to use this key instead of the username/password?

it should use the key by default but you have to accept the github hostkey
open a shell in your vscode container and do a `ssh git@github.com` and accept the host key fingerprint

**Comment by frenck** [comment]
I'm closing this issue.

While it is still present, there is nothing the add-on can do about it.
At this point, it is just cluttering up the overview of issues on the project.

I hope it will be resolved Upstream, however, it is recommended to use private/public keypairs.
