### ISSUE TITLE
icon mdi renamed, warning to replace

### ISSUE THREAD

**Issue by serlinGi** [hassio-addons/addon-vscode#122]
# Problem: icon mdi renamed - warning messages

## Actual behavior

>  I can't find the location of the indicated icon (mdi: visual-studio-code)

## Steps to reproduce

After upgrade Home Assistant Core 0.113, the recursive Warning message, with many occurrences;
this warning appears immediately upon restart;
I also tried to remove the add-on and reinstall it clean but I didn't solve the problem

## since I have not manually set this icon anywhere and in any case I can't find it, it would be useful for the warning to indicate the path / file in which it's recorded

> the messages appear in Configuration-> Logs

![warning icon VSC](https://user-images.githubusercontent.com/63103970/88568503-6128d280-d039-11ea-9739-e8afca3bdf87.JPG)

my Versions:

![Log start VSC](https://user-images.githubusercontent.com/63103970/88568611-89183600-d039-11ea-9ab6-4383f789e7bc.JPG)

**Comment by frenck** [comment]
Fixed in #121
