### ISSUE TITLE
numeric_state entity_id checking complains about anything other than sensor.*

### ISSUE THREAD

**Issue by rccoleman** [hassio-addons/addon-vscode#123]
# Problem/Motivation

The upgrade to 2.4.0 appears to have added restrictions to the syntax/entity checking for numeric_state that are too strict.  I have automations that use `input_number.xxx` and `sun.sun` with a `numeric_state` trigger/condition and they work fine, but they result in complaints with the new addon/HA extension.  They passed the checks in the previous addon release.

## Expected behavior

I expect entities that return a number to be valid in a `numeric_state` trigger or condition, and not just entities in the `sensor` domain.

## Actual behavior

The pattern matching for a valid `enity_id:` for `numeric_state` triggers/conditions appears to require an entity in the `sensor` domain.

![image](https://user-images.githubusercontent.com/860888/88697017-d7b8e500-d0b8-11ea-86e6-c6242b122c07.png)

![image](https://user-images.githubusercontent.com/860888/88697117-f7e8a400-d0b8-11ea-91df-50450c3dfac7.png)

## Steps to reproduce

Use an entity not in the `sensor` domain with a `numeric_state` trigger/condition.

## Proposed changes

Loosen the restrictions on the domains that can be used with `numeric_state` to include others that also return numbers.

**Comment by frenck** [comment]
Please report your issue here: <https://github.com/keesschollaart81/vscode-home-assistant/issues>

As this is not caused by the add-on, but by the extension. Thanks 👍

**Comment by rccoleman** [comment]
Sorry, I've gone through that process before and didn't think before filing this time.  Thanks for picking it up on the other side.
