### ISSUE TITLE
VS Code will not start

### ISSUE THREAD

**Issue by capgun42** [hassio-addons/addon-vscode#125]
# Problem/Motivation

> VS Code fails to start on a fresh install of 64-bit HomeAssistant OS on a Raspberry Pi 4GB. Similar Configuration to error as Issue 104. Looks to be error accessing 0.0.0.0. No proxy, but hardwired on Unifi system. I believe Unifi USG firewall should allow access. Log below

## Expected behavior

> VS Code should start

## Actual behavior

> VS Code refuses to start

## Steps to reproduce

>   Attempt to startVS Code

##Log Details:
>[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 2.4.0
 You are running the latest version of this add-on.
 System: HassOS 4.11  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 0.113.3
 Home Assistant Supervisor: 229
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[00:09:57] INFO: Starting the code server...
info  Wrote default config file to ~/.config/code-server/config.yaml
info  Using config file ~/.config/code-server/config.yaml
info  Using user-data-dir /data/vscode
info  code-server 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259
info  HTTP server listening on http://0.0.0.0:1337
info    - No authentication
info    - Not serving HTTPS

**Comment by frenck** [comment]
The above logs look good, as in the add-on has started correctly. Sounds like a connection issue?

**Comment by capgun42** [comment]
Thanks for the confirmation @frenck . Everything else seems to be connecting to the internet fine. Are there specific ports that need to be opened? 1337? TCP/UDP?

**Comment by frenck** [comment]
@capgun42 None. It uses ingress.

**Comment by capgun42** [comment]
Thanks @frenck; ill keep working on it

**Comment by stringy92** [comment]
@capgun42 did you find the issue? Currently got the same issue, i am running Home Assistant Supervised (Ubuntu) on NUC

**Comment by frenck** [comment]
@stringy92 As far as I'm concerned, there is no issue. At least, no actual issue has been provided in any of the above.

Please note, that Ubuntu isn't a supported system.

**Comment by capgun42** [comment]
@stringy92 I was able to get it working intermediately by reflashing uand moving the pi to the main LAN  from the VLAN. My guess is maybe the UniFi USG firewall rules are not working properly. The USG was picked up used and may be defective.

________________________________
