### ISSUE TITLE
VS Code can't be reached outside my lan.

### ISSUE THREAD

**Issue by jokerigno** [hassio-addons/addon-vscode#126]
# Problem/Motivation

VS instance is not visible (it's on but screen remains blank) while using remote connection (with let's encrypt as reverse proxy)
## Expected behavior

> To be able to access VS from inside AND ouside my lan

## Actual behavior

> If I use local IP adress VS is there. If I switch to external url the VS istance is not loading.

## Steps to reproduce

> Switch between local and remote address of HA instances

## Proposed changes

> Dunno unfortunately. I can only say that this happens only with VS. As a workaround when in need I use "file editor" addon.

Below my logs:

`Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 2.4.0
 You are running the latest version of this add-on.
 System: HassOS 4.12  (amd64 / qemux86-64)
 Home Assistant Core: 0.113.3
 Home Assistant Supervisor: 229
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:03:17] INFO: Starting the code server...
info  Wrote default config file to ~/.config/code-server/config.yaml
info  Using config file ~/.config/code-server/config.yaml
info  Using user-data-dir /data/vscode
info  code-server 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259
info  HTTP server listening on http://0.0.0.0:1337
info    - No authentication
info    - Not serving HTTPS

`

and here's my config

`packages: []
init_commands: []`

**Comment by sinclairpaul** [comment]
Will assume that you are using some form of nginx (letsencrypt isn't a reverse proxy).

Please make sure it is configured for websockets, this really isn't in scope for the addon itself.

**Comment by frenck** [comment]
The add-on is only exposed via Ingress. If it works from withing Home Assistant on the local network, than outside it, is a proxy or port forwarding problem.

The add-on does not control or influence that.
