### ISSUE TITLE
YAML auto indentation issue

### ISSUE THREAD

**Issue by VDRainer** [hassio-addons/addon-vscode#128]
# Problem/Motivation

Auto indentation adds indents after new lines, also on copy and pasting code blocks, indentations are added.

EDIT: Seeing the same behavior in a local installed vscode with the home assistant extention.

## Expected behavior

After adding a blank new line no indentation of the last code block.

## Actual behavior

> (What actually happened)

## Steps to reproduce

![yaml_indentation](https://user-images.githubusercontent.com/26381449/89985067-b7715480-dc7a-11ea-98ef-6a59ecdac0ef.gif)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by VDRainer** [comment]
Same in 2.5.0 with home assistant extention 1.9.0

**Comment by frenck** [comment]
Not an add-on issue, but an issue with the extension. please report the issue there.

**Comment by VDRainer** [comment]
Thanks for the reply.

**Comment by frenck** [comment]
No problem
