### ISSUE TITLE
Regular disconnection from Home assistant

### ISSUE THREAD

**Issue by tre4b** [hassio-addons/addon-vscode#129]
# Problem/Motivation

The ability is great but is made ineffective by continuous disconnection

## Expected behavior

Access system edit any .yaml file in configuration

## Actual behavior

Access system edit a yaml file.  A few seconds latter attached pop up will occur.  To connect again I must reload.  If I manage to type something and move on a line before the disconnection it is saved.  If not then it is lost.

## Steps to reproduce

This happens almost every time I use the system.  I have had one time that I accessed and it seemed to stay connected longer however I had not made changes.

## Proposed changes

Find a way to stop the disconnection occurring or to flag the issue that is causing it so that can be corrected.

![Annotation 2020-08-13 161729](https://user-images.githubusercontent.com/37894577/90153561-0ef9e800-dd81-11ea-8c89-329c33bb6fc3.png)

**Comment by frenck** [comment]
Please provide add-on and supervisor logs when this event occurs.

**Comment by tre4b** [comment]
VS plugin log

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 2.4.0
 You are running the latest version of this add-on.
 System: Ubuntu 19.04  (amd64 / qemux86-64)
 Home Assistant Core: 0.114.0
 Home Assistant Supervisor: 232
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:30:11] INFO: Starting the code server...
info  Wrote default config file to ~/.config/code-server/config.yaml
info  Using config file ~/.config/code-server/config.yaml
info  Using user-data-dir /data/vscode
info  code-server 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259
info  HTTP server listening on http://0.0.0.0:1337
info    - No authentication
info    - Not serving HTTPS
(node:482) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:482) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit

**Comment by tre4b** [comment]
Is there an easy way to provide these as a file.  I can't figure out how to get the HA supervisor logs from the interface so likely have to find in the system files somewhere?

**Comment by tre4b** [comment]
Checked the log file in configuration, there is only this one that could point at this addon

Log Details (ERROR)
Logger: homeassistant
Source: runner.py:115
First occurred: 15:12:30 (1 occurrences)
Last logged: 15:12:30

Error doing job: Unclosed connection


This was the addon log this time

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 2.4.0
 You are running the latest version of this add-on.
 System: Ubuntu 19.04  (amd64 / qemux86-64)
 Home Assistant Core: 0.114.0
 Home Assistant Supervisor: 232
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:55:39] INFO: Starting the code server...
info  Wrote default config file to ~/.config/code-server/config.yaml
info  Using config file ~/.config/code-server/config.yaml
info  Using user-data-dir /data/vscode
info  code-server 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259
info  HTTP server listening on http://0.0.0.0:1337
info    - No authentication
info    - Not serving HTTPS
(node:472) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:472) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit

**Comment by heinekmadsen** [comment]
Same goes for me... Didn't have any issues when running my hassos on Hyper-V. I have migrated to a RPi 4 and then tis started to happen.
Tried removing and reinstalling the addon. no success.

**Comment by hampshire-al** [comment]
Same for me too.  Disconnects every 10-12 seconds.  Running Hassio on an Intel NUC.  
Cannot see any errors in the log (attached), but on the VSC window it gives a warning of "! code-server is being accessed over an insecure domain. Web views, the clipboard, and other functionality will not work as expected."  Button: [I understand].
Maybe this is connected to the problem?
[log.txt](https://github.com/hassio-addons/addon-vscode/files/5164869/log.txt)

**Comment by sjmotew** [comment]
Same issue, running in Synology NAS

**Comment by DamsPams** [comment]
hi,
I had the same error on a HassOs VM on Virtual Box for months.
 I don't know if that has a relation but after having installed "VM VirtualBox Extension Pack", the addon works as it should ,no disconnection !!!

**Comment by carstenschroeder** [comment]
Same here under HassOS 4.13 in proxmox VM

**Comment by javierdc** [comment]
I'm having the same issue using HassOS 4.13 HA 0.115.2 Supervisor 245, Logs:

AddIn:
[2020-09-22T15:46:44.461Z] info  HTTP server listening on http://0.0.0.0:1337
[2020-09-22T15:46:44.461Z] info    - No authentication
[2020-09-22T15:46:44.461Z] info    - Not serving HTTPS
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
[2020-09-22T15:47:15.003Z] error VS Code exited unexpectedly with code 1

Nothing on the supervisor logs nor in HA logs.

**Comment by SmarterHomeLife** [comment]
I'm having the same issue on HassOS 5.2 HA 0.115.4 Supervisor 245 on RPi4 4Gb

(node:565) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit
(node:565) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
[2020-09-29T08:40:35.722Z] error VS Code exited unexpectedly with code 1

**Comment by piit79** [comment]
I'm also experiencing this issue and I found the following error message in the Chrome Developer Tools Console:

```
Uncaught (in promise) SecurityError: Failed to register a ServiceWorker for scope
('https://<hostname>/api/hassio_ingress/BzbJX9nGU2psjJ6BqSzlttL5m6DrJLD8MflUSjKt_pY') with script 
('https://<hostname>/api/hassio_ingress/BzbJX9nGU2psjJ6BqSzlttL5m6DrJLD8MflUSjKt_pY/static/de41646fc402b968ca6d555fdf2da7de9554d28a/usr/local/lib/code-server/dist/serviceWorker.js'):
The path of the provided scope ('/api/hassio_ingress/BzbJX9nGU2psjJ6BqSzlttL5m6DrJLD8MflUSjKt_pY')
is not under the max scope allowed (set by Service-Worker-Allowed: '/api/hassio_ingress/BzbJX9nGU2psjJ6BqSzlttL5m6DrJLD8MflUSjKt_pY/').
Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed
HTTP header to allow the scope.
```

As far as I can see, the only difference is that the ServiceWorker scope does **not** end in a slash, while the `Service-Worker-Allowed` header value **does**, causing the `SecurityError`.

Could this be the reason for the disconnects?

**Comment by tre4b** [comment]
Okay I think I may have some idea what is causing this.

I have just migrated my setup to one based on a NUC.  I have set it up from scratch from the base image rather than use a snapshot, as I wanted to make sure this was as "clean as possible".

After Samba VSCode was the next thing I tried.  This went on and worked well, though it moaned about the server not being secure as I had not done the SSL certs.   

This morning I got around to creating a new certificate for the box and added that so that I could get rid of the https: error messages and be more secure.  Now VSCode no longer gives the error message.  It has now resumed the regular disconnection as described in the original posed.   I checked the configuration docs and can find no information about telling VSCode about the certificates for this box.

I then turned off the SSL certificates again in Configuration.yaml with some #s, restarted and now VSCode is giving the error message about SSl again however it is not disconnecting any more.  Seems the issue is something to do with my certificate setup?

**Comment by robsonke** [comment]
I can confirm above two comments too:
`
ERR [remote-connection][ExtensionHost][694b7…][initial][myhostname.com:80] the handshake took longer than 10 seconds. Error:
log.ts:197
ERR Error: handshake timeout
    at VM282 workbench.web.api.js:1808
log.ts:197   
ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
log.ts:197   ERR Error: handshake timeout
    at VM282 workbench.web.api.js:1808
`

**Comment by robsonke** [comment]
Laptop on since my change, no disconnect errors so far. So somehow this addon connects to port 80, even if you default connection is over 443 (which is pretty obvious I'd say).

**Comment by jrm523** [comment]
I am also having issues with the add-on and one of my errors is similar to the last few posts.

Issue: VSC regularly prompts for a reload randomly (usually multiple times)

Errors:
Chrome Dev console (two errors)
`The path of the provided scope ('/api/hassio_ingress/gSbbVilFfQXD_PM4uxT4H4hheXYZJdihTiQzbLNhj4M') is not under the max scope allowed (set by Service-Worker-Allowed: '/api/hassio_ingress/gSbbVilFfQXD_PM4uxT4H4hheXYZJdihTiQzbLNhj4M/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.
(index):1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://moreland.duckdns.org/api/hassio_ingress/gSbbVilFfQXD_PM4uxT4H4hheXYZJdihTiQzbLNhj4M') with script ('https://moreland.duckdns.org/api/hassio_ingress/gSbbVilFfQXD_PM4uxT4H4hheXYZJdihTiQzbLNhj4M/static/de41646fc402b968ca6d555fdf2da7de9554d28a/usr/local/lib/code-server/dist/serviceWorker.js'): The path of the provided scope ('/api/hassio_ingress/gSbbVilFfQXD_PM4uxT4H4hheXYZJdihTiQzbLNhj4M') is not under the max scope allowed (set by Service-Worker-Allowed: '/api/hassio_ingress/gSbbVilFfQXD_PM4uxT4H4hheXYZJdihTiQzbLNhj4M/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.`

HA VSC Log:
`(node:480) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit
(node:480) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit`

**Comment by piit79** [comment]
@jrm523 Thanks for confirming my report. I really wonder when did the issue start...

By the way, you might want to redact the address of your HA to avoid it becoming a target for various attacks.

**Comment by piit79** [comment]
OK, I dug around a bit more and found the following:

* During the service worker registration, the response to the request to `/api/hassio_ingress/<key>/static/de41646fc402b968ca6d555fdf2da7de9554d28a/usr/local/lib/code-server/dist/serviceWorker.js` has the header `service-worker-allowed: ./../../../../../../..`. Which seems OK at first sight, as it gets us back to the root of the `iframe`, which is `/api/hassio_ingress/<key>/`
* The service worker scope is set to `.`, which, I assume, is interpreted as `/api/hassio_ingress/<key>` (no trailing slash) for some reason, causing the `SecurityError`

I found out that the code-server accepts an `options` query parameter in JSON format. If I set it to `{"base":"/api/hassio_ingress/<key>/"}` (URL-encoded, naturally), the service worker registration will succeed.
 
I can also work around this in my Apache2 config by altering the `service-worker-allowed` header and add an extra `/..`:

    Header edit service-worker-allowed ^\./\.\./\.\./\.\./\.\./\.\./\.\./\.\.$ ./../../../../../../../..

However, this uncovers the fact that the disconnects are **not** actually caused by the service worker registration failing. Even when the service worker registers correctly, I get another error, similar to other users above:

    ERR [remote-connection][ExtensionHost][df65a…][initial][<hostname>:80] the handshake took longer than 10 seconds. Error:
    ERR Error: handshake timeout
        at remoteAgentConnection.ts:115

I'm not quite sure what could be wrong, as there are actually no connections to my HA server to port 80 from the laptop I'm using.

If anybody has any ideas I'd greatly appreciate any input.

**Comment by Dinth** [comment]
Seems like the same issue as https://github.com/hassio-addons/addon-vscode/issues/96
Im also experiencing this. Weirdly, it is only occurring since I have backed up my old HassOS installation and restored it on a different host - Debian with docker. 
```
Container log shows: (node:480) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit
(node:480) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit
```

**Comment by piit79** [comment]
@Dinth Thanks for pointing to the possible duplicate.

However, I've got a feeling that the addon error messages (or rather warnings) are not linked to this issue. For example, I don't see them in my log.

**Comment by sinclairpaul** [comment]
@piit79 How are the websockets headers configured on your proxy?, do you see wss connections in the browser console?

**Comment by Koma-Andrea** [comment]
I've fixed patching the headers in my traefik configuration:

Added this middleware:

```yaml
traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto = https
```

Seems that if you configure VScode to work without ssl it tries to create the websocket over http this is not something that a good browser will let you do.
Pushing the https proto in the header inform vscode that the websocket should be in https.

**Comment by ybjlus** [comment]
I'm also having the same issue...
Running virtualbox

**Comment by mchoff** [comment]
I have same issue after restore backup to new install hassos. the errors are same handshake timeouts. Hass has ssl enable. i have chrome console log if it helps anyone. 

 if i have google chrome dev tools (f12) console opened up first, then vscode always loads. If not ill get blank screen.

It seem to work fine the very first time after browser data is cleared, after that blank screen. i would refresh over and over until it come up until i realize opening f12-console first works consistently when i needed vscode.

**Comment by Dinth** [comment]
Great point, i can confirm that the problem disappears when I open Developer Tools in Chrome.

**Comment by ybjlus** [comment]
Same here, Developer tools makes the problem go away.

**Comment by eloo** [comment]
> I've fixed patching the headers in my traefik configuration:
> 
> Added this middleware:
> 
> ```yaml
> traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto = https
> ```
> 
> Seems that if you configure VScode to work without ssl it tries to create the websocket over http this is not something that a good browser will let you do.
> Pushing the https proto in the header inform vscode that the websocket should be in https.

Hi, how did you configure traefik with homeassistant so you can use labels?

**Comment by frenck** [comment]
That is interesting though, as I don't use a X-Forwarded-Proto at all...

**Comment by eloo** [comment]
For me the `X-Forwarded-Proto` does not fix it.
I also see this error when i access HA without traefik.

**Comment by piit79** [comment]
Yeah, the `X-Forwarded-Proto` header didn't help in my Apache2 reverse proxy scenario either.

What is really strange though is that the vscode addon works just fine in Chrome on my Linux laptop, but it fails in Chrome on my MacBook. Just tested in Chrome in Linux at work and it fails too - but it works fine with Developer Tools open.

This is a _really_ strange one.

**Comment by frenck** [comment]
I haven't been able to reproduce or make anything about all the stuff reported here. Which sucks, because there is definitely something going on, unfortunately, I'm currently still touching in the dark on this one.

**Comment by eloo** [comment]
At least i've noticed that this error is not appearing the whole time...
Sometimes i'm getting a session which works for a longer period. 

Maybe we should share how we use the vscode?
For me:
Browser: Brave
OS: Ubuntu 20.10
Accessing: Using external DNS and internal DNS
ReverseProxy: Traefik (external), NoProxy (internal DNS)
Usage: I often have multiple tabs of homeassistant open and switch around them.

And i have just produced a bit different error while i was accessing the vscode integration.
I just got a blank page and found this in the console
```
Uncaught Error: Assertion Failed: argument is undefined or null
    at Object.t.assertIsDefined (VM199 workbench.web.api.js:267)
    at p.getStorage (VM199 workbench.web.api.js:1864)
    at p.get (VM199 workbench.web.api.js:1864)
    at new w (VM199 workbench.web.api.js:2893)
    at d._createInstance (VM199 workbench.web.api.js:1640)
...
ERR handshake timeout: Error: handshake timeout
    at https://my-external-dns:11111/api/hassio_ingress/eEKRicXsAAepXwQb8a9oDFCYCYU52UYGYFKaO6wiUng/static/a4a03c14922ccaec2a9ff8d1b7b2af8522a4214d/usr/local/lib/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:1833:806
...
 ERR Unable to read file 'vscode-userdata:/data/vscode/settings.json' (Error: handshake timeout): Error: Unable to read file 'vscode-userdata:/data/vscode/settings.json' (Error: handshake timeout)
```

Looks for me maybe the timeout for handshake is too strict?

**Comment by a351must2** [comment]
So I was regularly getting this in Chrome and having debug tools opened only worked about 75% of the time.  With the help of comments in this issue I was able to resolve the problem by adding the "X-Forwarded-Proto" header with value "fmt: https" to my HAProxy front end configuration running on pFSense.

--- Added a new Action to the top of the list of actions for my HomeAssistant ACL
      Action:   http-request header set
      Name:   X-Forwarded-Proto
      fmt:       https

I'm assuming this issue is only affecting people that use a proxy server for their HomeAssistant access.  With the way Chrome updates have been recently, I wouldn't be surprised if a Chrome update introduced this issue since they seem to be working on tightening security.

**Comment by tht** [comment]
Same here… I don't think it is a browser issue and not related to an update to Chrome. I'm watching this issue as I'm also experiencing this.

I also get a working session sometimes. The disconnect is always at the beginning of a session and if it works for more than about 10 seconds it will work for a long time. If I get a disconnect early I refresh the page. Most of the time after 2-3 reloads the session stays up.

Browser: Safari 14.0 on macOS and also Brave (Chromium) – both experience the same issue
OS: macOS 10.15.7
Accessing: Using external URL (https://hass.xxxxxx.ch) using a valid certificate
ReverseProxy: Caddy (Version 1), forwarding to internal URL (Caddy does the certificate handling and encryption)

I've added `X-Forwarded-Proto` in the reverse proxy configuration. A few weeks ago. IMHO this is needed to get it working most of the time. Without `X-Forwarded-Proto` it never worked for me.

For reference, this is the full configuration as used in Caddy:

```
hass.xxxxx.ch {
  tls my-email-address-here

  proxy / http://--interlan-IP--:8123 {
    transparent
    websocket
    header_upstream X-Forwarded-Proto https
  }
}
```

**Comment by rogersmj** [comment]
> I also get a working session sometimes. The disconnect is always at the beginning of a session and if it works for more than about 10 seconds it will work for a long time. If I get a disconnect early I refresh the page. Most of the time after 2-3 reloads the session stays up.

I am also having the problem described in this thread (for at least 2 months now), and FWIW, this is the exact same behavior I'm experiencing. It always occurs within the first few seconds or not at all -- sometimes refreshing 2-5 times will make it stop, but sometimes it's just hopeless and I have to use a different file editor add-on. Like earlier today, for about 2 hours it was constantly doing this. Now (about 3 hours later) it's not doing it after another refresh -- didn't even restart my browser.

I've experienced it on Chrome and Safari on two different Macs. I'm using an external duckdns URL and SSL cert managed by the DuckDNS+LetsEncrypt official add-on. Other than forwarding Home Assistant's port on my router I have done no special networking or proxy configuration.

**Comment by scooper1** [comment]
just fixed this problem 
my issue was that I had an old second dns server being used by hassio 
try "ha network info" from a terminal in hass docker image

**Comment by short4bmoney** [comment]
> try "ha network info" from a terminal in hass docker image

What should we try with the info returned from that command?

**Comment by freman** [comment]
Going to jump in on the "me too" bandwagon, raspi 4, 8 gig, fresh install and upgraded to latest version.

**Comment by MariusNTT** [comment]
Same for me, rpi 4, 4 Gb., on a fresh installed all was fine for the first hour or so and now I get a few seconds and the reconnect. Direct connect or through duckdns is all the same.

**Comment by manustu** [comment]
This seems to have resolved itself for me. Anyone else still getting these issues?

**Comment by rogersmj** [comment]
No, I'd say within the last couple weeks this seems to have just gone away.

**Comment by tre4b** [comment]
Last couple of days it has become much worse for me.  Now every addon is doing this.  That includes NodeRed, SSH&Web CLI and TasmoAdmin won't even let me access.

None of the "normal" pages and dashboards show any issue, nor do any other pages.

**Comment by frenck** [comment]
> Last couple of days it has become much worse for me. Now every addon is doing this. That includes NodeRed, SSH&Web CLI and TasmoAdmin won't even let me access.

That sounds like a completely different/unrelated problem to be honest.

**Comment by frenck** [comment]
The situation has improved is what I generally get as feedback. Another update is pending addressing a couple of more issues in this department. Unless more issues get reported, I'll close this issue with the next update.

**Comment by tre4b** [comment]
Yeah maybe, however it is only Home Assistant that has the issue and only in the Plugins pages.  I really don't understand as I but a Nuc specifically to get on a 100% compatible device.  The overall system is so much more stable, but this is annoying.   Will try it in Chrome to see if this is something that Edge is causing.

**Comment by Tyfosho** [comment]
@frenck unfortunately I'm still experiencing this issue.

I've been through two Home Assistant Core updates and multiple reboots now and unfortunately the issue hasn't resolved itsself. After installing the add-on, it worked great for about 2 days and then after trying to open a large file (~400MB, potentially unrelated) I now continuously get a disconnected message.

It is worth noting that the file structure does load in the tree on the left side, however I'm unable to load the contents of any file that I open.

**Comment by carstenschroeder** [comment]
I also had this issue. In my case it was caused by an expired SSL certificate used in HA.
