### ISSUE TITLE
"include_dir_merge_named" highlighted as "unknown tag"

### ISSUE THREAD

**Issue by pbavinck** [hassio-addons/addon-vscode#130]
# Problem/Motivation
VS code add-on (yaml validator?) does not recognize the allowed construct ```include_dir_merge_named``` in configuration.yaml. Even though this is supported by [Home Assistant](https://www.home-assistant.io/docs/configuration/splitting_configuration/#advanced-usage).
(I do not know if the other advanced constructs are not supported either)

## Expected behavior
Nothing highlighted as invalid, no error

## Actual behavior
Configuration lines that contain the mentioned construct are highlighted with an error and marks the yaml file as invalid (without consequence I might add, but still, annoying).
![image](https://user-images.githubusercontent.com/4839523/90522234-c15bf180-e16b-11ea-8d30-d2d9aae9c536.png)

## Steps to reproduce
Example based on themes subfolder
1. create a subfolder _themes/_
2. put themes config files in this subfolder
3. use in configuration.yaml:
```yaml
frontend:
  themes: !include_dir_merge_named themes/
```

## Proposed changes
I got nothing :-/

**Comment by earth08** [comment]
post your folder structure.

**Comment by frenck** [comment]
This is not an add-on problem, but an issue with the VSCode Extension for Home Assistant this add-on wraps. Please report it with that project.
