### ISSUE TITLE
Syntax errors in non-default automations.yaml

### ISSUE THREAD

**Issue by djiest** [hassio-addons/addon-vscode#131]
# Problem/Motivation
I use seperate automation files in subfolders, not the default automations.yaml. In these files I get a lot of syntax errors 

## Expected behavior
When placing the same code in the default automation.yaml in the root, I get no syntax errors

## Steps to reproduce
See the screenshots
Default automations.yaml
![image](https://user-images.githubusercontent.com/1582516/92304358-7caec380-ef7d-11ea-917d-a131c901bdb2.png)

automations.yaml in includes/automations/automation.yaml
![image](https://user-images.githubusercontent.com/1582516/92304420-19716100-ef7e-11ea-8738-f8736726754c.png)

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with the Home Assistant Config helper VSCode extension. Please report your issue with that project.

Thanks 👍

**Comment by djiest** [comment]
👍
