### ISSUE TITLE
problem with connection https and nginx

### ISSUE THREAD

**Issue by RWGaMeR** [hassio-addons/addon-vscode#132]
# Problem/Motivation
good morning,
I connected Home Assistant with NGINX via an ubuntu machine and since I did the addon vs code gives me this message:
401: Unauthorized

how do i solve?

## Expected behavior

interface display

## Actual behavior

401: Unauthorized

## Steps to reproduce

I reinstall, it works I exit the page and return from error

**Comment by frenck** [comment]
Sorry, this is not an add-on issue. The add-on doesn't handle authentication, Home Assistant does.

**Comment by RWGaMeR** [comment]
> Sorry, this is not an add-on issue. The add-on doesn't handle authentication, Home Assistant does.

but it only does it if I use the vs code addon

**Comment by frenck** [comment]
I'm sorry to hear that.

**Comment by RWGaMeR** [comment]
> I'm sorry to hear that.
this is the log:

info  Wrote default config file to ~/.config/code-server/config.yaml
info  Using config file ~/.config/code-server/config.yaml
info  Using user-data-dir /data/vscode
info  code-server 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259
info  HTTP server listening on http://0.0.0.0:1337
info    - No authentication
info    - Not serving HTTPS

**Comment by frenck** [comment]
Maybe you missed my first response:

> Sorry, this is not an add-on issue. The add-on doesn't handle authentication, Home Assistant does.

**Comment by afraazali** [comment]
I noticed the issue for me was disabling `http` in my config. I disabled it because I'm using DuckDNS to access my HASS instance via an external domain. My router doesn't support accessing the HA instance via domain from within my network. In order to allow access to the instance using only http (no s) and my internal IP, I needed to disable the `http` config in `configuration.yml`.

Looking at the network panel, I see the following network request getting a 401:

```
GET /api/hassio_ingress/VILy8u7DFC6j206ZaU57KdF-26mY_M9f64Pazc2D2tA/ HTTP/1.1
Host: 192.168.0.48:8123
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Referer: http://192.168.0.48:8123/a0d7b954_vscode
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
```

Hope this helps.
