### ISSUE TITLE
Visual Studio Code add-on not showing

### ISSUE THREAD

**Issue by dorgan** [hassio-addons/addon-vscode#133]
When searching HACS for Visual Studio Code, nothing is returned for both integrations and Frontend

**Comment by sinclairpaul** [comment]
https://hacs.xyz/docs/faq/addons

HACS is unrelated to addons.

**Comment by wdenny3885** [comment]
I have had a similar issue for about 2 months. it shows on the side bar, but when you click it, it tries to load the web UI (the screen changes), but it just stays white.

Just recently upgraded to the latest, and then on a clean restart.  

latest CHROME browser, lasest HASS core and OS

![image](https://user-images.githubusercontent.com/17281756/93942842-daba0580-fcf6-11ea-9469-3241c8102ef8.png)

**Comment by dorgan** [comment]
@sinclairpaul I have HACS installed, but searching it doesn't show visual studio code add-on.  So I am unsure how I can proceed with installing the add-on

**Comment by sinclairpaul** [comment]
@dorgan HACS does not install addons, it is done by the supervisor/addon store.  I am guessing you are running an install that does not have it.  Either way, this is not an issue with the addon itself.

![image](https://user-images.githubusercontent.com/24625998/93945053-2cb55800-fd04-11ea-936f-a770a9127b70.png)

**Comment by frenck** [comment]
HACS does not provide add-ons, it provides integrations.
Please note that integrations and add-ons are totally different things.
