### ISSUE TITLE
command not found: esphome

### ISSUE THREAD

**Issue by Sebclem** [hassio-addons/addon-vscode#135]
# Problem/Motivation

When you open a esphome file, a `OTA` buton appear on the bottom bar, but if you click on it, esphome is not installed in the docker so you get a `command not found: esphome`

## Expected behavior

Compile and upload my esphome config

## Actual behavior

 `command not found: esphome`

## Steps to reproduce

Open a esphome config file and click on the `OTA` button (bottom bar)

## Proposed changes

add `esphome` in the requirement.txt to install esphome

**Comment by frenck** [comment]
You can install custom packages using the init commands options:

<https://github.com/hassio-addons/addon-vscode/blob/master/vscode/DOCS.md#option-init_commands>


I'm not adding ESPHome into this add-on by default, due to size constrains.
