### ISSUE TITLE
blank screen when accessing over external network

### ISSUE THREAD

**Issue by thedansu** [hassio-addons/addon-vscode#136]
# Problem/Motivation

Addon runs fine when accessing home assistant over local network (ie. http://local-ip:8123) but loads a blank screen when accessing home assistant over external network (ie. https://external-domain.com). External access is managed through nginx reverse proxy + cloudflare.

## Expected behavior

Addon should load regardless of local/external access method.

## Actual behavior

Addon does not load, blank screen, when accessing from external network.

## Steps to reproduce

Login to home assistant through local network connection, open vscode addon from sidebar, everything loads and works correctly.
login to home assistant through external connection, click vscode addon from sidebar, blank screen/does not load.

Already tried clear storage in browser developer tools.

logs:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

 Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!

 Add-on version: 2.7.1
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.3 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 0.115.0
 Home Assistant Supervisor: 245

 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:44:36] INFO: Starting the code server...
[2020-09-30T17:44:36.495Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2020-09-30T17:44:36.497Z] info  Using config file ~/.config/code-server/config.yaml
[2020-09-30T17:44:36.882Z] info  Using user-data-dir /data/vscode
[2020-09-30T17:44:36.890Z] info  code-server 3.5.0 de41646fc402b968ca6d555fdf2da7de9554d28a
[2020-09-30T17:44:36.896Z] info  HTTP server listening on http://0.0.0.0:1337
[2020-09-30T17:44:36.896Z] info    - No authentication
[2020-09-30T17:44:36.896Z] info    - Not serving HTTPS

## Proposed changes

unknown

**Comment by sinclairpaul** [comment]
At a guess it sounds like your proxy isn't forwarding websockets correctly.  Check the browser dev tools for errors.

This is unlikely to be related to the addon.

**Comment by thedansu** [comment]
> At a guess it sounds like your proxy isn't forwarding websockets correctly. Check the browser dev tools for errors.
> 
> This is unlikely to be related to the addon.

Solved! Not exactly a websockets issue but I think still related to nginx. Cloudflare rocket loader was being blocked due to CSP. Addon loads correctly now after disabling rocket loader in cloudflare.  I believe there should be a way to get rocket loader to work with the correct header configuration in nginx; still researching this.
