### ISSUE TITLE
input_number/initial: integer value indicated as "Incorrect type"

### ISSUE THREAD

**Issue by hkhaka** [hassio-addons/addon-vscode#138]
# Problem/Motivation

input_number/initial integer value indicated as: 
Incorrect type. Expected "boolean"

![image](https://user-images.githubusercontent.com/45568793/95683019-f2472880-0be8-11eb-8b12-092eb839efac.png)

## Expected behavior

Integers allowed and not indicated as a problem.

## Actual behavior

See above

## Steps to reproduce

Add variable initial to any input_number

**Comment by frenck** [comment]
Fixed in https://github.com/keesschollaart81/vscode-home-assistant/pull/723
