### ISSUE TITLE
VS Code on a Raspberry Pi

### ISSUE THREAD

**Issue by IonutNeagu** [hassio-addons/addon-vscode#140]
# Problem/Motivation

````VS Code is now available for both Linux ARMv7 and ARM64 architectures. This means you can now officially use VS Code on a Raspberry Pi, Chromebook, and other ARM-based devices!````

https://code.visualstudio.com/updates/v1_50#_linux-arm-builds

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This add-on doesn't run VSCode directly, but code-server and has been available for the Raspberry Pi since February 2020.
