### ISSUE TITLE
vscode fails to start with "This socket has been ended by the other party"

### ISSUE THREAD

**Issue by maxandersen** [hassio-addons/addon-vscode#141]
# Problem/Motivation

when trying to access vscode it never shows up.

## Expected behavior

vscode starts.

## Actual behavior

log has this:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 2.8.1
 There is an update available for this add-on!
 Latest add-on version: 2.8.2
 Please consider upgrading as soon as possible.
 System: HassOS 4.13  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 0.115.6
 Home Assistant Supervisor: 247
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[00:25:16] INFO: Starting the code server...
[2020-10-16T22:25:17.330Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2020-10-16T22:25:17.334Z] info  Using config file ~/.config/code-server/config.yaml
[2020-10-16T22:25:18.075Z] info  Using user-data-dir /data/vscode
[2020-10-16T22:25:18.091Z] info  code-server 3.5.0 de41646fc402b968ca6d555fdf2da7de9554d28a
[2020-10-16T22:25:18.104Z] info  HTTP server listening on http://0.0.0.0:1337
[2020-10-16T22:25:18.105Z] info    - No authentication
[2020-10-16T22:25:18.105Z] info    - Not serving HTTPS
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:455:14)
    at d.write (/usr/local/lib/code-server/lib/vscode/out/vs/server/entry.js:177:808)
    at p.write (/usr/local/lib/code-server/lib/vscode/out/vs/server/entry.js:179:464)
    at g._writeNow (/usr/local/lib/code-server/lib/vscode/out/vs/server/entry.js:169:851)
    at Immediate.<anonymous> (/usr/local/lib/code-server/lib/vscode/out/vs/server/entry.js:169:789)
    at processImmediate (internal/timers.js:456:21)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EPIPE'
}
[2020-10-16T22:25:34.957Z] error VS Code exited unexpectedly with code 1
[2020-10-16T22:25:34.967Z] warn  discarding socket connection: vscode is not running
```

## Steps to reproduce

this is on a raspberry pi 4 with a fairly clean/no fuzz/recently installed homeassistant.

Only other plugins installed is deconz and check home assistant configuration.

**Comment by maxandersen** [comment]
noticed there was a 2.8.2 update - after updating I do not get the above error and vscode shows up but I keep getting "Cannont reconnect. Please reload the window." every few seconds.

**Comment by maxandersen** [comment]
okey - if I go through nabucasa https remote login then things starts working.

I guess this is what the warning talks about that when using unsecured access not all things wont' work ? I would consider that a pretty non-working :)

time to figure out how to get local https ;)

**Comment by sinclairpaul** [comment]
The https "error" is internal to the addon, the supervisor proxies to the addon via ingress, where it terminates SSL, the connects via HTTP.

What is interesting is the point you made that says it works via Nabu Casa, but not via direct to your (assumed) duckdns address, is this repeatable?  How do you resolve the address of your instance (i.e. if you `ping myha.mydomain.com` does it return your external address?).

**Comment by maxandersen** [comment]
I was just using homeassistant.local:8321 / local ip.

**Comment by maxandersen** [comment]
btw. I get similar error of "cannot reconnect. please reload the windows." after installing a vscode plugin that wanted reload...full restart "fixes it"

**Comment by maxandersen** [comment]
spoke too soon - its back again - getting "cannot reconnect. please reload the window." ...no errors in the log.

**Comment by sinclairpaul** [comment]
In that case likely a duplicate of #129 

Would be interested to see if http://myipaddress:8123 has any difference (though I would doubt it).

**Comment by maxandersen** [comment]
gave http://homeassistant.local:8123 a go again and now it works...so I guess the original bug seem fixed in latest vscode plugin release and yes, i'm affected by #129 which is quite annoying - it seem to run for some minutes and all is good...but then boom - goes bad. no errors visible in log.

I'll close this one and follow #129 - thanks!
