### ISSUE TITLE
vscode cannot be installed

### ISSUE THREAD

**Issue by CHRISS-74** [hassio-addons/addon-vscode#142]
Visual Studio Code 2.8.2 
This add-on is not available on your system. 

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.15
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7l
python_version | 3.8.5
supervisor | 249
timezone | Europe/Berlin
version | 0.116.4
virtualenv | false

**Comment by frenck** [comment]
See readme / documentation

![image](https://user-images.githubusercontent.com/195327/97039274-734cdb00-156c-11eb-8b95-d08b0c46563d.png)
