### ISSUE TITLE
Support ARMv7 / Raspberry Pi

### ISSUE THREAD

**Issue by daweizhangau** [hassio-addons/addon-vscode#143]
# Problem/Motivation

> Cannot install this extension on Raspberry Pi

## Expected behavior

> User should be able to install Visual Code extension on HA hosted by Raspberry Pi with ARMv7 cpu

## Actual behavior

> install button is gray

## Steps to reproduce

> Supervisor | Add-on Store | search the Visual Studio Code | click into the first result
> `This add-on is not available on your system. ` is shown

## Proposed changes

> [Visual Studio Code 1.5 supports ARMv7](https://code.visualstudio.com/updates/v1_50#_linux-arm-builds), please add that build and enable it in Add-on Store

**Comment by frenck** [comment]
This add-on runs code-server not the direct VSCode source.

Nevertheless, even if it was possible at this point, I would not publish it myself. VSCode is not lightweight and would swallow an armv7 Raspberry Pi (and thus a danger for running on the same ecosystem as Home Assistant).
