### ISSUE TITLE
Internal Server Error on Install

### ISSUE THREAD

**Issue by talun2075** [hassio-addons/addon-vscode#147]
I try to install over the supervisor store.

In the Log I got this:
20-12-10 12:45:34 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image hassioaddons/vscode-amd64 with tag 2.9.1.
20-12-10 12:45:34 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install hassioaddons/vscode-amd64:2.9.1 -> 500 Server Error for http+docker://localhost/v1.40/images/create?tag=2.9.1&fromImage=hassioaddons%2Fvscode-amd64: Internal Server Error ("Get https://registry-1.docker.io/v2/: dial tcp 35.174.73.84:443: connect: connection refused").

In the UI I got this:
500 Server Error for http+docker://localhost/v1.40/images/create?tag=2.9.1&fromImage=hassioaddons%2Fvscode-amd64: Internal Server Error ("Get https://registry-1.docker.io/v2/: dial tcp 23.22.155.84:443: connect: connection refused")

If I call the docker.io directly I got this json:

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}

Can you check it that is not a error on my new system?

**Comment by frenck** [comment]
That is an issue on your local network/system and out of control for the add-on.

**Comment by talun2075** [comment]
ok thx
