### ISSUE TITLE
Addon won't load on Chrome, loads fine on Opera

### ISSUE THREAD

**Issue by compujunk** [hassio-addons/addon-vscode#150]
# Problem/Motivation
> The VS Code addon will not load on Chrome, but loads fine on Opera

## Expected behavior
> that it also works in chrome

## Actual behavior
>get a blank sheet and nothing else

## Steps to reproduce

> It worked but suddenly it didn't work anymore what happened before why it doesn't work I don't know I don't see anything in the log files and my browser cache is cleared

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Works for me on Chrome. Anything in the logs?

**Comment by compujunk** [comment]
I don't see anything in the log files. 
I have also set the logs to log_level: trace but even then nothing appears in the log file of vsc. 
there is also nothing to see in the log files of HA.

it worked but i hadn't used it for a while. now i wanted to use it again and it stopped working. in the meantime I also removed and reinstalled it but still the same problem.

**Comment by frenck** [comment]
Chrome logs... inspect the page to see if there is anything visible in the chrome console.

**Comment by compujunk** [comment]
in the chrome console i get:

DevTools failed to load SourceMap: Could not load content for http://192.168.2.1:8123/api/hassio_ingress/W_sb0ULm2OYFWLRAzxsaZnCp0qbxivenG5oRJ5CyVJI/static/11f53784c58f68e7f4c5b3b8dae9407caa41725b/usr/local/lib/code-server/dist/pages/pages/vscode.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
loader.js:710 GET http://192.168.2.1:8123/api/hassio_ingress/W_sb0ULm2OYFWLRAzxsaZnCp0qbxivenG5oRJ5CyVJI/vs/code/browser/workbench/workbench.js net::ERR_ABORTED 404 (Not Found)
t.load @ loader.js:710
e.load @ loader.js:606
o @ loader.js:1620
s._loadModule @ loader.js:1632
s._resolve @ loader.js:1716
s.defineModule @ loader.js:1367
o @ loader.js:1835
(anonymous) @ (index):54

**Comment by frenck** [comment]
The first one is fine, the second error isn't nice. Browser cache?
Does it work when using incognito?

**Comment by compujunk** [comment]
yes in incognito its working.
I had already cleared the browser cache

**Comment by frenck** [comment]
Something is sticking in your browser. If incognito works, the application output is fine.

**Comment by compujunk** [comment]
okay i found the problem. I had a chrome extension "ezlinkpreview" installed which was the cause. after I turned it off for the site it worked again. the ticket can therefore be closed as far as I'm concerned. thank you for the help and time you spent on it.

**Comment by frenck** [comment]
Happy Holidays 🎄
