### ISSUE TITLE
Error with lovelace yaml files: Incorrect type. Expected "object"

### ISSUE THREAD

**Issue by browetd** [hassio-addons/addon-vscode#151]
# Problem/Motivation
I just installed this add-on, it worked fine for automations files (stored in /config/automations) but for lovelace, there is an error message for every view contained in a file.  I am storing the lovelace files into /config/lovelace (I am running Hass-io + supervisor 2020.12.7 + HA 2020.12.1).  
The ui-lovelace.yaml is just one line: "views: !include_dir_merge_list lovelace/" 
It is working fine in home-assistant (no error and display is as expected)
FYI, I am developping the views directly in yaml.

> (Why the issue was filed)

## Expected behavior
As home assistant is working fine, this error should maybe not be displayed... or maybe I have to correct my yaml files but I did not find any subject/blog on this error message nor in the documentation.

> (What you expected to happen)

## Actual behavior
See attached print screen for error message

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

![Sans titre](https://user-images.githubusercontent.com/46415133/103167197-6462fd00-4829-11eb-93c0-10ab0d7eb108.png)

**Comment by short4bmoney** [comment]
Your indentations look off. Try reformatting.

**Comment by browetd** [comment]
@short4bmoney That's what I thought but I tried different indentations and the only one with no error in VS is when "title" "path" "icon" and "cards" are completely on the left (4 columns to the left so even the "-" disappeared)... In this case no error in VS BUT lovelace is not displaying anything... so for the time being I prefer to keep the error in VS and have my views correctly displayed... Thank you for the proposal anyway...

**Comment by frenck** [comment]
That is not an add-on issue, an extension issue at best. Issues with the extension should be reported at the extension repository.
