### ISSUE TITLE
MQTT Light platform (Template schema) doesn't recognize the "state_template" configuration variable

### ISSUE THREAD

**Issue by lion06** [hassio-addons/addon-vscode#153]
# Problem/Motivation
light:
  - platform: mqtt
    schema: template
    name: "Shelly RGBW2"
    command_topic: "shellies/shellyrgbw2-aaaa/color/0/set"
    state_topic: "shellies/shellyrgbw2-aaaa/color/0/status"
    effect_list:
      - '0'
      - '1'
      - '2'
      - '3'
    command_on_template: >
      {"turn": "on"
      {%- if brightness is defined -%}
      , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
      {%- endif -%}
      {%- if red is defined and green is defined and blue is defined -%}
      , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
      {%- endif -%}
      {%- if white_value is defined -%}
      , "white": {{ white_value }}
      {%- endif -%}
      {%- if effect is defined -%}
      , "effect": {{ effect }}
      {%- endif -%}
      }
    command_off_template: '{"turn":"off"}'
    state_template: '{% if value_json.ison %}on{% else %}off{% endif %}'
    brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
    red_template: '{{ value_json.red }}'
    green_template: '{{ value_json.green }}'
    blue_template: '{{ value_json.blue }}'
    white_value_template: '{{ value_json.white }}'
    effect_template: '{{ value_json.effect }}'
    qos: 1

The error is "Property state_template is not allowed.". Looking at the documentation : https://www.home-assistant.io/integrations/light.mqtt/#template-schema. The configuration state_template is allowed under the Template Schema but not in the JSON or the Default Schema.

## Expected behavior

Valid configuration

> ike above

Configuration error message

> See attachment

You should update internal scheda reference

![immagine](https://user-images.githubusercontent.com/8861227/104172467-99b04300-5404-11eb-9c48-a5d53554d0a2.png)

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with the vscode extension. Please report the issue with the extension instead.
