### ISSUE TITLE
tilt_command_topic schema is string but VS.code reports it should be an integrer

### ISSUE THREAD

**Issue by vajonam** [hassio-addons/addon-vscode#155]
# Problem/Motivation

![image](https://user-images.githubusercontent.com/152501/104945069-2b302f80-5986-11eb-8ce2-2f7c07ff7031.png)

## Expected behavior
```    tilt_command_topic: "cmnd/blinds_01/PWM1"``` it should be string as per the documentation

**Comment by frenck** [comment]
That is an issue with the Home Assistant Config Helper extension for Visual Studio code, not the add-on.

Please report your issue upstream: <https://github.com/keesschollaart81/vscode-home-assistant/>

Thanks!

**Comment by vajonam** [comment]
thanks! and done! https://github.com/keesschollaart81/vscode-home-assistant/issues/929

**Comment by frenck** [comment]
No problem! If I have time I might take a look upstream 😉

**Comment by vajonam** [comment]
> No problem! If I have time I might take a look upstream

to save you some time. https://github.com/keesschollaart81/vscode-home-assistant/blob/1a5cff7304ee12d2634bf0714b5754064816d900/src/language-service/src/schemas/integrations/core/mqtt.ts#L1302

**Comment by frenck** [comment]
@vajonam I know... I wrote that file 😉 
I created that bug 😓
