### ISSUE TITLE
Extra identation inserted when pasting code.

### ISSUE THREAD

**Issue by krasatos** [hassio-addons/addon-vscode#160]
# Problem/Motivation
Pasting a code block adds extra identation on the first line of the block

## Expected behavior
Code pasted identically as copied

## Actual behavior
Extra idents added on the first line of the code block

## Steps to reproduce
Copy some lines of code then paste them in a clear line

I recorded a couple of gifs where i copy/paste the code and the identation is wrong.
**If i hit crtl+Z after pasting, the first line returns where it should be.**
This is probably some setting i have not set right?

Examples:
![yaml_paste_identation](https://user-images.githubusercontent.com/1773624/105159981-5f3b5a00-5b18-11eb-8494-7189d2b99987.gif)
![yaml_paste_identation2](https://user-images.githubusercontent.com/1773624/105159982-606c8700-5b18-11eb-8cac-457acf052702.gif)

**Comment by frenck** [comment]
This is an open bug report on the upstream visual studio code extension for Home Assistant. It is not caused by the add-on itself.
