### ISSUE TITLE
Possibility to integrate VSCode without HassIO

### ISSUE THREAD

**Issue by nicolasvila** [hassio-addons/addon-vscode#17]
# Problem/Motivation

I'd like the possibility to integrate VSCode without HassIO. Could you provide instruction for manual installation

## Expected behavior

Install the VSCode addon manually with Docker, pretty much like it is with hassio interface, then modify manually HA configuration to connect to the plugin.

## Actual behavior

Only available in hassio as docker image... :-(

**Comment by frenck** [comment]
You cannot use hassio add-ons on non-hassio systems.
If you run other installation types, it is up to you.
