### ISSUE TITLE
Adding AppDaemon HADashboard extension .dash to YAML

### ISSUE THREAD

**Issue by hjanum** [hassio-addons/addon-vscode#18]
# Problem/Motivation
We need to add .dash file extension to have the HADashboard configuration files treated as YAML.

## Proposed changes
It is a pretty easy change. I can make it via PullRequest, but wanted to make sure it was OK first. Just add the following to the settings.json file

"files.associations": {
        "*.dash": "yaml"
}

**Comment by frenck** [comment]
That is a user setting, not a setting I can provide on add-on level.
