### ISSUE TITLE
Mac with M1 not work

### ISSUE THREAD

**Issue by papy200** [hassio-addons/addon-vscode#203]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by papy200** [comment]
impossible to install with mac M1 !
have you a solution ????

**Comment by frenck** [comment]
That makes sense, as that is not a supported platform for installation that can install add-ons.

**Comment by papy200** [comment]
impossible for HA on the PI 4 ?

**Comment by frenck** [comment]
Raspberry Pi 4 is a supported platform by the Home Assistant project, this add-on could run on that.

**Comment by papy200** [comment]
![Capture d’écran 2021-03-19 à 11 28 55](https://user-images.githubusercontent.com/9330458/111766924-65468080-88a6-11eb-82d7-982ef94f75ae.png)

**Comment by papy200** [comment]
![Capture d’écran 2021-03-19 à 11 30 38](https://user-images.githubusercontent.com/9330458/111767066-8e671100-88a6-11eb-8602-ed277f2d3f65.png)

**Comment by frenck** [comment]
You run a 32 bits system, this add-on requires a 64 bits system.

**Comment by papy200** [comment]
ok. thanks !
