### ISSUE TITLE
VSCode v3 plugin not supported

### ISSUE THREAD

**Issue by DarrenRatcliffe** [hassio-addons/addon-vscode#21]
# Problem/Motivation

Updating plug in is 'greyed' out and says it isn't supported on my system

![image](https://user-images.githubusercontent.com/1911051/56117681-796a0080-5f60-11e9-8315-9cd18c820676.png)

System:

HASSIO

HassOS v2.11
HA 0.91.2

Running in a VM on Proxmox

## Expected behavior

Plug in to work

## Actual behavior

`19-04-15 08:21:50 ERROR (MainThread) [hassio.addons.addon] Add-on a0d7b954_vscode not supported on qemux86-64 with ['amd64', 'i386'] architecture`

I don't understand the reference to AMD architecture as my NUC is running Intel:

![image](https://user-images.githubusercontent.com/1911051/56118081-79b6cb80-5f61-11e9-9d90-0c643e77188f.png)

## Steps to reproduce

Click on update when running this configuration

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
You need to upgrade Home Assistant to 0.91.3.
