### ISSUE TITLE
Keyboard does not appear on iPhone

### ISSUE THREAD

**Issue by ab3lson** [hassio-addons/addon-vscode#210]
# Problem/Motivation

> I cannot edit my config file from my iPhone. 

## Expected behavior

> I should be able to edit my files through the add-on on a mobile device. 

## Actual behavior

> The add-on loads and I can click on the files, but when I click on the text window, the keyboard does not pop up. 

## Steps to reproduce

> Open the VSCode add-on on an iPhone and try to edit a file. The keyboard will not pop up so you cannot enter any text. 

## Proposed changes

> make the keyboard pop up.

**Comment by frenck** [comment]
That's nice. But using this on a mobile device makes no sense to me.
Feel free to contribute a fix, but I'm not investing time in that.
