### ISSUE TITLE
Platformio Intergration

### ISSUE THREAD

**Issue by marcinwrobel1984** [hassio-addons/addon-vscode#214]
# Problem/Motivation

How can I use platfirmio addon in VS Code for HA?
## Expected behavior

I would like to have fully functioning Platofmio addon for HA

## Actual behavior

I can install download addon, but it can not be installed

## Proposed changes

It could be good if we can have this addon enabled. I woul;k like to use intellisence of VS code and platfomio when I am creating ESPHOME custom components

**Comment by sinclairpaul** [comment]
Is there any reason why you wouldn't use the ESPHome addon to compile?, you can still use VSCode to edit.

**Comment by frenck** [comment]
Unfortunately, no. As it is not compatible.
