### ISSUE TITLE
Remove 'alias' property from auto-complete code snippets

### ISSUE THREAD

**Issue by fi-sch** [hassio-addons/addon-vscode#215]
# Problem/Motivation

It's not a problem per se, but recently added 'alias' property got really annoying in VS Code.
I don't use aliases at all. Even if I would, I wouldn't add them to each and every code block. However it's added each time I want to "automatically generate" code block (using VSC suggestions) for e.g. condition-state. Then I need to manually remove it from just added code. It is pretty frustrating experience to do so number of times in one hour. Not to mention that it makes coding using those snippets far less efficient and peasant.

## Expected behavior

As 'alias' property is purely optional and I would assume that it is not used often (e.g. for each condition and action), I would suggest to completely remove it from auto-generated snippets.

## Actual behavior

![alias](https://user-images.githubusercontent.com/59969726/112757281-66378a80-8fe9-11eb-9c18-cfc85819836c.jpg)

## Proposed changes

Same as written in 'expected behavior' section.

Thank you so much!

**Comment by frenck** [comment]
The alias will get a way more important function as of Home Assistant 2021.4, therefore as a best practice, it should be part of the snippet for that reason.

Home Assistant Core 2021.4 will introduce debug capabilities for past automation runs, having an alias makes them actually useful and readable.

**Comment by fi-sch** [comment]
Ok, thanks for your quick explanation. Anyways, I would still argue that it's an optional thing and if you don't need to debug it makes your code longer and forcing to type it at each code block makes the work somehow longer.


-- OFF-TOPIC HERE -- 
I have other issue connected with aliases – but completely different case. Could you be so kind and tell if I should create a separate issue for that?

Thing is with the alias vs id of automatons. It got changed a few releases ago how id's behave. Let me explain.
When you declare a new automation with:
```
- id: gate_open
  alias: 'Open the gate'
```
newly created automation will have Entity ID: automation.open_the_gate . It seems counter intuitive and it wasn't behaving like that in the past. Before said changes the 'id:' property would determine the Entity ID of an automation and 'alias:' would set up it's "friendly name". That's how I used it until it got changed and I surprisingly couldn't find some of my entities.
It's worth to mention that it wasn't described in any breaking changes (I read them with every release). Should we consider that an issue? 
-- OFF-TOPIC HERE --

**Comment by frenck** [comment]
`id` is a unique identifier. Using names like that could work, but a more random value is recommended (e.g., a UUID). the `id` is not related to entity ID in any way.

**Comment by fi-sch** [comment]
> `id` is a unique identifier. Using names like that could work, but a more random value is recommended (e.g., a UUID). the `id` is not related to entity ID in any way.

Is there any way to create automation with "human readable" entity ID that would be different that it's alias? I would swear that those two properties (id and alias) were working like that in the past. I could set up entity ID with 'id' and friendly name with 'alias'.
If that's not possible, then maybe it's a functionality that could be added in the future (perhaps as WTH request this year :) ).

**Comment by frenck** [comment]
`id` -> Registers the entity in the Home Assistant Entity Registry with that `id` as the unique ID for the entity. It must be unique for that reason (and thus recommending something arbitrary like a UUID). If an `id` is provided; the name, icon, area and entity_id can be customized in the Home Assistant frontend.

![image](https://user-images.githubusercontent.com/195327/112758814-7ef76e80-8ff0-11eb-97fd-26ba4d6a8f39.png)


When not overridden in the frontend (e.g., new automation or missing a `id` option), the `alias` will be used for generating an entity_id, which is a slug of the alias (the name).

Besides, automations can have a `description` as well.

![image](https://user-images.githubusercontent.com/195327/112758792-6ab37180-8ff0-11eb-8aa2-e859da45e4a8.png)

**Comment by fi-sch** [comment]
Yeah, I know that I can customize entities in the HA frontend or via YAML. But I'd like to be able to set up the entity ID (or maybe even an icon) directly in automation definition :) 

I think you get my point and I get yours. Thank you for your time. I won't abuse it anymore :) 
As this 'issue' is not an issue from your POV, I'm closing it by myself.

**Comment by frenck** [comment]
> But I'd like to be able to set up the entity ID (or maybe even an icon) directly in automation definition :)

Yeah, I love the YAML way too... however, all YAML configurations always slugified the names and tries to claim an entity_id. It is never guaranteed, it never has been. A consistent `id` is the only proper/good solution to that.
