### ISSUE TITLE
Git files are also getting parsed as Home Assistant in 3.3.0

### ISSUE THREAD

**Issue by realthk** [hassio-addons/addon-vscode#216]
# Problem/Motivation
During save of a .yaml file, excluded .git dirs are also parsed with erroneous result, and slowing down VSCode.

## Expected behavior
Don't parse .git dir, it is excluded in VSCode settings (and those files don't even have .yaml extension anyway)

## Actual behavior
Since version 3.3.0 I get messages like these when saving a .yaml file if there is a .git dir under its path.
Reverting VSCode to 3.1.1 solves the problem.
![screenshot-homeassistant local_8123-2021 03 29-08_52_19](https://user-images.githubusercontent.com/5654575/112798846-c839d380-906d-11eb-8f2e-41863116b603.png)

## Steps to reproduce
Supervised 2021.3.4 installation with VSCode addon 3.3.0 under Debian 10 on x86_64 with automation (or any other HA yaml) files in a Git repo, so there is a .git folder existing under their path.

**Comment by frenck** [comment]
Oh darn, that is bug! Thanks for reporting this!
