### ISSUE TITLE
Avoid double quote to single quote conversion when saving with ctrl-s

### ISSUE THREAD

**Issue by hklages** [hassio-addons/addon-vscode#218]
# Problem/Motivation

When editing "automations.yaml" in vscode double quotes are the default and inside double quotes single quotes are used. 
When saving (ctrl-s) all double quotes are being converted in single quotes and single in 2 times single quotes. 

After editing the file with the visual editor and using vscode again the game starts again. 

## Expected behavior

No conversion when saving (ctrl s)

## Actual behavior

Conversion double to single quote when saving

## Steps to reproduce
see top

## Proposed changes

It's nothing serious as the conversion works fine but the behavior is a bit confusing. I like to stick to the standard - but in Home Assistant I could not figure out what the standard is: double or single quote

**Comment by frenck** [comment]
Te he formatting is automatically done in VSCode by the Pretier formatter. You can disable that behavior in your own VSCode workspace settings if you like.

The Home Assistant YAML style guide uses double quotes.

https://developers.home-assistant.io/docs/documenting/yaml-style-guide
