### ISSUE TITLE
lost interface

### ISSUE THREAD

**Issue by Langtonpaul** [hassio-addons/addon-vscode#22]
# Problem/Motivation

> Ive broken my cscode editor I was adding a folder to config and could not get back to see all files in config just the new one I created I know this is probably user error but I tried searching for config now all I get is a black screen in the dark gray. Have tried reinstalling cscode and clearing cache but no change. Can you point me in right direction please. Sorry if this is not the right place tp post.

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Please use the second solution from the documentation: 

<https://github.com/hassio-addons/addon-vscode#known-issues-and-limitations>
