### ISSUE TITLE
Too mutch cpu usage

### ISSUE THREAD

**Issue by roschi02** [hassio-addons/addon-vscode#225]
I'm using an Raspberry Pi 4 8GB and the Addon is using too mutch resources. If this is normal then, it's my bad but I don't think it should do that. [Here is a picture of the usage](https://drive.google.com/file/d/1wRux2Ni09jFNNHedVMgL4zkoGtQnYuJo/view?usp=sharing)

**Comment by frenck** [comment]
This is not normal, and usually caused by having a symlink loop in your configuration. The add-on by itself does not consume this.

**Comment by roschi02** [comment]
> This is not normal, and usually caused by having a symlink loop in your configuration. The add-on by itself does not consume this.

and how do i fix it?

**Comment by frenck** [comment]
Remove the loop :)

**Comment by roschi02** [comment]
But I don't know what is causing the loop.

**Comment by frenck** [comment]
Check the vscode Home Assistant extension logs in vscode. It will probably show something like:

`/config/config/config/config/config/config/config/config`....

**Comment by roschi02** [comment]
just shows this 

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 3.3.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.3.4
 Home Assistant Supervisor: 2021.03.9
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:51:46] INFO: Starting the code server...
[2021-04-06T18:51:47.889Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2021-04-06T18:51:49.373Z] info  code-server 3.9.1 e0203f2a36c9b7036fefa50eec6cf8fa36c5c015
[2021-04-06T18:51:49.377Z] info  Using user-data-dir /data/vscode
[2021-04-06T18:51:49.422Z] info  Using config file ~/.config/code-server/config.yaml
[2021-04-06T18:51:49.422Z] info  HTTP server listening on http://0.0.0.0:1337 
[2021-04-06T18:51:49.422Z] info    - Authentication is disabled 
[2021-04-06T18:51:49.423Z] info    - Not serving HTTPS `

**Comment by roschi02** [comment]
just shows this 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 3.3.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.3.4
 Home Assistant Supervisor: 2021.03.9
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:51:46] INFO: Starting the code server...
[2021-04-06T18:51:47.889Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2021-04-06T18:51:49.373Z] info  code-server 3.9.1 e0203f2a36c9b7036fefa50eec6cf8fa36c5c015
[2021-04-06T18:51:49.377Z] info  Using user-data-dir /data/vscode
[2021-04-06T18:51:49.422Z] info  Using config file ~/.config/code-server/config.yaml
[2021-04-06T18:51:49.422Z] info  HTTP server listening on http://0.0.0.0:1337 
[2021-04-06T18:51:49.422Z] info    - Authentication is disabled 
[2021-04-06T18:51:49.423Z] info    - Not serving HTTPS

**Comment by roschi02** [comment]
in debug mode i get this all the time

error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/local/lib/code-server/out/node/vscode.js:206:19)
    at VscodeProvider.<anonymous> (/usr/local/lib/code-server/out/node/vscode.js:198:30)
    at step (/usr/local/lib/code-server/out/node/vscode.js:63:23)
    at Object.next (/usr/local/lib/code-server/out/node/vscode.js:44:53)
    at fulfilled (/usr/local/lib/code-server/out/node/vscode.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by roschi02** [comment]
if i go to the config there is an other config folder and so on 
how do i solve this

**Comment by frenck** [comment]
Removing the symlink that causes the loop.

Make sure `/config/config` is indeed a symlink.

```bash
ls -la /config/config
```

If so, delete it like this: `rm /config/config`

That should solve it.

**Comment by roschi02** [comment]
so i shodnt have an other config folder inside of config?

**Comment by frenck** [comment]
What is the use of a symlink pointing to its parent folder? That creates an infinite loop.
Keep it if you like, but don't blame the add-on for taking up high CPU usage (as it tries to index/read the infinite configuration folders you have).

**Comment by roschi02** [comment]
Do you know what is causing the infinite folder?
im just curious

**Comment by frenck** [comment]
Nope, sorry.

**Comment by roschi02** [comment]
Oh okay so if its back just remove it again

**Comment by frenck** [comment]
You are asking me for details on how your system works. I don't know what makes that folder, thus I cannot tell you if you have to remove it again in the future.
