### ISSUE TITLE
Accessing /config/.storage/

### ISSUE THREAD

**Issue by spencerthayer** [hassio-addons/addon-vscode#237]
In the example image there is an indication that `/config/.storage/` is accessible via in browser Visual Studio Code. How does one enable that? Thanks!

![Visual Studio Code, accessible through the browser.](https://github.com/hassio-addons/addon-vscode/raw/main/images/screenshot.png)

**Comment by sinclairpaul** [comment]
Excluded files are specified in the VSCode settings, under files.exclude

There is a reason it is hidden by default, editing it directly is strongly not recommended.

**Comment by spencerthayer** [comment]
> Excluded files are specified in the VSCode settings, under files.exclude
Ah, I see. Thanks @sinclairpaul, I found the settings for files.exclude in the _.code-sever/[settings.json](https://github.com/hassio-addons/addon-vscode/blob/0c9a477d632ad2c71a45494a20c200984695289d/vscode/rootfs/root/.code-server/settings.json)_.

For anyone else who wants to access _.storage_ add the following to your _settings.json_.
```YAML
    "files.exclude": {
        "**/.storage": false
    }
```

> There is a reason it is hidden by default, editing it directly is strongly not recommended.
Yeah, I know. But the reality of Home Assistant is that we are forced to manage dead or duplicate entities by editing _core.entity_registry_ [from time to time](https://www.reddit.com/r/homeassistant/comments/lq7h9a/delete_entity_like_a_civilized_person). In fact I am going to do that right now. Thanks agian.

**Comment by frenck** [comment]
> Yeah, I know. But the reality of Home Assistant is that we are forced to manage dead or duplicate entities by editing core.entity_registry from time to time. In fact, I am going to do that right now. Thanks again.

This is incorrect, and if this happens, this is a bug that should be reported and fixed for that specific integration.

**Comment by spencerthayer** [comment]
> This is incorrect, and if this happens, this is a bug that should be reported and fixed for that specific integration.

In theory you are correct but in practice the reality is different. You can read a Reddit thread talks about that reality [here](https://www.reddit.com/r/homeassistant/comments/lq7h9a/delete_entity_like_a_civilized_person/).

**Comment by frenck** [comment]
I am aware of the possible issues, I am just saying they should be reported. If they aren't raised as an issue, it isn't tree likely to get fixes. Working around a problem is never solving it.
