### ISSUE TITLE
Feature Request: SSH access for connecting with desktop VSCode

### ISSUE THREAD

**Issue by mdegat01** [hassio-addons/addon-vscode#238]
# Problem/Motivation

I was looking up ways to use my desktop Visual Studio Code app for easily editing Home Assistant configuration files. This addon is nice but I would personally prefer to use my Mac app rather then editing in the window. My Mac has a lot more horsepower and I can reuse my existing extensions and settings instead of trying to replicate them somewhat into another VS Code deploy.

I found [this discussion](https://github.com/cdr/code-server/discussions/2786) where the author suggested it was quite easy to do this by simply using the [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) extension. I tried it but ran into an issue. It seems to look for a `.vscode-server` configuration in the home directory and expects that to be the machine running the vscode server. In the typical HA setup that's not what happens. When you SSH in via the SSH & Web Terminal addon the `/root/.vscode-server` folder does exist but that isn't the container actually running the code server. And so when it tries to run there are issues because its there are dependencies missing in the SSH & Web Terminal container its operating in.

So I was wondering if it would be possible to allow SSH access directly to the VSCode add-on? It could be quite limited, no fancy setup options like the SSH & Web Terminal add-on has. Just an option to put a key and a way to expose the port with instructions saying this is intended only for use with the Remote - SSH extension to allow editing from the desktop app.

If you like the idea I can take a spin at doing the PR myself. This is a significant enough change though that I didn't want to sink any time on it without first getting approval on the idea.

Removing the rest of the issue template since it doesn't apply. Everything is working as expected, just a thought on a potential enhancement.

**Comment by frenck** [comment]
That won't work as VSCode still can't handle Alpine to run its remote agent in.

**Comment by mdegat01** [comment]
Glad I asked. Oh well, thanks for letting me know.

**Comment by frenck** [comment]
I have a project to "fix" that, it actually works and is used by a couple of testers. But far from done. Too much in flux/progress at this point to finish it.

**Comment by mdegat01** [comment]
Oh interesting. Is the test version in a separate repo? I don't see any branches on this one. What all is left to do, any particular tasks you're looking for help on I could look at?
