### ISSUE TITLE
Git integration is very slow.

### ISSUE THREAD

**Issue by JayRHa** [hassio-addons/addon-vscode#252]
# Problem/Motivation
The Git integration in VS code is very slow. Its more or less not possible to add changes to the stage changes or execute an commit.
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior
Very slow. The other VS code functions are fast only the git menu is slow.
> (What actually happened)

## Steps to reproduce
Its hard to say how to reproduce.
> (How can someone else make/see it happen)

## Proposed changes
Help me how I can troubleshoot and fix the issue.
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The speed of this depends on the speed of the device/storage medium used.
Besides, from an add-on perspective, there is nothing I can do to improve that; as add-ons wrap existing applications, we don't write them.
