### ISSUE TITLE
Doesnt work on raspberry pi 3+

### ISSUE THREAD

**Issue by dorgan-brillio** [hassio-addons/addon-vscode#267]
Not compatible with Raspberry pi:

![Screen Shot 2021-05-26 at 5 29 35 PM](https://user-images.githubusercontent.com/78161794/119733750-f78b7780-be47-11eb-9872-c33aa37c65f7.png)

**Comment by frenck** [comment]
Correct.

**Comment by polyzois** [comment]
Is there a reason? There are binaries of vs code for Raspberry these days so I am guessing it must be something else?

**Comment by polyzois** [comment]
Ok I found the reason in another issue. "you need a 64 bits system". So if other hardware requirements are met I guess @dorgan-brillio  you can try a 64bit build of HA?
