### ISSUE TITLE
 Add-on config 'auto_uart' is deprecated, use 'uart'

### ISSUE THREAD

**Issue by pierinho** [hassio-addons/addon-vscode#274]
# Problem/Motivation

i have this in my Hassio Log:

21-06-24 11:41:39 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Visual Studio Code
21-06-24 11:41:39 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of AppDaemon 4
21-06-24 11:41:39 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of VSCode Remote

none of these add-ons are currently installed.

**Comment by frenck** [comment]
This add-on does not have that anymore for quite some time (since September 2020 to be more precise).
So, if you still have that issue, then that message is not from this add-on.

🤷
