### ISSUE TITLE
Github authentication failed

### ISSUE THREAD

**Issue by rostislav-palivoda** [hassio-addons/addon-vscode#280]
# Problem/Motivation

VS Code extension does not allow to push config file change in to github from UI. 

## Expected behavior

After calling git push from console or from UI the popup shows message:

The extension 'GitHub' wants to sign in using GitHub.
    [Allow] [Cancel]

Expected to authenticate to Github and pass GIT push in HASS.

## Actual behavior

After redirect back from Github in to HASS a white page with message "404: Not Found". 
HASS version is 6.6 

http://hass.lan:8123/callback?vscode-requestId=ffff9799-e034-4fc1-bb0a-1102753120df&vscode-scheme=code-oss&vscode-authority=vscode.github-authentication&vscode-path=%2Fdid-authenticate&code=d7da3d0d2dc42115d8a9&state=10f02bee-7441-441c-bb8a-4a0d85d9196e

## Steps to reproduce

The extension 'GitHub' wants to sign in using GitHub.
    [Allow] [Cancel]

User click Allow, redirected to GitHub page, enters github Username and Password, redirected back. Should see the changes are committed in to github. Actually error message Not Found on a blank page.

## Proposed changes

Implement authentication.

**Comment by frenck** [comment]
That won't work indeed, as Home Assistant won't pass that along.

I need to update the documentation to add that as a known issue and limitation.

Using SSH keys is the only working way via the add-on.

**Comment by rostislav-palivoda** [comment]
Maybe there is a change to setup routing rule on HassOS to pass it to the plugin?

**Comment by frenck** [comment]
> It looks like a super comfortable feature for new users.

Sure, but not something I can do anything about.
