### ISSUE TITLE
Not compatible with Home Assistant OS 6.1?

### ISSUE THREAD

**Issue by amklose** [hassio-addons/addon-vscode#284]
# Problem/Motivation

I had to completely wipe my system and reinstall HassOS. I wanted to reinstall the VS Code add-on but it says it's not compatible with my processor or OS version. The processor is the same as it was before, but I think I'm on the most recent version of HassOS (6.1)

Do I just have to wait for an update for this add-on?

![image](https://user-images.githubusercontent.com/756265/124035000-8c424180-d9c1-11eb-97b7-ad10ff3e86db.png)
![image](https://user-images.githubusercontent.com/756265/124035042-98c69a00-d9c1-11eb-8515-5e455e0b565d.png)

**Comment by frenck** [comment]
You need a 64 bits OS, you have installed the 32 bits version. Thus not compatible with the operating system you have installed on your device (as per message).

Also documented in the add-on documentation here:

<https://github.com/hassio-addons/addon-vscode/blob/main/vscode/DOCS.md#known-issues-and-limitations>

**Comment by amklose** [comment]
@frenck AAAHHH!! Good catch. It was late and I grabbed the wrong image from the HassOS github page. Thanks for pointing that out so quickly!
