### ISSUE TITLE
Jupyter version incompatibility

### ISSUE THREAD

**Issue by gcobb321** [hassio-addons/addon-vscode#286]
# Problem/Motivation

> jupyter-2021.6.0 Extension is not compatible with Code 1.56.1. Extension requires: 1.56.0. Error message in VS Code log file.

## Expected behavior

> Extension are loaded properly

## Actual behavior

> Jupyter extension loading message and Python loading message displayed at the bottom of the window keeps redisplaying as the extensions keep retrying to load. The error message appears in the VSCode log on the VSCode add-on screen

## Steps to reproduce

> Run vs code

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Not much I can do about that, there isn't a newer codeserver available compatible with that version.

**Comment by gcobb321** [comment]
FWIW - Since I use this for Python development on my iPad when I’m not at my main computer (iCloud3 device tracker custom component), I had installed the Python extension, which requires Jupyter. I deleted and reinstalled the VSCode add on with all extensions I had been using except Python and Jupyter. Everything appears to now work.
