### ISSUE TITLE
Websocket connection failed: One or more reserved bits are on

### ISSUE THREAD

**Issue by cbzink** [hassio-addons/addon-vscode#30]
# Problem/Motivation

VS Code shows black screen, no interface loads.

## Expected behavior

VS Code should load.

## Actual behavior

VS Code shows black screen, no interface loads.

Browser console infinitely throws `ide.main.c231df.js:53 WebSocket connection to 'wss://redacted/api/hassio_ingress/redacted/' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1`.

## Steps to reproduce

Fresh install, default settings.

**Comment by cbzink** [comment]
[PEBCAK](https://en.wiktionary.org/wiki/PEBCAK). Updating to 0.91.4 fixed the issue. Thanks for all the hard work on this addon!

**Comment by frenck** [comment]
@cbzink 👍
