### ISSUE TITLE
Please Document Firefox Incompatibility 

### ISSUE THREAD

**Issue by throker** [hassio-addons/addon-vscode#301]
# Problem/Motivation

I thought it didn't work, turns out it doesn't like Firefox.

## Proposed changes

Please add a Note to the Documentation that VSCode may not work in Firefox. It would have saved me a lot of time. I don't really care that it doesn't work in FF, but I was just getting a black screen.

I don't think it's worth your time to try to fix the Firefox compatibility, but a note in the docs would be really nice.

Thanks for all your awesome add-ons.

**Comment by frenck** [comment]
This is not a problem with this add-on, but with Home Assistant or Firefox.

**Comment by 7R0J4Ner** [comment]
Thank you @throker 
I spent hours with it yesterday because I thought an update was to blame.
The same applies to the deCONZ plugin, by the way.
