### ISSUE TITLE
Error messages with SSH FS addon

### ISSUE THREAD

**Issue by flaektrem** [hassio-addons/addon-vscode#307]
# Problem/Motivation

> Error message "Could not connect to React dev server. Not running?" when trying to edit existing or add new SSH connection configuration with SSH FS addon
More details here:
[https://github.com/SchoofsKelvin/vscode-sshfs/issues/279](url)

**Comment by flaektrem** [comment]
@sinclairpaul 
I asked the author of SSH FS how the addon detected development mode, as you suggested. 
He answered "_I basically check whether ExtensionContext.extensionMode is different from vscode.ExtensionMode.Production_"
and showed me this code:
https://github.com/SchoofsKelvin/vscode-sshfs/blob/4eef87a7e8bfb4f8013c031381abb406dda11b46/src/extension.ts#L29-L32

Maybe this can help?

**Comment by sinclairpaul** [comment]
As mentioned on Discord, the addon runs Code-Server, which may deal with Extensions differently.

As was also mentioned, the addon is designed to assist in managing your HA configuration, there really isn't anything that can be done here.
