### ISSUE TITLE
Cannot install in HASSIO

### ISSUE THREAD

**Issue by nickm324** [hassio-addons/addon-vscode#31]
# Problem/Motivation

Not Available for install

## Expected behavior

Be able to install the addon

## Actual behavior

Message says This add-on is not available on your system.

## Steps to reproduce

Click Hassio on the side bar, go to Addon Store, click the VS Code item
## Proposed changes

If its not available for Hassio should be removed from the addons store.

**Comment by frenck** [comment]
You need at least Home Assistant 0.92.

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/56757067-9c33ba80-6793-11e9-925f-ed45230d8cea.png)

**Comment by nickm324** [comment]
Ok well I dont see that anywhere in the Addon Store info page for it.
![image](https://user-images.githubusercontent.com/6774571/56757165-2d397000-6759-11e9-9257-b1455608b660.png)

**Comment by frenck** [comment]
Feel free to open a feature request @ hass.io to improve on the error message.
I do agree on the error message shown by Hass.io, to contain not enough information. Nevertheless, that is out of control for an add-on developer.

**Comment by nickm324** [comment]
I agree, thanks for the feedback.
