### ISSUE TITLE
VS Code in Home Assistant Now not Useable

### ISSUE THREAD

**Issue by CeasarPrime** [hassio-addons/addon-vscode#310]
# Problem/Motivation

> (Why the issue was filed) VS Code not available to use on Home Assistant

## Expected behavior

> (What you expected to happen)  VS Code previously was used successfully on my HA application on a Raspberry Pi 4, 8 GB, with a 64 GB micro SD card.  I am using Home Assistant OS 6.2. It worked fine before.  

## Actual behavior

> (What actually happened)  VS Code one day just could not be accessed.  I see this note when trying to re-install it:  "This add-on is not compatible with the processor of your device or the operating system you have installed on your device."

## Steps to reproduce

> (How can someone else make/see it happen)  I have no idea how to reproduce this.  I would like to know how to fix it and prevent it from happening again.  I have found VS Code a very good editor, and want to continue to use it.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)  On the theory that my HA installation has been corrupted somehow, perhaps I should just start again?

**Comment by frenck** [comment]
> VS Code one day just could not be accessed. I see this note when trying to re-install it: "This add-on is not compatible with the processor of your device or the operating system you have installed on your device.

You need a 64 bits operating system to use this add-on (as per add-on documentation, and per message you are pasting).

It has been listed multiple times here as well:

<https://github.com/hassio-addons/addon-vscode/blob/main/vscode/DOCS.md#known-issues-and-limitations>

This is not a bug.

**Comment by CeasarPrime** [comment]
Thanks you are quite right.  I was using a 32 bit system when I thought is was 64 bit.  That has now been corrected and VS Code loads and runs fine.  I regret the inconvenience to you.

**Comment by frenck** [comment]
>  I regret the inconvenience to you.

Don't worry m8! I'm happy you got it resolved 👍  ❤️
