### ISSUE TITLE
error installing add on

### ISSUE THREAD

**Issue by pacfigueiredo** [hassio-addons/addon-vscode#314]
I´m trying to istall  the add-on on Home Assistant 2021.8.6  (core-2021.8.6 + supervisor-2021.08.1) and i´m getting this error:

Failed to install add-on
Can't install ghcr.io/hassio-addons/vscode/amd64:3.6.2: 404 Client Error for http+docker://localhost/v1.41/images/ghcr.io/hassio-addons/vscode/amd64:3.6.2/json: Not Found ("no such image: ghcr.io/hassio-addons/vscode/amd64:3.6.2: No such image: ghcr.io/hassio-addons/vscode/amd64:3.6.2")

How can it be fixed?
Thanks

**Comment by cpyarger** [comment]
This is also happening for me. Any suggestions?

**Comment by pacfigueiredo** [comment]
yep. Not enough space available for add on install

**Comment by cpyarger** [comment]
I am only using ~20% of my available space.
