### ISSUE TITLE
Issues reinstalling Addon

### ISSUE THREAD

**Issue by cpyarger** [hassio-addons/addon-vscode#316]
# Problem/Motivation

> Tried reinstalling addon

## Expected behavior

> Addon installs

## Actual behavior

> install fails with the following message

```Can't install ghcr.io/hassio-addons/vscode/aarch64:3.6.2: 500 Server Error for http+docker://localhost/v1.41/images/ghcr.io/hassio-addons/vscode/aarch64:3.6.2/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument")```

## Steps to reproduce

> Click install in the addons repository

**Comment by sinclairpaul** [comment]
Try ```ha supervisor repair``` from the SSH addon (or somewhere with the HA cli).

If that fails, please seek help on the HA discord or forums, this isn't anything the addon can fix.

**Comment by cpyarger** [comment]
This worked (:
