### ISSUE TITLE
Custom yaml tag for !secret

### ISSUE THREAD

**Issue by pbavinck** [hassio-addons/addon-vscode#32]
# Problem/Motivation
VS Code YAML validator highlights "!secret" as invalid. As this is very common in Home Assistant configs and is valid, adding a custom YAML tag would make sense.

## Steps to reproduce
Open a yaml file with a !secret reference in it and the YAML validator will mark the file red (error).

## Proposed changes
Would be nice if the vs code user settings.json would already contain the custom yaml tag for !secret. I played around and this does seem to work;
```
"yaml.customTags": [
    "!secret scalar",
]
```

**Comment by frenck** [comment]
Already in the current version....
