### ISSUE TITLE
AZERTY layout is ignored in vscode shortcuts

### ISSUE THREAD

**Issue by vlebourl** [hassio-addons/addon-vscode#321]
# Problem/Motivation

> With an AZERTY keyboard, hitting Cmd-Z (on a mac) closes the tab instead of doing "undo".

## Expected behavior

> Cmd-Z is mapped to Undo, so expecting it.

## Actual behavior

> Cmd-Z is closing the tab

## Steps to reproduce

> Hit Cmd-Z on an AZERTY keyboard

## Further test

The editor seems to know the layout, but trying to change the shortcuts in the preferences doesn't. In the preferences, the layout seems to always be QWERTY.

**Comment by vlebourl** [comment]
I had a question in the forum about it, but I do believe it's a bug, so here it is. Forgive me if it's not the place...
https://community.home-assistant.io/t/home-assistant-community-add-on-visual-studio-code/107863/444

**Comment by vlebourl** [comment]
Hey, sorry to insist, but this is super annoying having the current tab closed when trying to "undo"... I've tried modifying the keybindings, but it's not working either... Any way I can help fix this? 
Cheers

**Comment by laurentdebricon** [comment]
i confirm it is solved.
