### ISSUE TITLE
limited functionality on http connections.

### ISSUE THREAD

**Issue by dbuezas** [hassio-addons/addon-vscode#322]
# Problem/Motivation

> The GitGraph extension doesn't show the graph

## Expected behavior

> After installing the GitGraph extension and opening `>Git Graph: View Git Graph (git log)` it should show the git graph

## Actual behavior

> a blank page is shown instead

## Steps to reproduce

> 1. Open homeassistant locally in the browser (`e.g http://homeassistant.local:8123/`)
> 2. Install the GitGraph extension
> 3. Open command palette and select `>Git Graph: View Git Graph (git log)` 

## Proposed changes

> Update code-server to v3.12.0
> Rationale: it updates vscode to 1.60.0

## Am I sure?

> Yes, very much so. In [this git-graph closed issue](https://github.com/mhutchie/vscode-git-graph/issues/535#issuecomment-872171523) @oschulz shows that the bug present in VSCode v1.56.1 was fixed in VSCode v1.56.2.
> To confirm I checked the console and indeed I see `Error: Service Workers are not enabled in browser. Webviews will not work.` as they described. Furthermore, the problem is not there when accessing through https (through HomeAssistantCloud)

### Loading from local network:
![image](https://user-images.githubusercontent.com/777196/134904560-cda8e404-7b6c-40e1-9f2b-4c9c7ee9b12f.png)
![image](https://user-images.githubusercontent.com/777196/134904299-27f0b687-a12b-401d-b03c-c1f815f0969a.png)

### Loading from HA Cloud (HTTPS connection)
![image](https://user-images.githubusercontent.com/777196/134904254-f38dd64f-d6b9-455a-b7e5-5ef545b72839.png)

**Comment by frenck** [comment]
> limited functionality on http connections

That is correct, the add-on also warns for that. 
These are browser limitations and not add-on limitations.

**Comment by dbuezas** [comment]
I see. Thanks for answering.

Irrespective of that, updating code-server does fix this particular problem (see Proposed changes)

**Comment by frenck** [comment]
That will happen automatically when I get to its maintenance cycle.
