### ISSUE TITLE
"Property state_class not allowed"

### ISSUE THREAD

**Issue by DJF3** [hassio-addons/addon-vscode#326]
originally posted [here](https://github.com/home-assistant/home-assistant.io/issues/19615).

# Problem/Motivation

> The MQTT integration doc mentions "state_class" as a variable. VS Code tells me "`Property state_class not allowed`"

## Expected behavior

> This should not be marked as "not allowed"

## Steps to reproduce

> In VS code, edit configuration.yaml and add
```
  - platform: mqtt
    state_topic: "mcsMQTT/power/Elektra_huidig_verbruik"
    state_class: measurement
    unit_of_measurement: "kWh"

```
And while we're on this topic: 
the same seems to apply for `device_class: gas`. 

The error message: `Value is not accepted. Valid values: "battery", "current", "energy", "humidity", "illuminance", "power", "power_factor", "pressure", "signal_strength", "temperature", "timestamp", "voltage".yaml-schema: http://schemas.home-assistant.io/configuration(1)`

According to examples I've seen "gas" is a totally valid option.

**Comment by Benchamoneh** [comment]
This is still an issue as of 3.6.2, I have just encountered it and have had the same experience as @DJF3. VSCode mentions the property is not allowed but thankfully HA does not throw errors if it is included. I think VSCode just needs to be updated for the newer properties.

**Comment by frenck** [comment]
This isn't an add-on issue, but an issue that should be reported with the VSCode extension for Home Assistant.

Which can be found here: <https://github.com/keesschollaart81/vscode-home-assistant/issues>
