### ISSUE TITLE
Sensor Device_class: update not recognised

### ISSUE THREAD

**Issue by Ogurtsov-D** [hassio-addons/addon-vscode#331]
The device_class: update for binary_sensor is not recognised by VS, however the sensor itself works fine.
![vna](https://user-images.githubusercontent.com/78870757/138082059-1bf67775-1ff2-4183-95fc-b2226a7001bb.jpg)
the problem is only with template binary sensors. for other binary sensors this class is recognized correctly.

**Comment by seganku** [comment]
binary_sensor should also recognize "running" and "tamper":
https://www.home-assistant.io/integrations/binary_sensor/

(but it does not)

**Comment by sinclairpaul** [comment]
This is an extension issue please log it at https://github.com/keesschollaart81/vscode-home-assistant/issues
