### ISSUE TITLE
GitHub Copilot

### ISSUE THREAD

**Issue by cjescudero** [hassio-addons/addon-vscode#343]
# Problem/Motivation
I would like to use the GitHub extension Copilot, since it would be very interesting to take advantage of this code generator. This is the extension: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot&ssr=false#review-details 

## Expected behavior

When searching for extensions in the marketplace for "GitHub Copilot", it should appear.

## Actual behavior
It doesn't appear in the search of the marketplace. In a Visual studio install in my computer, there is no problem.

## Steps to reproduce

Search for "GitHub Copilot" in the market place extensions search bar.

## Proposed changes

Review why this extension is not show when searching.

**Comment by frenck** [comment]
> When searching for extensions in the marketplace for "GitHub Copilot", it should appear.

Copilot is not available on the non-official/open marketplace.
This is a limitation Microsoft has, they don't allow the main store to be used.

> I would like to use the GitHub extension Copilot, since it would be very interesting to take advantage of this code generator.

You could try and install it manually by downloading the extension from the marketplace, but I doubt it will work in this setting.

**Comment by Apocrathia** [comment]
Manually downloading the .vsix file and trying to install via `code --install-extension <file>` appears to work. However, it seems to break code-server. I doubt we'll get to use Copilot with code-server until it is out of beta, and even that is uncertain.
