### ISSUE TITLE
Firefox problem: document + test/share workaround?

### ISSUE THREAD

**Issue by DJF3** [hassio-addons/addon-vscode#353]
# Problem/Motivation

Pls document workaround VS Code / Firefox problem

## Expected behavior

That the documentation would have told me that there is a problemw with Firefox. Don't care who's at fault but it would have saved me a lot of time. 

## Actual behavior

> in this [issue](https://github.com/hassio-addons/addon-vscode/issues/301) the same thing was requested but closed without fix: "_This is not a problem with this add-on, but with Home Assistant or Firefox._" 
> Why would you not share this info _regardless of the root cause_? And a possible workaround -->

## Steps to reproduce

> In FF, open VS Code add-on

## Proposed changes

> Document the problem with Firefox and the fix that worked for me: disabling "Enhanced Tracking Protection" in Firefox FIXED the issue for me. (press the shield icon left of the URL)

**Comment by frenck** [comment]
Really, we don't care. We don't report issues with Windows or macOS either, nor do we document issue with your car that make it impossible for you to get home from work and use your computer.

**Comment by DJF3** [comment]
> Really, we don't care. We don't report issues with Windows or macOS either, nor do we document issue with your car that make it impossible for you to get home from work and use your computer.

wow <silence>... 
That may have been my last report trying to make the lifes of other/new users easier. (or contribute in any other way)

To stay with the car analogy: 
I think this more like buying a car that **_works on highway_A_** but **_not on highway_B_**. 

It is quite reasonable to assume that there are Firefox users.  
Given your argument you could remove _all_ of the [known issues](https://github.com/hassio-addons/addon-vscode/blob/main/vscode/DOCS.md#known-issues-and-limitations
) and limitations as they are all just as reasonable as the Firefox limitation - _which even has a workaround!_ 

Anyhow, you made your point, I will stop contributing.

**Comment by frenck** [comment]
> wow ...
> That may have been my last report trying to make the lifes of other/new users easier. (or contribute in any other way)

I feel sorry for you a bit that is the way you think you should respond to the fact your suggestion is not processed.

I don't have much to add to that, which such a response I rather not have you contributing indeed.

Thanks 👍

**Comment by DJF3** [comment]
> > wow ...
> > That may have been my last report trying to make the lifes of other/new users easier. (or contribute in any other way)
> 
> I feel sorry for you a bit that is the way you think you should respond to the fact your suggestion is not processed.
> 
> I don't have much to add to that, which such a response I rather not have you contributing indeed.
> 
> Thanks 👍

Sorry Frenck, I was taken off-guard by the "**_Really, we don't care._**" remark. 

I'm quite new to the Home Assistant community and hearing "we don't care" when I'm only trying to help sounded very unfriendly? Or was that because of my submission?

You do understand that I'm only trying to help here, right? (and trying to understand the reasoning for (not) documenting things so I know what to submit and what not)

And maybe it would have sounded very different if you told me this in person. Sometimes I write something that with a grin and laugh sounds totally different than with text only. With text it's up to the readers interpretation. 

Enjoy your evening!
DJ

**Comment by frenck** [comment]
> You do understand that I'm only trying to help here, right?

Yes, but you also should understand that we don't care about unrelated software causing issues. The browser you are using is your choice. That browser has a bug, which we have reported and has been acknowledged by Firefox. There are many more browser bugs.

That said, this is not the issue tracker or documentation for browser X.
