### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by samuelcanadi** [hassio-addons/addon-vscode#356]
# Problem/Motivation

Addon uses more and more memory over time. About 1GB per week. Home Assistant OS Freezes if Addon isn't restartet every few days.

## Expected behavior

Addon should not use more than a few 100 MB of RAM at any given time.

## Actual behavior

Addon uses more and more memory over time. About 1GB per week. Home Assistant OS Freezes if Addon isn't restartet every few days.

## Steps to reproduce

Just let the addon run for a few days.

**Comment by tapd** [comment]
I have noticed a similar thing but relating to CPU usage & temperature. I'm running core-2021.12.0 & supervisor-2021.12.1 on Debian 11(bullseye). The change in CPU usage happens as soon as the addon starts and gets gradually worse when I modify anything, especially when I navigate away from the WebUI and go back to it. I have attached some screenshots of the usage & temp changes over 8 minutes of it running. What else can I provide to assist in identifying the issue
![VSC_AddOn1](https://user-images.githubusercontent.com/2671841/146156979-dddebaf5-2a74-4379-a616-b735611b010c.PNG)
![VSC_AddOn2](https://user-images.githubusercontent.com/2671841/146156984-fd685fe7-a1c2-49d3-9dc0-50decd6d3871.PNG)
![VSC_AddOn3](https://user-images.githubusercontent.com/2671841/146156989-865e4927-505f-4af6-8e1f-d2b297992a4e.PNG)
![VSC_CPU_TEMP1](https://user-images.githubusercontent.com/2671841/146157013-215af17f-f924-456c-8a59-4858b20f73b2.PNG)
![VSC_CPU_TEMP2](https://user-images.githubusercontent.com/2671841/146157018-8b85f7fd-3d51-4e04-99ef-2426d9f5e4e0.PNG)
![VSC_CPU_TEMP3](https://user-images.githubusercontent.com/2671841/146157023-f079cf91-8eae-4262-a9eb-a50fb062c877.PNG)
![VSC_CPU_TEMP4](https://user-images.githubusercontent.com/2671841/146157029-2212fac4-3ded-4279-9126-5c324c6bd3f1.PNG)
![VSC_CPU_TEMP5](https://user-images.githubusercontent.com/2671841/146157032-24c9183f-dc89-45cf-81bf-c5fac0998bb1.PNG)
![VSC_CPU_TEMP6](https://user-images.githubusercontent.com/2671841/146157035-614bce06-df8f-441f-a488-48cf4beea7fd.PNG)
?
