### ISSUE TITLE
Invalid warning "Property event is not allowed." (KNX)

### ISSUE THREAD

**Issue by StephanSchuster** [hassio-addons/addon-vscode#357]
# Problem/Motivation

> Studio Code Server 3.7.0 on HA 2021.12.1 shows invalid warning for KNX `event` property:
> https://www.home-assistant.io/integrations/knx/#events
>
> Config verification succeeds.
> KNX event functionality works.
> Therefore I guess the warning is just wrong.

## Expected behavior

> No warning

## Actual behavior

> Studio Code Server underlines `event` and says: "Property event is not allowed."

## Steps to reproduce

> Add YAML file with content:
```
knx:
  event:
    - address:
        - "0/1/*"
```

## Proposed changes

> No idea.

**Comment by derandiunddasbo** [comment]
This is already in progress:

https://github.com/keesschollaart81/vscode-home-assistant/pull/1780

**Comment by frenck** [comment]
This is not an add-on issue
