### ISSUE TITLE
High CPU and Disk Usage when I load the VSCode page

### ISSUE THREAD

**Issue by simpat1zq** [hassio-addons/addon-vscode#37]
# Problem/Motivation

It appears to happen the second or third time I load the page. The first time, the CPU/Disk spikes for about 5 seconds, and then the second or third time, it goes to 100% usage, and like 80+MB/s on the disk, which is probably max. The CPU spikes to 100 in a few seconds. But the disk takes a couple minutes. It gets to the point where I can't even log into the desktop or connect to anything else on the system. Even HA becomes unresponsive. Sometimes it corrects itself after about an hour. Other times I have to hard reboot the VM(Linux Mint, latest version). HA is .92.2

This started happening on my old HA, so I built a completely new one, and I don't think it happened when I didn't have many devices loaded, but I didn't really test it that thoroughly. And I was only able to get to the logs once to see. The other times, the issues happen, and I can't access anything, and have to hard reboot, and I think HA is wiping the logs when it starts back up. The one time I was able to see the logs, I didn't copy the whole thing, so all I have is this line:

[aiohttp.server] Error handling request

There was a bunch more stuff after that. 

I googled that error, and people were saying that it happens when you are trying to access https when HA is running http  or the other way around. 

I'm only doing http, and on the plugin as well. 

Does anyone have any idea what might be causing this? I can't access any troubleshooting info when the problem happens so it's kind of tough to figure it out for me. 

Thanks in advance.

**Comment by toporovskii** [comment]
Hi, 

I had absolutely same issue. 
Looks like it was caused by low available memory. 
After adding more RAM to my virtual machine running hassio problems gone.

**Comment by simpat1zq** [comment]
I forgot to update here, but I move my HA install off the VM onto a proper dedicated desktop. It runs SOOOO much better and the vs code issue is gone.

**Comment by frenck** [comment]
Thanks for letting me know! Great it worked out 👍
