### ISSUE TITLE
Incorrect yaml parsing with Home Assistant VSCode extension

### ISSUE THREAD

**Issue by tomlut** [hassio-addons/addon-vscode#376]
# Problem/Motivation

Version 4.1.0 seems to have something wrong with the Home Assistant YAML parser. Getting a lot off errors like this:

![Untitled](https://user-images.githubusercontent.com/10679300/149713153-57acd5cc-bc31-49b9-85b8-358e9090a300.png)

The previous version and desktop version (via SAMBA share) do not have this issue.

Seems to only occur for !include files that contain lists, files that contain dictionaries are ok.

```
 Add-on version: 4.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2021.12.9
 Home Assistant Supervisor: 2021.12.2
```

## Expected behavior

YAML to be parsed correctly

## Actual behavior

False positive errors.

## Steps to reproduce

Open an `!include` file that contains a list with the addon.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tomlut** [comment]
Actually, some lists are ok:

![Untitled](https://user-images.githubusercontent.com/10679300/149714492-5cdd256f-1c95-4a54-8785-d4618eb7447d.png)

**!include files with the issue I've found:**

binary_sensors.yaml
lights.yaml
sensors.yaml
switches.yaml
zones.yaml

**Files that are ok:**

automations.yaml
cameras.yaml
media_players.yaml
notifications.yaml
rest_sensors.yaml
scenes.yaml
And all files that contain dictionaries.

**Comment by Hamudulu** [comment]
Same here after update Studio Code to 4.1...

**Comment by gabrieledaltoe** [comment]
I also confirm with my installation:  

binary_sensors.yaml
lights.yaml
sensors.yaml
switches.yaml
zones.yaml

With Studio Code Server 4.1

**Comment by stefanroelofs** [comment]
Same here.

![image](https://user-images.githubusercontent.com/37924749/149773518-9a69ae6b-cfe2-4704-b41e-d549972f9d10.png)

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with the VSCode extension.
Upstream issue here: <https://github.com/keesschollaart81/vscode-home-assistant/issues/1866>
