### ISSUE TITLE
Property not allowed in sensor file

### ISSUE THREAD

**Issue by snp88** [hassio-addons/addon-vscode#379]
# Problem

Each sensor show as error with message like on screenshot

![271982882_5084069398292146_5408439600394866463_n](https://user-images.githubusercontent.com/46537540/149953221-196813e5-3603-4014-849b-7b33282944e2.jpg)
## Expected behavior
no red error when the sensor is correctly configured 

## Actual behavior
each sensor have red error indication

## Steps to reproduce
check sensor file

**Comment by snp88** [comment]
all sensor from screenshot are correctly configured and working without any issue;)

**Comment by frenck** [comment]
This is not an add-on issue.

https://github.com/keesschollaart81/vscode-home-assistant/issues/1866
