### ISSUE TITLE
VS Code seems to cause HA crash since HAOS 7.2 update

### ISSUE THREAD

**Issue by bfish2** [hassio-addons/addon-vscode#383]
# Problem/Motivation

>This morning I updated HAOS to 7.2.  Today I decided to split my configuration.yaml into separate files, so I made extensive use of Studio Code Server for about an hour and a half.

## Expected behavior

> What I expected was business as usual.

## Actual behavior

> What happened was after this work, my HA instance kept crashing.  I had to hard reboot the RPi4 to get it back repeatedly and it would shortly crash again.  Prior to reboot, server (IP ping) remained up, but I couldn't navigate within HA.  

## Steps to reproduce
Initially I thought my external SSD might have been corrupted so I reloaded an HA backup via SD card but got same results.  Ultimately, I disabled Studio Code Server on the SD card and it seemed to stabilize.  I reloaded via the external SSD, disabled Studio Code Server and it has been stable now.

Here are all the logs I have on new instance:
22-01-24 15:05:56 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon core_samba
22-01-24 15:05:56 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-01-24 15:05:56 WARNING (SyncWorker_4) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-01-24 15:05:57 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-samba with version 9.5.1
22-01-24 15:05:57 INFO (MainThread) [supervisor.addons] Detect new Add-on after restore core_samba
22-01-24 15:05:57 INFO (MainThread) [supervisor.addons.addon] Restore config for addon a0d7b954_nodered
22-01-24 15:05:57 INFO (MainThread) [supervisor.addons.addon] Restore/Install of image for addon a0d7b954_nodered
22-01-24 15:05:57 INFO (SyncWorker_4) [supervisor.docker.interface] Downloading docker image ghcr.io/hassio-addons/node-red/aarch64 with tag 10.3.4.
22-01-24 15:05:58 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/default/info access from core_samba
22-01-24 15:06:33 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon a0d7b954_nodered
22-01-24 15:06:33 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-01-24 15:06:33 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-01-24 15:06:33 WARNING (SyncWorker_2) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-01-24 15:06:33 WARNING (SyncWorker_2) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-01-24 15:06:34 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/node-red/aarch64 with version 10.3.4
22-01-24 15:06:34 INFO (MainThread) [supervisor.addons] Detect new Add-on after restore a0d7b954_nodered
22-01-24 15:06:35 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-01-24 15:06:35 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-01-24 15:06:39 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-01-24 15:06:39 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-01-24 15:07:07 INFO (MainThread) [supervisor.addons.addon] Restore config for addon a0d7b954_vscode
22-01-24 15:07:07 INFO (MainThread) [supervisor.addons.addon] Restore/Install of image for addon a0d7b954_vscode
22-01-24 15:07:07 INFO (SyncWorker_2) [supervisor.docker.interface] Downloading docker image ghcr.io/hassio-addons/vscode/aarch64 with tag 4.1.0.
22-01-24 15:08:41 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon a0d7b954_vscode
22-01-24 15:08:51 INFO (MainThread) [supervisor.addons.addon] Finished restore for add-on a0d7b954_vscode
22-01-24 15:08:51 INFO (MainThread) [supervisor.addons] Detect new Add-on after restore a0d7b954_vscode
22-01-24 15:08:51 INFO (MainThread) [supervisor.addons.addon] Restore config for addon core_ssh
22-01-24 15:08:51 INFO (MainThread) [supervisor.addons.addon] Restore/Install of image for addon core_ssh
22-01-24 15:08:51 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-ssh with tag 9.3.0.
22-01-24 15:09:09 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon core_ssh
22-01-24 15:09:10 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-ssh with version 9.3.0
22-01-24 15:09:10 INFO (MainThread) [supervisor.addons] Detect new Add-on after restore core_ssh
22-01-24 15:09:10 INFO (MainThread) [supervisor.addons.addon] Restore config for addon cebe7a76_hassio_google_drive_backup
22-01-24 15:09:10 INFO (MainThread) [supervisor.addons.addon] Restore/Install of image for addon cebe7a76_hassio_google_drive_backup
22-01-24 15:09:10 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image sabeechen/hassio-google-drive-backup-aarch64 with tag 0.105.2.
22-01-24 15:09:29 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon cebe7a76_hassio_google_drive_backup
22-01-24 15:09:30 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on sabeechen/hassio-google-drive-backup-aarch64 with version 0.105.2
22-01-24 15:09:31 INFO (MainThread) [supervisor.addons] Detect new Add-on after restore cebe7a76_hassio_google_drive_backup
22-01-24 15:09:31 INFO (MainThread) [supervisor.addons.addon] Restore config for addon a0d7b954_glances
22-01-24 15:09:31 INFO (MainThread) [supervisor.addons.addon] Restore/Install of image for addon a0d7b954_glances
22-01-24 15:09:31 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image ghcr.io/hassio-addons/glances/aarch64 with tag 0.14.2.
22-01-24 15:09:33 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup
22-01-24 15:09:33 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-01-24 15:09:33 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-01-24 15:09:33 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
22-01-24 15:09:33 INFO (MainThread) [supervisor.api.middleware.security] /backups/ff1380a4/info access from cebe7a76_hassio_google_drive_backup
22-01-24 15:09:41 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon a0d7b954_glances
22-01-24 15:09:41 INFO (MainThread) [supervisor.addons.addon] Finished restore for add-on a0d7b954_glances
22-01-24 15:09:41 INFO (MainThread) [supervisor.addons] Detect new Add-on after restore a0d7b954_glances
22-01-24 15:09:41 INFO (MainThread) [supervisor.addons.addon] Restore config for addon core_configurator
22-01-24 15:09:41 INFO (MainThread) [supervisor.addons.addon] Restore/Install of image for addon core_configurator
22-01-24 15:09:41 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-configurator with tag 5.3.3.
22-01-24 15:09:59 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon core_configurator
22-01-24 15:09:59 INFO (MainThread) [supervisor.addons.addon] Finished restore for add-on core_configurator
22-01-24 15:09:59 INFO (MainThread) [supervisor.addons] Detect new Add-on after restore core_configurator
22-01-24 15:11:00 INFO (MainThread) [supervisor.addons.addon] Restore config for addon core_mariadb
22-01-24 15:11:00 INFO (MainThread) [supervisor.addons.addon] Restore/Install of image for addon core_mariadb
22-01-24 15:11:00 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-mariadb with tag 2.4.0.
22-01-24 15:11:25 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon core_mariadb
22-01-24 15:11:37 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mariadb with version 2.4.0
22-01-24 15:11:37 INFO (MainThread) [supervisor.addons] Detect new Add-on after restore core_mariadb
22-01-24 15:11:37 INFO (MainThread) [supervisor.addons.addon] Restore config for addon core_mosquitto
22-01-24 15:11:37 INFO (MainThread) [supervisor.addons.addon] Restore/Install of image for addon core_mosquitto
22-01-24 15:11:37 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-mosquitto with tag 6.0.1.
22-01-24 15:11:42 INFO (MainThread) [supervisor.services.modules.mysql] Set core_mariadb as service provider for MySQL
22-01-24 15:11:47 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon core_mosquitto
22-01-24 15:11:49 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 6.0.1
22-01-24 15:11:49 INFO (MainThread) [supervisor.addons] Detect new Add-on after restore core_mosquitto
22-01-24 15:11:53 INFO (MainThread) [supervisor.discovery] Sending discovery to Home Assistant mqtt from core_mosquitto
22-01-24 15:11:53 INFO (MainThread) [supervisor.discovery] Discovery b6677ac729d14e3ea559f0bb0979e2f1 message ignore
22-01-24 15:11:53 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
22-01-24 15:11:54 INFO (MainThread) [supervisor.addons.addon] Restore config for addon core_zwave_js
22-01-24 15:11:54 INFO (MainThread) [supervisor.addons.addon] Restore/Install of image for addon core_zwave_js
22-01-24 15:11:54 INFO (SyncWorker_4) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-zwave_js with tag 0.1.52.
22-01-24 15:12:19 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon core_zwave_js
22-01-24 15:12:22 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-zwave_js with version 0.1.52
22-01-24 15:12:22 INFO (MainThread) [supervisor.addons] Detect new Add-on after restore core_zwave_js
22-01-24 15:12:22 INFO (MainThread) [supervisor.backups.manager] Restore ff1380a4 wait until homeassistant ready
22-01-24 15:12:23 INFO (SyncWorker_2) [supervisor.docker.interface] Starting homeassistant
22-01-24 15:12:23 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-01-24 15:12:26 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_zwave_js
22-01-24 15:12:27 INFO (MainThread) [supervisor.discovery] Sending discovery to Home Assistant zwave_js from core_zwave_js
22-01-24 15:12:27 INFO (MainThread) [supervisor.discovery] Discovery bf216e502ebf4e46a4c19a26556338e3 message ignore
22-01-24 15:12:37 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.FREEZE
22-01-24 15:12:37 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-01-24 15:12:38 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-01-24 15:17:15 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-01-24 15:17:15 INFO (MainThread) [supervisor.backups.manager] Full-Restore ff1380a4 done
22-01-24 15:17:16 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-01-24 15:17:16 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-01-24 15:17:16 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-01-24 15:19:03 INFO (SyncWorker_0) [supervisor.docker.interface] Removing image ghcr.io/hassio-addons/vscode/aarch64 with latest and 4.1.0
22-01-24 15:19:09 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/a0d7b954_vscode
22-01-24 15:19:11 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for a0d7b954_vscode
22-01-24 15:19:11 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_vscode' successfully removed
22-01-24 15:19:53 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for core_configurator
22-01-24 15:20:00 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-configurator with version 5.3.3

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by jmoflhrc** [comment]
I've been having the same exact issue, this also happened prior to the HAOS 7.2 upgrade.  My 4GB Pi4 with SSD would become unresponsive but still pingable as you are seeing @bfish2 

One other data point to note is while I am just sitting with the config file open within VSCode it's using quite a bit of CPU.  My friend with the same exact setup is unable to replicated this issue which is odd.

Name	Status	CPU%	MEM	RSS	IOR/s	IOW/s	RX/s	TX/s	Command
addon_a0d7b954_vscode	running	99.3	1.15G	971M	0b	0b	1Kb	544b	["/init"]
