### ISSUE TITLE
Problem with new update

### ISSUE THREAD

**Issue by schumi2309** [hassio-addons/addon-vscode#384]
since the update in home assistant, I have errors that have been added to my yaml files. except, before this update, there was no error.
ex:
- platform: meteoalarm   Property platform is not allowed.
  country: "belgium"        Property country is not allowed.
  province: "liege"            Property province is not allowed.

What is going on ?
What should be done to remove these errors?

Thank you.

**Comment by frenck** [comment]
Incorrect issue tracker, see upstream issue: <https://github.com/keesschollaart81/vscode-home-assistant/issues/1866>

**Comment by schumi2309** [comment]
thanks.
