### ISSUE TITLE
False positive syntax errors on included yaml files 

### ISSUE THREAD

**Issue by rrlevy** [hassio-addons/addon-vscode#386]
After 4.1.0 I'm seeing a lot of false positive errors on my light.yaml and other included files.

![image](https://user-images.githubusercontent.com/14061585/152396988-2014f132-dfb2-42e5-874a-1628d5059db8.png)

I usually include those files on configuration.yaml like this:

```
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
switch: !include switch.yaml
light: !include light.yaml
```

However, after the 4.1.0 I'm seeing red lines with the syntax error "property platform is not allowed" in all lines where I add a new entity with the "platform" property.

It is still working in Home Assistant, it's only VSCode that is showing it as an error

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with the VSCode extension for Home Assistant.

**Comment by GaTechThomas** [comment]
Where should we go for issues with the VSCode extension for Home Assistant?

**Comment by sinclairpaul** [comment]
https://github.com/keesschollaart81/vscode-home-assistant
