### ISSUE TITLE
Invalid validation

### ISSUE THREAD

**Issue by koevoetsfjm** [hassio-addons/addon-vscode#387]
# Problem/Motivation
To keep my configuration.yaml clean, i'd like to seperate my sensors and stuff in seperate files.

So, i've created a folder called 'custom' and put the config files for (e.g.) sensors in there.
When configuration gets large I want to split them by platform, (I have platform:mqtt and platform:template sensors)

> Although home assitant likes this setup, VSCode does not.

## Expected behavior
> I'd like to see no validation errors in VSCode.

## Actual behavior
configuration.yaml:
![image](https://user-images.githubusercontent.com/12787382/152675083-aad5055f-e71c-4dfa-b379-ab2cd1e04528.png)
.
/custom/entity-sensor.yaml
![image](https://user-images.githubusercontent.com/12787382/152675016-8afc5df2-7181-4acf-aa42-87b8c07f6cfa.png)

But also Homeassistant:
![image](https://user-images.githubusercontent.com/12787382/152675125-00b857be-ba79-4c7a-bc14-dca9780f79ee.png)

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)
move your sensors to a seperate file using the steps described here:
[Documentation](https://www.home-assistant.io/docs/configuration/splitting_configuration/)

## Proposed changes
I don't know how to fix this.
> Either this is a bug in vscode addon, or the documention for splitting your configuration files confuses me. But since HA likes it, i'm assuming vscode has misconfigured intellisense.

**Comment by frenck** [comment]
Please check previous closed issues.  This is not an add-on issue.
