### ISSUE TITLE
Error shown in the Visual Studio Code editor

### ISSUE THREAD

**Issue by bouwew** [hassio-addons/addon-vscode#39]
Since the update to 0.5.3, I see this error pop up when I open the editor:

![image](https://user-images.githubusercontent.com/11290930/58876286-dd41b780-86cd-11e9-81ec-11afeb0f9a8f.png)

The editor seems to work normally, I can edit and save files.

My config:
```
{
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "packages": [],
  "init_commands": [],
  "disable_telemetry": false
}
```

**Comment by frenck** [comment]
Known issue.

Fix is pending/under review upstream:
keesschollaart81/vscode-home-assistant#44

**Comment by bouwew** [comment]
Clear, thanks!

**Comment by frenck** [comment]
This issue has been fixed already and can be closed.
