### ISSUE TITLE
No Update on Version 4.2.0

### ISSUE THREAD

**Issue by GerdRuetten** [hassio-addons/addon-vscode#391]
# Problem/Motivation

I have install Version 4.1.0 and Autoupdate active.
If i open Studio Code Server it shows me in a small splash window, that Version 4.2.0 is available.

## Expected behavior

Autoupdate on the latest Version.

## Actual behavior

No update on the latest version.

## Proposed changes

My Systemenviroment:

## System Health

version | core-2022.2.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.22.0
Stage | running
Available Repositories | 1053
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 12. März 2022, 01:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-west-2-4.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 118.3 GB
disk_used | 14.1 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (4.1.0), SSH & Web Terminal (10.0.2), Terminal & SSH (9.3.0), FTP (4.4.1), RPC Shutdown (2.2), Samba Backup (5.0.0), InfluxDB (4.3.0), Grafana (7.4.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 6
views | 9
mode | storage

</details>

**Comment by sinclairpaul** [comment]
We can't auto update as it's a container, it appears that the update notifications (which is disabled) has an issue upstream.
