### ISSUE TITLE
not available in hassio

### ISSUE THREAD

**Issue by mclaudiopt** [hassio-addons/addon-vscode#40]
Hello
i have Hassio but cannot install

![image](https://user-images.githubusercontent.com/48178294/59088922-ca62f900-8900-11e9-8203-0b739c8cd36a.png)
is there anyway to install this addon?
thanks

**Comment by frenck** [comment]
This add-on is only available for the AMD64 architecture.
Please consult the add-on documentation before sending in issues. Thanks.
