### ISSUE TITLE
Property xxxx is not allowed errors

### ISSUE THREAD

**Issue by verstrepeng** [hassio-addons/addon-vscode#400]
# Problem/Motivation

A lot of errors on the included sensor.yaml and binary_sensor.yaml since upgrade >4.0

## Expected behavior

Syntax is correct and working, so shouldn't show the error

## Actual behavior

Property XXXXX is not allowed.
![image](https://user-images.githubusercontent.com/16412175/158073779-7e2dacea-902e-42e7-baa7-3a2cee77214b.png)

## Steps to reproduce

Create a sensor.yaml file and include it in configuartion.yaml

## Proposed changes

It was working on previous versions

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with the VSCode extension. It also have been reported many more times, if you searched the issue tracker it would have saved you the time to create an issue 😉 

../Frenck

**Comment by verstrepeng** [comment]
> This is not an add-on issue, but an issue with the VSCode extension. It also have been reported many more times, if you searched the issue tracker it would have saved you the time to create an issue 😉
> 
> ../Frenck

OK, so how to solve it ?
I used Google without luck ;-)
