### ISSUE TITLE
Error seen when typing entity names instead of dropdown list to choose

### ISSUE THREAD

**Issue by cbhiii** [hassio-addons/addon-vscode#416]
# Problem/Motivation

> When partially typing a list of entities VS is no longer displaying the dropdown to make a selection. Instead I see errors referenced in the bottom right part of window (see attached screenshot).

## Expected behavior

> When partially typing a list of entities I expect a dropdown to appear and then I can arrow up/down to make a selection.

## Actual behavior

> No dropdown only an error seen.

## Steps to reproduce

> Start partially typing an entity name where expected ( e.g. light. should bring up a list of light entities)

![Pasted Graphic 1](https://user-images.githubusercontent.com/10853381/160418232-7a3477da-19bf-450e-8810-b15dbb5cf76a.png)

**Comment by cbhiii** [comment]
Here are some images of the error boxes expanded.

![Unhandled promise reiections a deprecated](https://user-images.githubusercontent.com/10853381/160422659-8a6ad78d-f4d3-48f9-8c68-974dfd3cbd0f.png)

----------------------

![® (node3393)  DEP0018  DeprecationWarning Unhandled promise -](https://user-images.githubusercontent.com/10853381/160422682-6f8e99b7-3dc8-4984-90f9-d71fd852d310.png)

**Comment by sinclairpaul** [comment]
The VSCode extension repo is at https://github.com/keesschollaart81/vscode-home-assistant

Please log your issues there
