### ISSUE TITLE
4.2.0 does not work properly due to js error

### ISSUE THREAD

**Issue by vekexasia** [hassio-addons/addon-vscode#417]
# Problem/Motivation

Apparently there is an error in js preventing the UI to show up.

## Expected behavior

The UI should properly show up

## Actual behavior

It does not

## Steps to reproduce

I just upgraded to 4.2.0. This is what i see in console

![image](https://user-images.githubusercontent.com/200523/160574380-9fc1454f-f6cd-4a53-9c96-e128c9674b0e.png)

**Comment by lesu1** [comment]
I had the same issue after the VSCode update.
Try to uninstall VSCode and re-install it back.
