### ISSUE TITLE
Entity_id autofill doesn't work and throws error

### ISSUE THREAD

**Issue by TheFes** [hassio-addons/addon-vscode#419]
# Problem/Motivation

When entering an entity_id it normally gives a list of options based on your input. However now it throws some errors

Screenshot:
![image](https://user-images.githubusercontent.com/28803438/161079378-5e431c39-b650-4c49-bbf3-089f522bc161.png)

## Expected behavior

A list with entity_ids which match the input already provided

## Actual behavior

The errors shown above

## Steps to reproduce

enter `entity_id:  ` and start providing and entity_id

## Proposed changes

N/A

**Comment by MikeGuest** [comment]
I also have this. Running version 4.2.0 of the add-in.

Not sure how to revert.

**Comment by Stuke00** [comment]
Same issue for me

**Comment by tconnz** [comment]
Same for me. 
I tried removing and re-adding Studio Code Server but still get the same errors as depicted/posted above by OP (except my node:###) is different.
I'm running HA via HTTP not HTTPS, just to add another data point.

**Comment by guennikasse** [comment]
Same for me

**Comment by frenck** [comment]
I wonder which Home Assistant versions you guys run?

**Comment by Barma-lej** [comment]
Same for me.
## System Health

version | core-2022.4.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.0-13-amd64
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.24.5
Stage | running
Available Repositories | 1097
Downloaded Repositories | 18

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.14
disk_total | 61.8 GB
disk_used | 22.4 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.14.0), Samba share (9.5.1), Mosquitto broker (6.0.1), Studio Code Server (4.2.0), FTP (4.5.0), ESPHome (2022.3.1), TasmoAdmin (0.17.0), SQLite Web (3.3.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 14
views | 16
mode | storage

</details>

**Comment by TheFes** [comment]
## System Health

version | core-2022.4.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.34
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4567
Installed Version | 1.24.5
Stage | running
Available Repositories | 1099
Downloaded Repositories | 33

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.0.rc2
-- | --
update_channel | beta
supervisor_version | supervisor-2022.04.2
docker_version | 20.10.12
disk_total | 125.3 GB
disk_used | 43.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.106.2), Samba share (9.5.1), Studio Code Server (4.2.0), Terminal & SSH (9.3.0), MariaDB (2.4.0), RPC Shutdown (2.2), deCONZ (6.12.0), ESPHome (2022.3.1), phpMyAdmin (0.7.1), Mosquitto broker (6.0.1), Nginx Proxy Manager (0.11.0), VLC (0.1.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 14
views | 13
mode | yaml

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by michelsup** [comment]
You can reopen this issue. No errors anywhere but still doesn't work.

**Comment by frenck** [comment]
This is not an issue of the add-on.

**Comment by michelsup** [comment]
Ok, thank you for the precision.
