### ISSUE TITLE
Unable to Copy or Cut text

### ISSUE THREAD

**Issue by jdenver13** [hassio-addons/addon-vscode#42]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> Using cmd +c or cmd+x is no longer working

## Actual behavior

> I can highlight text but after trying to copy or cut and then paste, the old contents in the clipboard is pasted. I can copy text in other areas of home assistant and paste that text in vscode but not text I try to copy within vscode. This use to work for me, I have uninstalled vscode and reinstalled it but its not solved the issue. Im running 0.94 but this problem has been around since 0.92

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by jdenver13** [comment]
Ive worked out this issue only happens in Safari. Chrome and Firefox are ok

**Comment by CurrentThread** [comment]
Known issue with code-server, https://github.com/cdr/code-server/issues/569

**Comment by frenck** [comment]
The workaround is to allow the page access to the clipboard in your browser.
