### ISSUE TITLE
Black screen with ingress through reverse proxy and custom domain

### ISSUE THREAD

**Issue by eavanvalkenburg** [hassio-addons/addon-vscode#43]
# Problem/Motivation

> I still have the same issue that was closed here (#25) when running HA 96.5, Hassio Supervisor 170. I get a black screen when opening the VSCode addin from the side bar with ingress, when enabling a port and going to that it does work (after logging in).

## Expected behavior

> Ingress link in sidebar shows VSCode interface

## Actual behavior

> Black screen

## Steps to reproduce

> Running on a subdomain (ha.domain.com) that is locally resolving to a local IP and globally through DNS with NGINX catching all traffic and routing different subdomains differently. Hassio installed on Ubuntu 18.04, running HA latest and a couple of add-ons. Configurator ingress does work, so seems to be VSCode add-on related.

**Comment by frenck** [comment]
No logs, no config examples. There is nothing I can do with this issue.

**Comment by eavanvalkenburg** [comment]
Sorry, log:

> -----------------------------------------------------------
>  Hass.io Add-on: Visual Studio Code
>  Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
> -----------------------------------------------------------
>  Add-on version: 0.6.1
>  You are running the latest version of this add-on.
>  System: Ubuntu 18.04.2 LTS  (amd64 / qemux86-64)
>  Home Assistant version: 0.96.5
>  Supervisor version: 170
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> [cont-init.d] 00-banner.sh: exited 0.
> [cont-init.d] 01-log-level.sh: executing... 
> [cont-init.d] 01-log-level.sh: exited 0.
> [cont-init.d] code-server.sh: executing... 
> [cont-init.d] code-server.sh: exited 0.
> [cont-init.d] nginx.sh: executing... 
> [cont-init.d] nginx.sh: exited 0.
> [cont-init.d] user.sh: executing... 
> [cont-init.d] user.sh: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [16:11:14] INFO: Starting the code server...
> (node:422) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> INFO  code-server v1.1156-vsc1.33.1
> INFO  Additional documentation: http://github.com/cdr/code-server
> INFO  Initializing {"data-dir":"/data/vscode","extensions-dir":"/data/vscode/extensions","working-dir":"/config","log-dir":"/root/.cache/code-server/logs/20190730141115206"}
> INFO  Starting webserver... {"host":"127.0.0.1","port":"8443"}
> WARN  No certificate specified. This could be insecure.
> WARN  Documentation on securing your setup: https://github.com/cdr/code-server/blob/master/doc/security/ssl.md
> WARN   
> WARN  Launched without authentication.
> INFO   
> INFO  Started (click the link below to open):
> INFO  http://localhost:8443/
> INFO   
> INFO  Starting shared process [1/5]...
> WARN  stderr {"data":"(node:473) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
> [16:11:15] INFO: Starting NGinx...
> INFO  Connected to shared process
> [30/Jul/2019:16:11:18 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3837.0 Safari/537.36 Edg/77.0.211.3)
> [30/Jul/2019:16:11:18 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET /ide.1.5b173b.js HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3837.0 Safari/537.36 Edg/77.0.211.3)
> [30/Jul/2019:16:11:18 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET /ide.main.5b173b.css HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3837.0 Safari/537.36 Edg/77.0.211.3)
> [30/Jul/2019:16:11:18 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET /ide.main.5b173b.js HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3837.0 Safari/537.36 Edg/77.0.211.3)
> [30/Jul/2019:16:11:19 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3837.0 Safari/537.36 Edg/77.0.211.3)
> [30/Jul/2019:16:11:19 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3837.0 Safari/537.36 Edg/77.0.211.3)
> [30/Jul/2019:16:11:19 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3837.0 Safari/537.36 Edg/77.0.211.3)
> [30/Jul/2019:16:11:19 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3837.0 Safari/537.36 Edg/77.0.211.3)
> [30/Jul/2019:16:11:19 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3837.0 Safari/537.36 Edg/77.0.211.3)
> [30/Jul/2019:16:11:20 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3837.0 Safari/537.36 Edg/77.0.211.3)

config:

> {
>   "ssl": true,
>   "certfile": "fullchain1.pem",
>   "keyfile": "privkey1.pem",
>   "packages": [],
>   "init_commands": [],
>   "disable_telemetry": false,
>   "leave_front_door_open": false
> }

and network port set to 8444 and all dials set, so running in protected mode, start on boot, etc.

Hope that helps in figuring out what is happening, let me know what else I can get for you to troubleshoot!

**Comment by eavanvalkenburg** [comment]
@frenck could you have another look at my logs?
