### ISSUE TITLE
"Visual Studio Code is unable to watch for file changes in this large workspace" (error ENOSPC)

### ISSUE THREAD

**Issue by jokerigno** [hassio-addons/addon-vscode#44]
# Problem/Motivation
Hi, when I open a VS session I receive this error message:

![image](https://user-images.githubusercontent.com/23552762/62135754-0b650180-b2e3-11e9-8740-c47e8d4963ca.png)

The link on  instructions button open this page:

https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

So maybe the error can be solved in the container?

<blockquote><img src="https://code.visualstudio.com/opengraphimg/opengraph-docs.png" width="48" align="right"><div><strong><a href="https://code.visualstudio.com/docs/setup/linux">Running Visual Studio Code on Linux</a></strong></div><div>Get Visual Studio Code up and running on Linux.</div></blockquote>

**Comment by frenck** [comment]
Please read the add-on manual before opening issues. Thanks.

**Comment by jokerigno** [comment]
Sorry!

**Comment by frenck** [comment]
No problem m8!
