### ISSUE TITLE
The shorthand notation for logical conditions shows an error

### ISSUE THREAD

**Issue by Plazmin** [hassio-addons/addon-vscode#447]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
![5](https://user-images.githubusercontent.com/62091912/168344377-a45803a1-8639-4eab-b27d-abdeccb8dcbe.png)

**Comment by sinclairpaul** [comment]
Please log the issue with the extension https://github.com/keesschollaart81/vscode-home-assistant
