### ISSUE TITLE
After latest update to 5.0.3 to all files goes into "Source control"

### ISSUE THREAD

**Issue by poudenes** [hassio-addons/addon-vscode#455]
Hi All,

After I updates to 5.0.3 and edit some yams files they not appear into "source control" so I can give them a comment and sync to GitHub.

Its a straightforward problem. 

Cant find any error messages, no popups from VScode etc....

**Comment by frenck** [comment]
I cannot reproduce that issue:

![image](https://user-images.githubusercontent.com/195327/168991476-90ab1507-3fac-4cae-a8a2-f511a6c10fc4.png)

Make sure you have the correct folder open in your workspace? 🤷

**Comment by poudenes** [comment]
I'm working for long time in same folder
I see a green (little clock) icon and then its gone... The file is not showing.

Clear cache, restart VSC didn't help also.

I will remove the VSC Add-On and reboot HA, reinstall it again and see what happen
(i have to config everything again I guess)

**Comment by poudenes** [comment]
Removed VSC Add-on, restart HA, reinstall VSC, config Git/Github and everything is running again.

**Comment by poudenes** [comment]
Its seems that certain files work and some not. Still have the issue... :(

**Comment by poudenes** [comment]
created a new folder, moved all files from this specific folder and pushed it to GitHub. removed this old folder in VSC. 
Now it seems to work again.
