### ISSUE TITLE
Installing .NET SDK for NetDaemon

### ISSUE THREAD

**Issue by josesimoes** [hassio-addons/addon-vscode#456]
# Problem/Motivation

When adding the configuration shown [here](https://netdaemon.xyz/docs/v3/started/development/#24-studio-code-server-addon) I get this error message:

```
E: Unable to locate package dotnet-sdk-6.0
E: Couldn't find any package by glob 'dotnet-sdk-6.0'
E: Couldn't find any package by regex 'dotnet-sdk-6.0'
[22:31:09] FATAL: Failed executing init command: apt-get install -y dotnet-sdk-6.0
[cont-init.d] user.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
```

## Expected behavior

Can't figure out why this is failing. Already reached out to NetDaemon folks without success...

## Actual behavior

> Error installing the .NET SDK as described above.

## Steps to reproduce

> Copy the above config to the add-on and restart it. It will show the described error message.

**Comment by sinclairpaul** [comment]
It's not in the debian package distro, would suggest looking at the instructions for installing:

<https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#debian-11->

**Comment by josesimoes** [comment]
@sinclairpaul I've ended up using the install script from [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script). Thanks for pointing me in the right direction. 😃
