### ISSUE TITLE
Error: metadata: {} - Property metadata is not allowed

### ISSUE THREAD

**Issue by oneseventhree** [hassio-addons/addon-vscode#457]
# Problem/Motivation

VS is showing this error:
<img width="471" alt="Screen Shot 2022-05-22 at 5 43 06 pm" src="https://user-images.githubusercontent.com/15043282/169684453-25c04c22-cfb3-42b7-8c88-de3730b31350.png">

Even though its fine in UI:
<img width="990" alt="Screen Shot 2022-05-22 at 5 45 17 pm" src="https://user-images.githubusercontent.com/15043282/169684503-3df06c5c-0f77-4664-9f05-9e49737b2139.png">

## Expected behavior

No error.

## Actual behavior

Shows error as in first picture

## Steps to reproduce

1. Create a new 'Action' and select 'Activate Scene' in an automation
2. Select the scene in the drop down of 'Entity'
3. Save automation
4. Error now shows in VSCode

## Proposed changes

Remove the error as there is none.

**Comment by frenck** [comment]
This is not an issue with the add-on, but with the Home Assistant VSCode extension. Please report the issue with that project.

**Comment by oneseventhree** [comment]
> Home Assistant VSCode extension

Hi frenck, where would I be able to report that? 
Here?: https://github.com/microsoft/vscode/issues

All google links point back here, thanks

**Comment by frenck** [comment]
<https://marketplace.visualstudio.com/items?itemName=keesschollaart.vscode-home-assistant&ssr=false#overview>

![CleanShot 2022-05-22 at 11 46 12](https://user-images.githubusercontent.com/195327/169689418-ec2b956d-1124-4026-b3c4-cef1d9f1d8c5.png)

<https://github.com/keesschollaart81/vscode-home-assistant/issues>

![CleanShot 2022-05-22 at 11 46 49](https://user-images.githubusercontent.com/195327/169689436-fe9aabc5-2dcc-4adf-b9c2-9d75b36f2406.png)
