### ISSUE TITLE
source control doesn't sync

### ISSUE THREAD

**Issue by r3mcos3** [hassio-addons/addon-vscode#46]
# Problem/Motivation
The source control tab on the vscode addon don't sync with the source control off the vscode program on windows.

## Expected behavior
That source control sync between addon and windows program 

## Actual behavior
They don't sync

## Steps to reproduce

I commit and push changes through the vscode program on windows but it doesn't sync between the addon, i don't know if it is reproduce-able 

for me it doesn't work

![source control](https://user-images.githubusercontent.com/45529818/62521481-08609880-b830-11e9-931c-82f90c6bfa03.JPG)
![2019-08-06 09 44 08 10 10 50 90 370dbeaddb4e](https://user-images.githubusercontent.com/45529818/62521519-1a423b80-b830-11e9-819c-23ab78203578.jpg)
![2019-08-06 09 43 45 10 10 50 90 3b008e869770](https://user-images.githubusercontent.com/45529818/62521520-1c0bff00-b830-11e9-8648-129cb319aa2c.jpg)

**Comment by frenck** [comment]
You are using Samba... Windows & Linux file permissions get f-ed up.
That is not an add-on issue.
