### ISSUE TITLE
Showing error for the valid code : mqtt sensors

### ISSUE THREAD

**Issue by homonto** [hassio-addons/addon-vscode#465]
since HA 2022.6 there is an error in VSC with regards to new mqtt settings:
<img width="517" alt="Screenshot 2022-06-03 at 09 13 19" src="https://user-images.githubusercontent.com/46562447/171816320-7ba21e97-969f-448a-8d54-ed153dc05479.png">
irrespective if I add !include or just define the sensor 

this is issue with VSC as since 2022.6 the mqtt sensors that are manually defined should be in mqtt: section

**Comment by g4sbq** [comment]
There is a similar "error" for mqtt device trackers...

![image](https://user-images.githubusercontent.com/57624938/172185680-ec92fc0d-9759-4fee-8dee-55bc514054fc.png)

**Comment by homonto** [comment]
> There is a similar "error" for mqtt device trackers...
> 
> ![image](https://user-images.githubusercontent.com/57624938/172185680-ec92fc0d-9759-4fee-8dee-55bc514054fc.png)

I solved mine by upgrading vscode ;-)
For some reason I was on 4.x version or so

**Comment by frenck** [comment]
👋  Hi there!

This is not an issue with the add-on, but with the Home Assistant Config Helper VSCode extension. Please report the issue there. If that is fixed, it will also be fixed at the add-on end.

../Frenck
