### ISSUE TITLE
Please install the pillow python package to use this feature. (pip install pillow)

### ISSUE THREAD

**Issue by gsieben** [hassio-addons/addon-vscode#474]
# Problem/Motivation

I use Studio Code Server to program ESPHome Devices. But unfortunately I get a compiler error message the moment I include images or fonts.

e.g.
```
  - file: gfonts://Roboto Mono
    id: my_font
    size: 20
```

or

```
  - file: "images/36/auto.png"
    id: im_auto
    type: TRANSPARENT_BINARY 
```

## Expected behavior

No Error

## Actual behavior

An Error: The error message says: Please install the pillow python package to use this feature. (pip install pillow).

## Steps to reproduce
1. Create an ESPHome device 
2. Edit the device.yaml and add
```
    - file: gfonts://Roboto Mono
        id: my_font
        size: 20
```
3. Try to compile

## Proposed changes

I have not found a way to do this myself.

**Comment by frenck** [comment]
> Please install the pillow python package to use this feature


You can do so yourself, see also the add-on documentation: https://github.com/hassio-addons/addon-vscode/blob/main/vscode/DOCS.md#option-packages

**Comment by gsieben** [comment]
Thanks for the hint. Installing the package "python3-pypillowfight" worked.
