### ISSUE TITLE
Failed to start add-on

### ISSUE THREAD

**Issue by GittyGrubHub85** [hassio-addons/addon-vscode#476]
# Problem/Motivation

> I can't find any search results about an add-on failing to start so I want to create an issue.

## Expected behavior

> Based on the docs, it should start after I installed it.

## Steps to reproduce

I've gone into this error when I press the start button and shows a message that it failed to start add-on https://i.imgur.com/dQ9wCHr.png

Hope someone can fix this thanks.

**Comment by frenck** [comment]
This is not an problem with the add-on, but with your system.

You can try running `ha supervisor repair` from an (web/ssh) terminal to try to resolve it. Otherwise, please report your issue with the Home Assistant Supervisor project.

Thanks 👍 

../Frenck

**Comment by GittyGrubHub85** [comment]
Thanks, but I decide to delete that setup and start again. I went another [video tutorial](https://www.youtube.com/watch?v=oYjOYkdyr38&ab_channel=GEEKrarGuides) that is more recent so it's relevant for me to follow up the setup.
