### ISSUE TITLE
Vscode won't start

### ISSUE THREAD

**Issue by marcelodavanzo** [hassio-addons/addon-vscode#48]
# Problem/Motivation
Vscode won't run and gives the following errors:

```
19-08-25 22:30:13 INFO (SyncWorker_0) [hassio.docker.interface] Stop addon_a0d7b954_vscode application
19-08-25 22:30:15 INFO (SyncWorker_0) [hassio.docker.interface] Clean addon_a0d7b954_vscode application
19-08-25 22:30:20 ERROR (SyncWorker_4) [hassio.docker] Can't start addon_a0d7b954_vscode: 404 Client Error: Not Found ("linux runtime spec devices: error gathering device information while adding custom device "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1996743-if00": lstat /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1996743-if00: no such file or directory")
```

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce
Synology NAS with a Conbee II stick added via deCONZ.
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Please provide system information.

**Comment by marcelodavanzo** [comment]
Synology NAS DS218+ running Hass.io in Docker.

**Comment by frenck** [comment]
I'm sorry to hear that you are having issues. However, you are running on an unsupported platform.
The error you get, isn't related to the add-on, but to Hassio (or some of the ecosystem around it).
From the add-on perspective, there is really nothing I can do... Sorry m8.

**Comment by marcelodavanzo** [comment]
Thanks, you're right. After unplugging the problematic USB device vscode starts just fine. I've opened a similar issue here https://github.com/home-assistant/hassio/issues/1265 thanks for the heads up.
