### ISSUE TITLE
ESPHome integration is missing pillow package

### ISSUE THREAD

**Issue by mhaas** [hassio-addons/addon-vscode#489]
# Problem/Motivation

When I edit my esphome config via this addon and I add a font, I get an error when clicking the "OTA" button in VSC:

```
font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 20
```

The error is:

```
INFO Reading configuration esphome/esp32-3.yaml...
WARNING GPIO2 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO0 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

font: [source esphome/esp32-3.yaml:18]
  
  Please install the pillow python package to use this feature. (pip install pillow).
  - file: gfonts://Roboto
    id: roboto
    size: 20

 *  The terminal process "/usr/bin/zsh '-c', 'esphome run esphome/esp32-3.yaml --device OTA'" terminated with exit code: 2. 
 *  Terminal will be reused by tasks, press any key to close it. 
 * ```

## Expected behavior

Upload should work.

## Actual behavior

Error observed:

```
INFO Reading configuration esphome/esp32-3.yaml...
WARNING GPIO2 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO0 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

font: [source esphome/esp32-3.yaml:18]
  
  Please install the pillow python package to use this feature. (pip install pillow).
  - file: gfonts://Roboto
    id: roboto
    size: 20

 *  The terminal process "/usr/bin/zsh '-c', 'esphome run esphome/esp32-3.yaml --device OTA'" terminated with exit code: 2. 
 *  Terminal will be reused by tasks, press any key to close it. 
 ```

## Steps to reproduce

* Add font directive to esphome config (see above)
* Click "ota upload" button in VSC (bottom left corner)
* Observe error


## Proposed changes

Install pillow package.

**Comment by frenck** [comment]
Not stale bot... I've put out the question to the ESPHome project.
