### ISSUE TITLE
Black screen with ingress through reverse proxy and custom domain

### ISSUE THREAD

**Issue by eavanvalkenburg** [hassio-addons/addon-vscode#49]
# Problem/Motivation

> I still have the same issue that was closed here (#25) when running HA 0.97.2, Hassio Supervisor 184 and VSCode addin 0.6.5. I get a black screen when opening the VSCode addin from the side bar with ingress, when enabling a port and going to that it does work (after logging in).

## Expected behavior

> Ingress link in sidebar shows VSCode interface

## Actual behavior

> Black screen

## Steps to reproduce

> Running on a subdomain (ha.domain.com) that is locally resolving to a local IP and globally through DNS with NGINX catching all traffic and routing different subdomains differently. Hassio installed on Ubuntu 18.04, running HA latest and a couple of add-ons. Configurator and Pi-hole ingress do work, so seems to be VSCode add-on related.

### Config
```
{
"ssl": true,
"certfile": "fullchain1.pem",
"keyfile": "privkey1.pem",
"packages": [],
"init_commands": [],
"disable_telemetry": false,
"leave_front_door_open": false
}
```

### VSCode Add-in Log
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 0.6.5
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.3 LTS  (amd64 / qemux86-64)
 Home Assistant version: 0.97.2
 Supervisor version: 184
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:11:21] INFO: Starting the code server...
(node:435) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
INFO  code-server v1.1156-vsc1.33.1
INFO  Additional documentation: http://github.com/cdr/code-server
INFO  Initializing {"data-dir":"/data/vscode","extensions-dir":"/data/vscode/extensions","working-dir":"/config","log-dir":"/root/.cache/code-server/logs/20190826151122399"}
INFO  Starting webserver... {"host":"127.0.0.1","port":"8443"}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://github.com/cdr/code-server/blob/master/doc/security/ssl.md
WARN   
WARN  Launched without authentication.
INFO   
INFO  Started (click the link below to open):
INFO  http://localhost:8443/
INFO   
INFO  Starting shared process [1/5]...
[17:11:22] INFO: Starting NGinx...
WARN  stderr {"data":"(node:482) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
INFO  Connected to shared process
[26/Aug/2019:17:11:29 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3879.0 Safari/537.36 Edg/78.0.249.1)
[26/Aug/2019:17:11:29 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET /ide.1.5b173b.js HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3879.0 Safari/537.36 Edg/78.0.249.1)
[26/Aug/2019:17:11:29 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET /ide.main.5b173b.css HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3879.0 Safari/537.36 Edg/78.0.249.1)
[26/Aug/2019:17:11:29 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET /ide.main.5b173b.js HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3879.0 Safari/537.36 Edg/78.0.249.1)
[26/Aug/2019:17:11:35 +0200] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3879.0 Safari/537.36 Edg/78.0.249.1)
```

### HASSIO Log
```
19-08-26 15:11:21 INFO (SyncWorker_11) [hassio.docker.addon] Start Docker add-on hassioaddons/vscode-amd64 with version 0.6.5
19-08-26 15:11:21 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_vscode
19-08-26 15:11:21 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_vscode
```

**Comment by frenck** [comment]
The add-on got a major upgrade, could you check again?

**Comment by eavanvalkenburg** [comment]
I'm on vacation, back next week, so I'll try it out then! Thanks!

**Comment by eavanvalkenburg** [comment]
Still nothing after upgrading both HA to 101.3 and this to 1.1.1, Pi-hole does still work through ingress and I can still reach VSC by going to <ha_ip>:8444 (the port I have set for this extention), but a white screen this time, instead of black...

Logs:
`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 1.1.1
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.3 LTS  (amd64 / qemux86-64)
 Home Assistant version: 0.101.3
 Supervisor version: 192
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:45:31] INFO: Starting the code server...
info  Server listening on http://127.0.0.1:8443
info    - No authentication
info    - Not serving HTTPS
[13:45:32] INFO: Starting NGinx...
[09/Nov/2019:13:45:33 +0100] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3952.0 Safari/537.36 Edg/80.0.320.5)
[09/Nov/2019:13:45:34 +0100] 200 10.0.1.113, 10.0.0.7, 172.30.32.1(172.30.32.2) GET /?reconnectionToken=3a538fab-3191-425f-81ec-84f88f467d5e&reconnection=false&skipWebSocketFrames=false HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3952.0 Safari/537.36 Edg/80.0.320.5)
`

**Comment by sinclairpaul** [comment]
Browser dev tools output would probably be good to see, I would guess it may be Websockets related.

**Comment by eavanvalkenburg** [comment]
Thanks @sinclairpaul, I grabbed just the errors and warnings from the log, flow was https://<ha_name>/lovelace to clicking the ingress button for VSC.

> /manifest.json:1 Manifest: property 'theme_color' ignored, 'var(--text-color)' is not a valid color.
> browserSocketFactory.ts:162 WebSocket connection to 'wss://<ha_name>/api/hassio_ingress/2YSvlSA3_4AEcbpNgQteGuk_0tzEJWR0gTAYUKqePz0/?reconnectionToken=5ee9ff32-689b-4a5d-ab65-34c89a073c35&reconnection=false&skipWebSocketFrames=false' failed: Error during WebSocket handshake: Unexpected response code: 200
> create @ browserSocketFactory.ts:114
> connect @ browserSocketFactory.ts:190
> (anonymous) @ browserSocketFactory.ts:190
> d @ browserSocketFactory.ts:190
> h @ remoteAgentConnection.ts:153
> u @ remoteAgentConnection.ts:208
> t.connectRemoteAgentManagement @ remoteAgentConnection.ts:208
> errors.ts:26 Uncaught Error: WebSocket close with status code 1006
> 
> Error: WebSocket close with status code 1006
>     at WebSocket.<anonymous> (browserSocketFactory.ts:129)
>     at errors.ts:26
> (anonymous) @ diff.ts:920
> setTimeout (async)
> unexpectedErrorHandler @ diff.ts:920
> onUnexpectedError @ errors.ts:49
> t.onUnexpectedError @ errors.ts:49
> createStorageService @ web.main.ts:219
> async function (async)
> createStorageService @ web.main.ts:219
> initServices @ web.main.ts:179
> open @ workbench.ts:434
> t.main @ web.main.ts:281
> t.create @ workbench.web.main.ts:76
> (anonymous) @ workbench.ts:233
> t._invokeFactory @ loader.js:983
> t.complete @ loader.js:1045
> s._onModuleComplete @ loader.js:1622
> s._resolve @ loader.js:1622
> s.defineModule @ loader.js:1268
> r @ loader.js:1697
> (anonymous) @ workbench.js:4
> (anonymous) @ workbench.ts:233
> extensionsRegistry.ts:124 Uncaught Error: Handler already set!
>     at u.setHandler (extensionsRegistry.ts:124)
>     at g.initialize (colorThemeStore.ts:66)
>     at new g (colorThemeStore.ts:62)
>     at new P (workbenchThemeService.ts:105)
>     at h._createInstance (instantiationService.ts:117)
>     at h._createServiceInstance (instantiationService.ts:216)
>     at h._createServiceInstanceWithOwner (instantiationService.ts:205)
>     at h._createAndCacheServiceInstance (instantiationService.ts:194)
>     at h._getOrCreateServiceInstance (instantiationService.ts:142)
>     at h._createInstance (instantiationService.ts:94)
> setHandler @ extensionsRegistry.ts:32
> initialize @ colorThemeStore.ts:39
> g @ colorThemeStore.ts:39
> P @ colorThemeStore.ts:53
> _createInstance @ instantiationService.ts:88
> _createServiceInstance @ instantiationService.ts:204
> _createServiceInstanceWithOwner @ instantiationService.ts:204
> _createAndCacheServiceInstance @ instantiationService.ts:140
> _getOrCreateServiceInstance @ instantiationService.ts:140
> _createInstance @ instantiationService.ts:88
> createInstance @ serviceCollection.ts:34
> acquireInstantiationService @ configurationService.ts:305
> (anonymous) @ workbench.ts:207
> setTimeout (async)
> (anonymous) @ workbench.ts:134
> invokeFunction @ serviceCollection.ts:34
> initServices @ workbench.ts:134
> startup @ workbench.ts:134
> open @ workbench.ts:434
> async function (async)
> open @ workbench.ts:434
> t.main @ web.main.ts:281
> t.create @ workbench.web.main.ts:76
> (anonymous) @ workbench.ts:233
> t._invokeFactory @ loader.js:983
> t.complete @ loader.js:1045
> s._onModuleComplete @ loader.js:1622
> s._resolve @ loader.js:1622
> s.defineModule @ loader.js:1268
> r @ loader.js:1697
> (anonymous) @ workbench.js:4
> (anonymous) @ workbench.ts:233
> browserSocketFactory.ts:162 WebSocket connection to 'wss://<ha_name>/api/hassio_ingress/2YSvlSA3_4AEcbpNgQteGuk_0tzEJWR0gTAYUKqePz0/?reconnectionToken=9fd6fcdb-742f-48bd-9a75-59b366c8283e&reconnection=false&skipWebSocketFrames=false' failed: Error during WebSocket handshake: Unexpected response code: 200
> create @ browserSocketFactory.ts:114
> connect @ browserSocketFactory.ts:190
> (anonymous) @ browserSocketFactory.ts:190
> d @ browserSocketFactory.ts:190
> h @ remoteAgentConnection.ts:153
> g @ remoteAgentConnection.ts:208
> t.connectRemoteAgentExtensionHost @ remoteAgentConnection.ts:284
> extensionHostProcessManager.ts:77 Error received from starting extension host
> (anonymous) @ extensionHostProcessManager.ts:66
> Promise.then (async)
> e @ extensionHostProcessManager.ts:66
> _createInstance @ instantiationService.ts:88
> createInstance @ serviceCollection.ts:34
> _createExtensionHosts @ extensionService.ts:95
> _startExtensionHostProcess @ abstractExtensionService.ts:116
> _initialize @ abstractExtensionService.ts:85
> D @ extensionService.ts:34
> _createInstance @ instantiationService.ts:88
> _createServiceInstance @ instantiationService.ts:204
> _createServiceInstanceWithOwner @ instantiationService.ts:204
> _createAndCacheServiceInstance @ instantiationService.ts:140
> _getOrCreateServiceInstance @ instantiationService.ts:140
> get @ serviceCollection.ts:34
> initLayout @ layout.ts:198
> (anonymous) @ workbench.ts:134
> invokeFunction @ serviceCollection.ts:34
> startup @ workbench.ts:134
> open @ workbench.ts:434
> async function (async)
> open @ workbench.ts:434
> t.main @ web.main.ts:281
> t.create @ workbench.web.main.ts:76
> (anonymous) @ workbench.ts:233
> t._invokeFactory @ loader.js:983
> t.complete @ loader.js:1045
> s._onModuleComplete @ loader.js:1622
> s._resolve @ loader.js:1622
> s.defineModule @ loader.js:1268
> r @ loader.js:1697
> (anonymous) @ workbench.js:4
> (anonymous) @ workbench.ts:233
> extensionHostProcessManager.ts:78 Error: WebSocket close with status code 1006
>     at WebSocket.<anonymous> (browserSocketFactory.ts:129)
> (anonymous) @ extensionHostProcessManager.ts:66
> Promise.then (async)
> e @ extensionHostProcessManager.ts:66
> _createInstance @ instantiationService.ts:88
> createInstance @ serviceCollection.ts:34
> _createExtensionHosts @ extensionService.ts:95
> _startExtensionHostProcess @ abstractExtensionService.ts:116
> _initialize @ abstractExtensionService.ts:85
> D @ extensionService.ts:34
> _createInstance @ instantiationService.ts:88
> _createServiceInstance @ instantiationService.ts:204
> _createServiceInstanceWithOwner @ instantiationService.ts:204
> _createAndCacheServiceInstance @ instantiationService.ts:140
> _getOrCreateServiceInstance @ instantiationService.ts:140
> get @ serviceCollection.ts:34
> initLayout @ layout.ts:198
> (anonymous) @ workbench.ts:134
> invokeFunction @ serviceCollection.ts:34
> startup @ workbench.ts:134
> open @ workbench.ts:434
> async function (async)
> open @ workbench.ts:434
> t.main @ web.main.ts:281
> t.create @ workbench.web.main.ts:76
> (anonymous) @ workbench.ts:233
> t._invokeFactory @ loader.js:983
> t.complete @ loader.js:1045
> s._onModuleComplete @ loader.js:1622
> s._resolve @ loader.js:1622
> s.defineModule @ loader.js:1268
> r @ loader.js:1697
> (anonymous) @ workbench.js:4
> (anonymous) @ workbench.ts:233
> extensionHostProcessManager.ts:77 Error received from starting extension host
> (anonymous) @ extensionHostProcessManager.ts:66
> Promise.then (async)
> e @ extensionHostProcessManager.ts:66
> _createInstance @ instantiationService.ts:88
> createInstance @ serviceCollection.ts:34
> _createExtensionHosts @ extensionService.ts:34
> _startExtensionHostProcess @ abstractExtensionService.ts:116
> _initialize @ abstractExtensionService.ts:85
> D @ extensionService.ts:34
> _createInstance @ instantiationService.ts:88
> _createServiceInstance @ instantiationService.ts:204
> _createServiceInstanceWithOwner @ instantiationService.ts:204
> _createAndCacheServiceInstance @ instantiationService.ts:140
> _getOrCreateServiceInstance @ instantiationService.ts:140
> get @ serviceCollection.ts:34
> initLayout @ layout.ts:198
> (anonymous) @ workbench.ts:134
> invokeFunction @ serviceCollection.ts:34
> startup @ workbench.ts:134
> open @ workbench.ts:434
> async function (async)
> open @ workbench.ts:434
> t.main @ web.main.ts:281
> t.create @ workbench.web.main.ts:76
> (anonymous) @ workbench.ts:233
> t._invokeFactory @ loader.js:983
> t.complete @ loader.js:1045
> s._onModuleComplete @ loader.js:1622
> s._resolve @ loader.js:1622
> s.defineModule @ loader.js:1268
> r @ loader.js:1697
> (anonymous) @ workbench.js:4
> (anonymous) @ workbench.ts:233
> extensionHostProcessManager.ts:78 Error: WebSocket close with status code 1006
>     at WebSocket.<anonymous> (browserSocketFactory.ts:129)
> (anonymous) @ extensionHostProcessManager.ts:66
> Promise.then (async)
> e @ extensionHostProcessManager.ts:66
> _createInstance @ instantiationService.ts:88
> createInstance @ serviceCollection.ts:34
> _createExtensionHosts @ extensionService.ts:34
> _startExtensionHostProcess @ abstractExtensionService.ts:116
> _initialize @ abstractExtensionService.ts:85
> D @ extensionService.ts:34
> _createInstance @ instantiationService.ts:88
> _createServiceInstance @ instantiationService.ts:204
> _createServiceInstanceWithOwner @ instantiationService.ts:204
> _createAndCacheServiceInstance @ instantiationService.ts:140
> _getOrCreateServiceInstance @ instantiationService.ts:140
> get @ serviceCollection.ts:34
> initLayout @ layout.ts:198
> (anonymous) @ workbench.ts:134
> invokeFunction @ serviceCollection.ts:34
> startup @ workbench.ts:134
> open @ workbench.ts:434
> async function (async)
> open @ workbench.ts:434
> t.main @ web.main.ts:281
> t.create @ workbench.web.main.ts:76
> (anonymous) @ workbench.ts:233
> t._invokeFactory @ loader.js:983
> t.complete @ loader.js:1045
> s._onModuleComplete @ loader.js:1622
> s._resolve @ loader.js:1622
> s.defineModule @ loader.js:1268
> r @ loader.js:1697
> (anonymous) @ workbench.js:4
> (anonymous) @ workbench.ts:233
> layout.ts:826 Uncaught TypeError: Cannot read property 'layout' of undefined
>     at t.Workbench.layout (layout.ts:826)
>     at web.main.ts:94
> layout @ layout.ts:814
> (anonymous) @ web.main.ts:94
> layout.ts:826 Uncaught TypeError: Cannot read property 'layout' of undefined
>     at t.Workbench.layout (layout.ts:826)
>     at web.main.ts:94
> layout @ layout.ts:814
> (anonymous) @ web.main.ts:94
> layout.ts:826 Uncaught TypeError: Cannot read property 'layout' of undefined
>     at t.Workbench.layout (layout.ts:826)
>     at web.main.ts:94
> layout @ layout.ts:814
> (anonymous) @ web.main.ts:94
> layout.ts:826 Uncaught TypeError: Cannot read property 'layout' of undefined
>     at t.Workbench.layout (layout.ts:826)
>     at web.main.ts:94
> layout @ layout.ts:814
> (anonymous) @ web.main.ts:94
> layout.ts:826 Uncaught TypeError: Cannot read property 'layout' of undefined
>     at t.Workbench.layout (layout.ts:826)
>     at web.main.ts:94
> layout @ layout.ts:814
> (anonymous) @ web.main.ts:94

**Comment by sinclairpaul** [comment]
From the logs it appears Websockets is failing (you should I believe see a 101 response).  Does your Nginx proxy have the Websocket directives set?

**Comment by eavanvalkenburg** [comment]
my nginx config for the site is this:

`
location / {
      proxy_pass https://ha;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # proxy_http_version 1.1;
      # proxy_set_header Upgrade $http_upgrade;
      # proxy_set_header Connection "upgrade";
  }

  location /api/websocket {
      proxy_pass https://ha/api/websocket;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
}
`

and after uncommenting the three lines in the first part it worked! thanks @sinclairpaul and @frenck. Closing the issue with the resolution for future reference.
