### ISSUE TITLE
Can't start vscode in HA - help with debug

### ISSUE THREAD

**Issue by andrejs2** [hassio-addons/addon-vscode#498]
# Problem/Motivation

Can't start Visual Studio Code addon in Home Assistant 

## Expected behavior

> When button start is pressed the addon should start the addon and make "open web ui" or similar button available

## Actual behavior

When start button is pressed noting happens, see this log output:
`-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.3.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.5  (amd64 / qemux86-64)
 Home Assistant Core: 2022.8.7
 Home Assistant Supervisor: 2022.08.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[10:54:19] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/code-server.sh
cont-init: info: /etc/cont-init.d/code-server.sh exited 0
cont-init: info: running /etc/cont-init.d/mosquitto.sh
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/mysql.sh
cont-init: info: /etc/cont-init.d/mysql.sh exited 0
cont-init: info: running /etc/cont-init.d/user.sh
cont-init: info: /etc/cont-init.d/user.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun code (no readiness notification)
s6-rc: info: service legacy-services successfully started
[10:54:21] INFO: Starting the code server...
[2022-09-11T08:54:21.657Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2022-09-11T08:54:22.195Z] info  code-server 4.6.0 6d3f9ca6a6df30a1bfad6f073f6fa33c0e63abdb
[2022-09-11T08:54:22.198Z] info  Using user-data-dir /data/vscode
[2022-09-11T08:54:22.238Z] info  Using config file ~/.config/code-server/config.yaml
[2022-09-11T08:54:22.239Z] info  HTTP server listening on http://0.0.0.0:1337/ 
[2022-09-11T08:54:22.239Z] info    - Authentication is disabled 
[2022-09-11T08:54:22.240Z] info    - Not serving HTTPS `

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
Would kindly ask for help hot to fix this...

**Comment by LastEnd1** [comment]
New user same problem

**Comment by JGNi** [comment]
Same problem here......

**Comment by tjorim** [comment]
Don't just reply 'same' as that is pretty useless. At least provide your system information. Also, which browser are you using to access HA?

**Comment by LastEnd1** [comment]
This is how I got it working. I unplugged the Pi and waited 15 sec, and plug it back in. After that I could start addons again.

Sometimes I have to do this after a backup restore.
