### ISSUE TITLE
ERROR: Unknown HTTP error occurred

### ISSUE THREAD

**Issue by grantalewis** [hassio-addons/addon-vscode#5]
# Problem/Motivation

> Error on first launch

## Expected behavior

> Successful launch

## Actual behavior

> Error:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 0.1.0
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[20:43:21] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant version: 0.84.6
 Supervisor version: 150
```

## Steps to reproduce

> Home Assistant 0.84.6 (Hass.io) running on VirtualBox (Ubuntu 64). I received this error on first installation / attempt to run. The only config option I changed was the addition of a password. Running Duck DNS / Let's Encrypt.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
The addon should still launch with this error, do you see any other issues?

**Comment by grantalewis** [comment]
Nothing of note either in the HA or Hass.io system logs.
