### ISSUE TITLE
Expose code-server to internet

### ISSUE THREAD

**Issue by mar-schmidt** [hassio-addons/addon-vscode#503]
Is it possible to expose the addon to the supervisor host? My wish is to use the code-server capabilities to do development on any project (not nessesarly home assistant config) from outside of my own network.

**Comment by frenck** [comment]
> My wish is to use the code-server capabilities to do development on any project (not nessesarly home assistant config) from outside of my own network.

There is no such limitation. You can work on anything you like.
It is accessible via the Home Assistant interface, also from the public network.

**Comment by mar-schmidt** [comment]
My question was probably poorly explained.

What I'm looking for is an exposed port so that I can access code-server on _hostip:port_ without having to open vscode through home assistant interface.

This is for example possible with the unifi addon and from what I understand the reason it's possible is because of an exposed port on the docker container. Excuse me if I'm making incorrect assumptions but I hope my request is abit more clear now.

Thanks for a great addon

**Comment by frenck** [comment]
The addon is only available via ingress.

In case of UniFi, if ingress was possible, it would have had it too. That is unfortunately a limitation of the Uni-Fi app.

There is no port option on this add-on, is has been remove quite some time ago.

**Comment by mar-schmidt** [comment]
Thanks for the explanation
