### ISSUE TITLE
Context menu to reload automations/themes/etc

### ISSUE THREAD

**Issue by Fusseldieb** [hassio-addons/addon-vscode#51]
This is both an feature request and a issue.

Currently I'm using "Configurator" in the Hassio addons to make changes to files. Home Assistant needs a reload command for specific files to reread them and "Configurator" has a little menu to reload certain things, which comes in handy almost every time.

![image](https://user-images.githubusercontent.com/4715129/65168741-87461500-da1b-11e9-8bdf-0a3f96570f0f.png)

The VSCode Addon in Hassio completely lacks this menu, which makes me switch back and forth between pages just to reload something, which can be very tedious. That's why I'm still on "Configurator".

A additional context menu to reload all those things would be awesome!

**Comment by sinclairpaul** [comment]
Open a Terminal in VSCode and type `hassio help` you should be able to do all you need from there.  Adding a menu to VSCode isn't really feasible.

**Comment by Fusseldieb** [comment]
> Open a Terminal in VSCode and type `hassio help` you should be able to do all you need from there.

I couldn't find a way to reload specific files there...

> Adding a menu to VSCode isn't really feasible.

Maybe not in VSCode, but as a Extension.

**Comment by sinclairpaul** [comment]
I would suggest you look to contribute to the HA Config extension at https://github.com/keesschollaart81/vscode-home-assistant

**Comment by Fusseldieb** [comment]
Thanks. Just made a feature request over there, let's see...
