### ISSUE TITLE
Cannot start VS Code addon

### ISSUE THREAD

**Issue by yardee** [hassio-addons/addon-vscode#510]
# Problem/Motivation
Addon cannot start, logs are not telling me much (Folder /run/uncaught-logs doesn’t exist.).

## Expected behavior

Addon started.

## Actual behavior

Addon not starting. Logs:
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
Illegal instruction (core dumped)
cont-init: info: /etc/cont-init.d/00-banner.sh exited 132
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Illegal instruction (core dumped)
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 132
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
Illegal instruction (core dumped)
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 132
cont-init: info: running /etc/cont-init.d/code-server.sh
Illegal instruction (core dumped)
cont-init: info: /etc/cont-init.d/code-server.sh exited 132
cont-init: info: running /etc/cont-init.d/mosquitto.sh
Illegal instruction (core dumped)
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 132
cont-init: info: running /etc/cont-init.d/mysql.sh
Illegal instruction (core dumped)
cont-init: info: /etc/cont-init.d/mysql.sh exited 132
cont-init: info: running /etc/cont-init.d/user.sh
Illegal instruction (core dumped)
cont-init: info: /etc/cont-init.d/user.sh exited 132
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

## Steps to reproduce

I am not sure which update cause this issue.

**Comment by yardee** [comment]
I have same issue with Grafana addon

**Comment by tjorim** [comment]
Please post your system information, you can find it in the system settings or (partially) at top of the add-on logs.

**Comment by yardee** [comment]
I'm running Home Assistant Operating System:
Home Assistant 2022.10.3
Supervisor 2022.10.0
Operating System 9.0
Frontend 20221010.0 - latest
generic-x86-64
Studio Code Server 5.4.0

Everything should be on latest version. I have tried to uninstall VS code and install again, still having the issue. Are you missing any more information?
