### ISSUE TITLE
Auto-completion does not work anymore

### ISSUE THREAD

**Issue by armayen** [hassio-addons/addon-vscode#517]
# Problem/Motivation

Auto-completion does not work for entities, services, etc.. When I press CTRL+space I receive loading.. and then No Suggestions.

## Expected behavior

Listing entities when I type light. or press CTRL+Shift

## Actual behavior

Nothing.. only when I hit CTRL+space --> loading... --> No Suggestions.

## Steps to reproduce

I don't know.
I reinstalled the Addon
I resetted the settings via terminal
I deleted the config file before reinstalling the Addon

**Comment by armayen** [comment]
Nevermind.. I restored a backup and it works again.

**Comment by michelsup** [comment]
I do mind. I run a fresh instance and it doesn't work for me too, and no, I don't have backups. 
I even tried to set a token and so on, but no luck.
