### ISSUE TITLE
Unable to fully start VSCode server

### ISSUE THREAD

**Issue by terri1769** [hassio-addons/addon-vscode#528]
# Problem/Motivation

Unable to start VSCode add-on after new install and restore from backup

## Expected behavior

Expect to be able to access VSCode from browser

## Actual behavior

If I try to access it from the link in the side panel, I get "Add-on is not running. Please start it first".  Clicking Start in the add-on info tries to start the server but no errors are generated and it never successfully starts.

## Steps to reproduce
Not sure it's reproducible outside of my system.  I installed HAOS onto a new Intel NUC then restored config from backup.  Have not been able to start VSCode Server add-on despite uninstalling and reinstalling the add-on.

## Proposed changes
Unknown

Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

Generic x86-64

Log:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.4.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.11.2
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Log level is set to DEBUG
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[21:33:26] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/code-server.sh
cont-init: info: /etc/cont-init.d/code-server.sh exited 0
cont-init: info: running /etc/cont-init.d/mosquitto.sh
[21:33:27] DEBUG: Requested API resource: http://supervisor/services/mqtt
[21:33:27] DEBUG: Request method: GET
[21:33:27] DEBUG: Request data: {}
[21:33:27] DEBUG: API HTTP Response code: 200
[21:33:27] DEBUG: API Response: {"result": "ok", "data": {"host": "core-mosquitto", "port": 1883, "ssl": false, "protocol": "3.1.1", "username": "addons", "password": "Ohngoosi5euxe2eiciengeit9Fiey6eebixohmosie7Eng4Edab3iepiFeongoor", "addon": "core_mosquitto"}}
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/mysql.sh
cont-init: info: /etc/cont-init.d/mysql.sh exited 0
cont-init: info: running /etc/cont-init.d/user.sh
cont-init: info: /etc/cont-init.d/user.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun code (no readiness notification)
s6-rc: info: service legacy-services successfully started
[21:33:28] INFO: Starting the code server...
[2022-11-14T02:33:30.295Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2022-11-14T02:33:31.560Z] info  code-server 4.8.3 977b853a1e162ab583aed64b1322d1515c57728c
[2022-11-14T02:33:31.563Z] info  Using user-data-dir /data/vscode
[2022-11-14T02:33:31.626Z] info  Using config file ~/.config/code-server/config.yaml
[2022-11-14T02:33:31.627Z] info  HTTP server listening on http://0.0.0.0:1337/ 
[2022-11-14T02:33:31.627Z] info    - Authentication is disabled 
[2022-11-14T02:33:31.627Z] info    - Not serving HTTPS

**Comment by frenck** [comment]
Restart your machine after restoring a backup. That will fix it.


../Frenck

**Comment by terri1769** [comment]
I've actually restarted the machine a few times without luck.  That's okay though.  I'll figure something out.  Thanks for your time.

**Comment by frenck** [comment]
Please be sure to report it to the Supervisor project. From an add-on perspective, there is not much I can do.

../Frenck
