### ISSUE TITLE
Device class water gives an error

### ISSUE THREAD

**Issue by bikeymouse** [hassio-addons/addon-vscode#530]
# Problem/Motivation

I have defined  device_class: water in my configuration.yaml

This raises a warning in VSCode:

_Value is not accepted. Valid values: "apparent_power", "aqi", "awning", "battery", "battery_charging", "blind", "carbon_dioxide", "carbon_monoxide", "cold", "connectivity", "current", "curtain", "damper", "date", "door", "duration", "energy", "frequency", "garage", "garage_door", "gas", "gate", "heat", "humidity", "illuminance", "light", "lock", "moisture", "monetary", "motion", "moving", "nitrogen_dioxide", "nitrogen_monoxide", "nitrous_oxide", "occupancy", "opening", "outlet", "ozone", "plug", "pm1", "pm10", "pm25", "power", "power_factor", "presence", "pressure", "problem", "receiver", "running", "safety", "shade", "shutter", "signal_strength", "smoke", "sound", "speaker", "sulphur_dioxide", "switch", "tamper", "temperature", "timestamp", "tv", "update", "vibration", "volatile_organic_compounds", "voltage", "window".yaml-schema: http://schemas.home-assistant.io/configuration(1)_

> (Why the issue was filed)

According to the documentation "water" iOS a valid device-class: https://www.home-assistant.io/integrations/sensor/

## Expected behavior

No error/warning. 

## Proposed changes

Validation should be done on the latest allowable value-list.

> (If you have a proposed change, workaround or fix,

Add "water" to the list against this is evaluated.

**Comment by frenck** [comment]
This is not an add-on issue. Feel free to report it with the VCode extension.

../Frenck
