### ISSUE TITLE
Studio Code server is not starting

### ISSUE THREAD

**Issue by Richspr** [hassio-addons/addon-vscode#534]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Could you provide things like: Logs? Error messages? Reproduction steps? Maybe screenshots?

Like saying: Doesn't work, isn't something I can help debugging :)

**Comment by Richspr** [comment]
Hi I am new hear so hope I am in the right place, and provided the necessary info
I have installed SCS (restarted HA) and when I try to start it nothing happens.
The link to the service is in the side bar but when I click on it the message is SCS is not  running
The log file is below:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.4.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.11.3
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[15:16:01] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/code-server.sh
cont-init: info: /etc/cont-init.d/code-server.sh exited 0
cont-init: info: running /etc/cont-init.d/mosquitto.sh
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/mysql.sh
cont-init: info: /etc/cont-init.d/mysql.sh exited 0
cont-init: info: running /etc/cont-init.d/user.sh
cont-init: info: /etc/cont-init.d/user.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun code (no readiness notification)
s6-rc: info: service legacy-services successfully started
[15:16:03] INFO: Starting the code server...
[2022-11-27T15:16:04.719Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2022-11-27T15:16:05.930Z] info  code-server 4.8.3 977b853a1e162ab583aed64b1322d1515c57728c
[2022-11-27T15:16:05.935Z] info  Using user-data-dir /data/vscode
[2022-11-27T15:16:05.979Z] info  Using config file ~/.config/code-server/config.yaml
[2022-11-27T15:16:05.979Z] info  HTTP server listening on http://0.0.0.0:1337/ 
[2022-11-27T15:16:05.979Z] info    - Authentication is disabled 
[2022-11-27T15:16:05.979Z] info    - Not serving HTTPS 
Guess I am doing something wrong.
Regard R

**Comment by frenck** [comment]
The add-on is running. Sounds like Home Assistant has lost track of the running state of add-ons. Try rebooting your instance and see if it is resolved.

**Comment by Richspr** [comment]
Thank for the quick reply I will reboot it

**Comment by Richspr** [comment]
Hi I have rebooted and asked SCS to start but it is still not running. Had a look at the log files which are below and I don't think they have changed.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.4.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.11.3
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[15:16:01] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/code-server.sh
cont-init: info: /etc/cont-init.d/code-server.sh exited 0
cont-init: info: running /etc/cont-init.d/mosquitto.sh
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/mysql.sh
cont-init: info: /etc/cont-init.d/mysql.sh exited 0
cont-init: info: running /etc/cont-init.d/user.sh
cont-init: info: /etc/cont-init.d/user.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun code (no readiness notification)
s6-rc: info: service legacy-services successfully started
[15:16:03] INFO: Starting the code server...
[2022-11-27T15:16:04.719Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2022-11-27T15:16:05.930Z] info  code-server 4.8.3 977b853a1e162ab583aed64b1322d1515c57728c
[2022-11-27T15:16:05.935Z] info  Using user-data-dir /data/vscode
[2022-11-27T15:16:05.979Z] info  Using config file ~/.config/code-server/config.yaml
[2022-11-27T15:16:05.979Z] info  HTTP server listening on http://0.0.0.0:1337/ 
[2022-11-27T15:16:05.979Z] info    - Authentication is disabled 
[2022-11-27T15:16:05.979Z] info    - Not serving HTTPS 

suggestion appreciated.
R

**Comment by frenck** [comment]
I don't have answers; according to the logs you provided, the add-on is running an healthy.

**Comment by Richspr** [comment]
Ok many thanks for giving it a look.

**Comment by Richspr** [comment]
Hi Frenck. I have now sorted this issue  I reboot my RPi and the SCS is up and running as expected. I had previously been just restarting HA.
R.
