### ISSUE TITLE
Addon can't open after latest update

### ISSUE THREAD

**Issue by dankarization** [hassio-addons/addon-vscode#536]
# Problem/Motivation

I get this error on 5 different HA servers on different locations after latest vscode update while opening ui every time. I can't use it(
![image](https://user-images.githubusercontent.com/26330178/205486309-5ed1bb36-b4ae-43dd-9c91-21cf5b2370d2.png)

## Expected behavior
It just opens as normal.

## Steps to reproduce
Just update and open.

I already tried restarting servers and completely reinstalling the addon. Nothing helps.

Logs>>

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.4.1
 You are running the latest version of this add-on.
 System: Ubuntu 20.04.5 LTS  (aarch64 / odroid-c2)
 Home Assistant Core: 2022.11.5
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[14:33:39] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/code-server.sh
cont-init: info: /etc/cont-init.d/code-server.sh exited 0
cont-init: info: running /etc/cont-init.d/mosquitto.sh
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/mysql.sh
cont-init: info: /etc/cont-init.d/mysql.sh exited 0
cont-init: info: running /etc/cont-init.d/user.sh
cont-init: info: /etc/cont-init.d/user.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun code (no readiness notification)
s6-rc: info: service legacy-services successfully started
[14:33:49] INFO: Starting the code server...
[2022-12-04T10:33:55.583Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2022-12-04T10:34:00.525Z] info  code-server 4.8.3 977b853a1e162ab583aed64b1322d1515c57728c
[2022-12-04T10:34:00.535Z] info  Using user-data-dir /data/vscode
[2022-12-04T10:34:00.727Z] info  Using config file ~/.config/code-server/config.yaml
[2022-12-04T10:34:00.728Z] info  HTTP server listening on http://0.0.0.0:1337/ 
[2022-12-04T10:34:00.729Z] info    - Authentication is disabled 
[2022-12-04T10:34:00.730Z] info    - Not serving HTTPS 
[14:34:03] Extension host agent started.
[14:34:04] Extension host agent started.
[14:34:10] No ptyHost heartbeat after 6 seconds
[14:34:10] No ptyHost heartbeat after 6 seconds

**Comment by dankarization** [comment]
I was updating for every new version, and I still have this problem on every single one of them. No, this issue is not inactive- just noone is answering me..

**Comment by GaTechThomas** [comment]
I'm now getting a blank screen when trying to use this addon in home assistant.

**Comment by jefutte** [comment]
Also a blank screen here when I try to open this in HA. Tried restarting add-on, restarting HA, reinstall addon.

**Comment by GaTechThomas** [comment]
I was eventually about to get it to work. Seems that it needs to just wait there with a blank screen for a minute or so.

**Comment by kumters** [comment]
> I was eventually about to get it to work. Seems that it needs to just wait there with a blank screen for a minute or so.

Very the same for me. It looks like after the upgrade it took some time to process internal things and after a while, it will be ready.

**Comment by dankarization** [comment]
I still have the same problem- not the blank screen, but error from my screenshot :(

**Comment by supershree** [comment]
Having a issue with the log ending Not serving https
Just trying to press start and it doesn't do anything. 


s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[15:00:02] INFO: Configuring timezone (America/New_York)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
[15:00:03] INFO: Starting code-server...
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2023-01-29T20:00:04.548Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2023-01-29T20:00:05.085Z] info  code-server 4.9.1 f7989a4dfcf21085e52157a01924d79d708bcc05
[2023-01-29T20:00:05.089Z] info  Using user-data-dir /data/vscode
[2023-01-29T20:00:05.115Z] info  Using config file ~/.config/code-server/config.yaml
[2023-01-29T20:00:05.116Z] info  HTTP server listening on http://0.0.0.0:1337/ 
[2023-01-29T20:00:05.116Z] info    - Authentication is disabled 
[2023-01-29T20:00:05.117Z] info    - Not serving HTTPS

**Comment by capic** [comment]
Hello same issue here, I press start and it does nothing

**Comment by artlov** [comment]
It linked with my reported issue there: https://github.com/hassio-addons/addon-vscode/issues/586 .
If waiting a minute or so I found myself in the same situation as described there: "An unexpected error occured that requires a reload of this page. The workbench failed to connect to the server (Error: Time limit reached)".
But seems that nobody of developers or contibutors have no interest to solve this.
