### ISSUE TITLE
since core 2022.12.0 wrong error on adding country in configuration.yaml

### ISSUE THREAD

**Issue by marcelhoogantink** [hassio-addons/addon-vscode#539]
# Problem/Motivation

> since core 2022.12.0 wrong error on adding country in configuration.yaml

## Expected behavior

> No error

## Actual behavior

> Error "property country is not allowed" appairs

## Steps to reproduce

>Just add country: [code] to homeassistant: section
## Proposed changes

> Add country to allowed keywords

![error](https://user-images.githubusercontent.com/51886888/206431677-7e56efec-d437-482f-a297-cbc7145bb076.PNG)

**Comment by frenck** [comment]
This is not an issue with the add-on itself, but with the VSCode Extensions for Home Assistant (the configuration helper). Please report the issue with them.

Thanks 👍 

../Frenck
