### ISSUE TITLE
Still erroring non-errors - climate mqtt entity

### ISSUE THREAD

**Issue by IanAdd** [hassio-addons/addon-vscode#551]
# Problem/Motivation

There has ben a significant improvement issued which removes a number of false errors I was experiencing, however I have a new one and an unresolved one.

## Expected behavior

No red highlighting

## Actual behavior

Screen shot of errored climate entity definition provided.

## Steps to reproduce
![climate](https://user-images.githubusercontent.com/10492213/207794342-a2bdc44f-06e9-4104-9cd2-7a0e81e9303b.png)

> (How can someone else make/see it happen)

1) The red complaint about the **action_topic** definition seems erroneous.

2) the red complaint on the **modes** - I am happy enough to see it as a warning that I might be wrong, so could be left as is.?

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi there @IanAdd 👋 

That is an issue with the VSCode extension the add-on uses, not the add-on itself.

Please report your issue with the extension, here: <https://github.com/keesschollaart81/vscode-home-assistant/issues>

Thanks! 👍 

../Frenck
