### ISSUE TITLE
{%Y} messes up syntax highlighting

### ISSUE THREAD

**Issue by mxwi** [hassio-addons/addon-vscode#553]
# Problem/Motivation

> the addon [Waste Collection Schedule](https://github.com/mampfes/hacs_waste_collection_schedule) accepts [a variable "{%Y}"](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md#configuration-variables) in the configuration.yaml. This messes up the syntax highlighting.

## Expected behavior

> ![image](https://user-images.githubusercontent.com/32883521/208066651-d65d648f-1e0a-4c7e-9da0-d4a317f00f1c.png)

## Actual behavior

> ![image](https://user-images.githubusercontent.com/32883521/208066705-948379ea-4563-4c10-bf4c-100837aaaf31.png)

## Steps to reproduce

> work with the "{%Y}" variable from Waste Collection Schedule addon

**Comment by frenck** [comment]
From an add-on perspective, there is not much I can do. This functionality is provided by the Home Assistant Config Helper VSCode extension. Please report this issue upstream with that project.

Thanks! 👍 

../Frenck
