### ISSUE TITLE
MQTT Device Tracker Showing Errors

### ISSUE THREAD

**Issue by jman203** [hassio-addons/addon-vscode#561]
# Problem/Motivation

> VS Code is showing errors in the config.yaml file when following the HA documentation for MQTT Device Tracker at https://www.home-assistant.io/integrations/device_tracker.mqtt/

## Expected behavior

> No error as the config file is following the HA documentation. The MQTT Device Tracker is working as expected.

## Actual behavior

> VS Code is requesting the property "devices" which is not listed in MQTT Device Tracker documentation. It is also showing "state_topic" as a property that is not allowed. However, this is shown in the MQTT documentation.

![Screenshot 2022-12-29 161248](https://user-images.githubusercontent.com/67200853/210022882-6a48a9ba-5edd-4280-90ef-b78a1dc1bc2f.png)

## Steps to reproduce

> See screenshot above for example config.

## Proposed changes

> (If you have a proposed change, workaround or fix, describe the rationale behind it)

**Comment by frenck** [comment]
This is not an issue with the add-on but with the Home Assistant VSCode extension. Please report your issue with the Home Assistant Config Helper VSCode extension project.

Thanks 👍 

../Frenck
