### ISSUE TITLE
Add new configuration option for CLI arguments

### ISSUE THREAD

**Issue by egandro** [hassio-addons/addon-vscode#562]
# Problem/Motivation

I want to install the open-remote-ssh extension (since the remote-ssh extension is closed source and can't be used by Code Server)

The extension is here: https://github.com/jeanp413/open-remote-ssh

In VSCode it's name is "Open Remote - SSH"

## Expected behavior

As the extension is using an "api", we need to tell this visual studio code at startup.

NOT Solution 1) I hacked my way in the docker container, and added a api.json as described here: https://code.visualstudio.com/api/advanced-topics/using-proposed-api

Unfortunately that doesn't work. (according to my understanding this will only work with "vscode-insiders")

Solution 2)

Add an option as mentioned here:

https://github.com/microsoft/vscode/issues/148176

A parameter to the start script

` --enable-proposed-api what.ever`

## Proposed changes

It would be super cool do just add a configuration option (such as the "init_commands") to the CLI options right here:

https://github.com/hassio-addons/addon-vscode/blob/main/vscode/rootfs/etc/s6-overlay/s6-rc.d/code-server/run#L24

So the user can add the string ` --enable-proposed-api jeanp413.open-remote-ssh`

Please consider adding this - willing to help.

**Comment by frenck** [comment]
The goal of this add-on is to manage your Home Assistant configuration, why would adding an third-party remote thing help?

**Comment by egandro** [comment]
> The goal of this add-on is to manage your Home Assistant configuration, why would adding an third-party remote thing help?

How is that question related to the Problem/Motivation?

There are simple reasons for me to do so. I don't see any point in disclosing or discussing them - nothing secret - I can of course! I see no point how that profits the Problem/Motivation.

The "--enable-proposed-api" option - or adding other cli arguments are a resonable extension request.

**Comment by frenck** [comment]
Alright, it seems like you just want that feature but do not want to elaborate otherwise; because of that, I don't feel the need to spend time on it.

Thanks for your suggestion, but closing it here.

../Frenck

**Comment by egandro** [comment]
I am sending you a PR and then you can decide.

**Comment by frenck** [comment]
I already did, I have no intention of adding is considering the above.

**Comment by egandro** [comment]
This solves my problem: https://superuser.com/questions/1528212/vscode-ssh-with-multiple-hops/1528213#1528213

**Comment by egandro** [comment]
This example helped the most: https://wiki.gentoo.org/wiki/SSH_jump_host

`
## add this to the ~/.ssh/config (Linux, mac, Windows)
## on HA in the SSH (i am using SSH & Web Terminal)  - allow_tcp_forwarding needs to be true

### First jump host. Directly reachable
Host alphajump
  HostName jumphost1.example.org
 
### Second jumphost. Only reachable via jumphost1.example.org
Host betajump
  HostName jumphost2.example.org
  ProxyJump alphajump
 
### Host only reachable via alphajump and betajump
Host behindalphabeta
  HostName behindalphabeta.example.org
  ProxyJump betajump
`

**Comment by SgtBatten** [comment]
> This example 

Hi, could you please provide some guidance on if this is the solution for me. I would like to edit files from other machines and docker containers using the HA vscode addon. is that what you have achieved here?
