### ISSUE TITLE
Auto-completion doesn't work in subfolders

### ISSUE THREAD

**Issue by Buddinski88** [hassio-addons/addon-vscode#563]
# Problem/Motivation

I currently divide my YAML files into individual groups and place them in separate subfolders.
Within the YAML files stored in them, the code is not auto-completed.

## Expected behavior

Auto-completion should also work within a subfolder.

## Actual behavior

If I try to add a value inside one of these YAML files. E.g. "binary_sensor.", then the possible values are not listed.

## Steps to reproduce

1. Create a new folder
2. Create within the folder a new YAML file
3. Try a value such as "binary_sensor." to add

**Comment by frenck** [comment]
This add-on does not provide the auto-completion but the Home Assistant config helper Visual Studio Code extension does.

Please report it with that project upstream.

Thanks! 👍 

../Frenck

**Comment by Buddinski88** [comment]
> This add-on does not provide the auto-completion but the Home Assistant config helper Visual Studio Code extension does.
> 
> Please report it with that project upstream.
> 
> Thanks! 👍
> 
> ../Frenck

Thank you for the fast response. So i should create a issue directly a home assistant core? Can you perhaps link the repository?

**Comment by frenck** [comment]
The extension is a third-party extension, created by Kees:

<https://github.com/keesschollaart81/vscode-home-assistant/>
