### ISSUE TITLE
Is possible to add the requirements to documentation for install the addon?

### ISSUE THREAD

**Issue by CiquattroFPV** [hassio-addons/addon-vscode#57]
# Problem/Motivation
 I have Pi3 with Hassio but I can't install the addon

## Actual behavior
Can' install the addon 
" This add-on is not available on your system."

## Steps to reproduce
Hassio Menu > Addon store > Search for Visual Studio Code

## Proposed changes
Add requirements sections to the documentation

**Comment by tjorim** [comment]
It's already documented: https://github.com/hassio-addons/addon-vscode#known-issues-and-limitations

**Comment by frenck** [comment]
Besides that, the supported architectures are listed right below the add-on title 🤷‍♂ 

![image](https://user-images.githubusercontent.com/195327/67939959-ed08ed80-fbd2-11e9-9267-abae81eb3f1e.png)
