### ISSUE TITLE
Studio Code Server fails to start after a backup restore, even if reinstalled

### ISSUE THREAD

**Issue by AndySymons** [hassio-addons/addon-vscode#574]
# Problem/Motivation

After restoring my system from a backup, Studio Code Server said it is not running, start it first. I pressed the start button but it has no effect.  

<img width="1289" alt="Screen Shot 2023-02-10 at 21 35 59" src="https://user-images.githubusercontent.com/14819812/218204053-f73cbee7-17f7-4972-8293-f1bab099ab58.png">

## Expected behavior

Studio Code server should start.

## Actual behavior

Keeps saying it needs starting, even after reinstalling. 
Log seems to show it is OK. 

```
Studio Code Server
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.5.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.1.7
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
```

## Steps to reproduce

Do a full backup. Restore it, then try to start Stdio Code Server. 

## Proposed changes

None. A fix is desperately needed!

**Comment by sinclairpaul** [comment]
This is generally an issue with the Supervisor, please perform a full system reboot and try again.

**Comment by sFeri01** [comment]
It just happened to me too but it's the same for every addon. What helped for me is doing a clean install and partial restore without addons and then installing the addons manually.
