### ISSUE TITLE
Disable auto-save while editing config.yaml?

### ISSUE THREAD

**Issue by kmanan** [hassio-addons/addon-vscode#579]
# Problem/Motivation

> I am trying to edit the http config under config.yaml and since VSCode auto saves when I stop typing, I lose access to my HA instance as I have not completed the edit.

## Expected behavior

> Toggle an option to disable / enable auto-save edits

## Actual behavior

> Partial edits are saved and I lose access to HA since I am editing config.yaml

## Steps to reproduce

> Edit a file

**Comment by frenck** [comment]
> Toggle an option to disable / enable auto-save edits

That is a VSCode setting and isn't add-on related. Just go into the VSCode workspace settings and change your VScode config the way you like.

../Frenck
