### ISSUE TITLE
File not found: ....

### ISSUE THREAD

**Issue by VNRARA** [hassio-addons/addon-vscode#589]
# Problem/Motivation

`
File not found: /usr/local/lib/code-server/lib/vscode/extensions/keesschollaart.vscode-home-assistant-1.34.0/jinja-language-configuration.json`

Keeps showing up.

## Steps to reproduce

Just run Studio Code. 

## Proposed changes

Remove whatever is looking for that file or add the file in.

**Comment by DvdEnde** [comment]
I have noticed same issue. reinstalled Studio Code Server and logfile shows a number of error messages about non-existant files (see image)
![image](https://user-images.githubusercontent.com/114862353/233835815-5ff7553c-485a-4b35-b2bf-183045e6572d.png)

**Comment by rophome** [comment]
also discussed on home-assistant forum : https://community.home-assistant.io/t/unable-to-load-schema-from-http-schemas-home-assistant-io-integration-automation-no-content-yaml-768/557688/16
