### ISSUE TITLE
Studio Code server not loading when I accessing HA from outside of local network

### ISSUE THREAD

**Issue by Maggus85** [hassio-addons/addon-vscode#592]
# Problem

I not able to open this addon when I access HA from outside of local network
![fromoutside](https://user-images.githubusercontent.com/2716445/227568927-dae46940-7797-41da-909f-c823bc4da286.PNG)

When I access this addon from my local network everything is working fine:
![image](https://user-images.githubusercontent.com/2716445/227567097-47c485bd-f5f4-49bd-a958-db5ee7b7cd40.png)

Problem occurs when I started using NGINX Home Assistant SSL proxy addon to access HA from outside.

When I did not use this addon and just forwad port on router, everything was working fine

**Comment by sinclairpaul** [comment]
Please see #584
