### ISSUE TITLE
vsc addon 5.5.4 cpu to +100%

### ISSUE THREAD

**Issue by eddysteurs** [hassio-addons/addon-vscode#598]
# Problem/Motivation
since the upgrade to version 5.5.4 after using vsc addon is gradually brings HA CPU usage to 100% 
> (Why the issue was filed)
It is slowing down HA
## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
![image](https://user-images.githubusercontent.com/9960284/227716653-9c07a9f3-0d88-4147-8d7e-1ef64c45984b.png)

**Comment by sealbro** [comment]
The same problem
