### ISSUE TITLE
Won't accept password

### ISSUE THREAD

**Issue by DavidFW1960** [hassio-addons/addon-vscode#6]
# Problem/Motivation
Can't open vscode
> (Why the issue was filed)
VScode gets to logon screen but won't accept password
## Expected behavior

> (What you expected to happen)

## Actual behavior
just keeps looping and asking for password
> (What actually happened)
```
parse error: Expected string key before ':' at line 1, column 4
[18:31:52] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant version: 0.90.2
 Supervisor version: 150
.
.
.
.
.
ERROR Failed to parse cookies {"error":{}}
ERROR Failed to parse cookies {"error":{}}
ERROR Failed to parse cookies {"error":{}}
ERROR Failed to parse cookies {"error":{}}
ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/data/vscode/Backups/workspaces.json'\n\nError: ENOENT: no such file or directory, open '/data/vscode/Backups/workspaces.json'\n    at Timeout.setTimeout [as _onTimeout] (eval at exports.requireModule (/usr/local/bin/code-server:468:27625), <anonymous>:56921:31)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)\n"}
ERROR Failed to parse cookies {"error":{}}
ERROR Failed to parse cookies {"error":{}}
ERROR Failed to parse cookies {"error":{}}
ERROR Failed to parse cookies {"error":{}}
```

Just using default config with a !secret password...

![image](https://user-images.githubusercontent.com/36390762/55058658-b446ea00-50c0-11e9-9354-ef5841f592d6.png)

Addon config:
```
{
  "password": "!secret vscodesecret",
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "packages": [],
  "init_commands": []
}
```

Also tried switching protection mode off..
## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by gnkarn** [comment]
in my case it accepted password just fine ,  but after installing it causes a reboot , i just waited to complete and it seams to be working ok, thankyou

**Comment by sinclairpaul** [comment]
Looking at the forums, looks like this is good, probably an encoding issue (special characters in the password).  If its fixed could you close it out pretty please? :)

**Comment by frenck** [comment]
Just released `v0.2.0`, the password option has been dropped and now uses HA Authentication.
This solves this issue as well.

**Comment by marcoboers94** [comment]
@frenck Could you please update the readme to reflect this change. The password option is still stated there and I didn't know it was deleted till I read your comment on this closed issue.

**Comment by timmo001** [comment]
@marcoboers94 check the current version of the readme. You might be looking at an older version:

https://github.com/hassio-addons/addon-vscode#configuration

**Comment by frenck** [comment]
@marcoboers94 Done.
