### ISSUE TITLE
Can't pull latest container

### ISSUE THREAD

**Issue by taw123** [hassio-addons/addon-vscode#607]
**Caveat** In order to keep this simple I am going to leave out ALOT of details I doubt are particularly relevant. If you wish to know the details for troubleshooting please let me know.

I am unable to pull the current VScode container (regardless of TAG). I am getting an access denied error from GIT.

```
# docker pull ghcr.io/hassio-addons/vscode
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/hassio-addons/vscode/manifests/latest": denied
# docker pull ghcr.io/hassio-addons/vscode:x86_64
Error response from daemon: Head "https://ghcr.io/v2/hassio-addons/vscode/manifests/x86_64": denied
```

Longer story is that I am attempting to use the HASSIO container with HA Core running in docker. I overroad the entrypoint that deals with supervisor and replaced it with a simple cp /root/.code-server/settings.json...  Should be all set IF I can get docker to pull the original container...

I am clearly missing something simple and obvious. I have never needed to (or even looked at how to set up) log in with my GitHub credentials as all containers in DockerHub and and thus far on GitHub have been published public for release. Is it possible that is NOOT the case here?

Thanks for any help, love to get off the linuxserver container I have hacked up for use in HA and join mainstream build-train...  (well mostly main stream, right 😉)..

--Tom

**Comment by frenck** [comment]
You can't (and should not) pull this, as this is not just a Docker container, but an Home Assistant add-on. Please read the documentation for the installation instructions:

https://github.com/hassio-addons/addon-vscode/blob/main/vscode/DOCS.md#installation

../Frenck

**Comment by taw123** [comment]
I do understand this plugin installs a number of other related components. I am not interested in it's UNIVERSAL use. Also to be clear we both understand the reason why I can't follow the "install instructions". It would of course be much easier for me if I COULD run plug-ins but architecturally that isn't a viable option given how my Home Assistant has been deployed, and I don't quite understand the resistance to my questioning how I might be able to pull the container so I could benefit from all the VSC/Home Assistant integration you and others have already done.

As we said early on in the IETF, "We all stand on the shoulders of giants", and I'd simply like to just avail myself of the effort you have already invested. I am not looking for support or anything further then some insight on getting this software. I suppose I could clone/fork the repo and set up a build process myself but this all seems a bit like overkill for my rather simple purposes.

Any help or inside into your thinking here would be appreciated.

Thanks again for all the efforts made for thee community, and any consideration you might give to my thoughts above.

--T

**Comment by frenck** [comment]
>  I am not interested in it's UNIVERSAL use. Also to be clear we both understand the reason why I can't follow the "install instructions".

In that case, you are running something that is not the intention of it / supported, meaning you are on your own.

> Any help or inside into your thinking here would be appreciated.

Don't use it.

../Frenck
