### ISSUE TITLE
Renaming a file fails

### ISSUE THREAD

**Issue by mcfrojd** [hassio-addons/addon-vscode#61]
# Problem/Motivation

> When i try to rename a .yaml file i will "jump out" of renaming mode and my typing becomes some kind of search instead.

## Expected behavior

> The file name to be edited until i click "enter"

## Actual behavior

> (What actually happened)

## Steps to reproduce

> I copied a .yaml file and pasted it in my "packages" folder, the if i click F2 or if right mouse click and choose "rename" i get same problem.
Running the latest 1.1.0 addon version

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
![Screenshot McDesktop 2019-11-03 14_25_10](https://user-images.githubusercontent.com/7395495/68085946-c6eb8380-fe46-11e9-8c31-a43a09be2b6f.png)
![Screenshot McDesktop 2019-11-03 14_24_28](https://user-images.githubusercontent.com/7395495/68085947-c6eb8380-fe46-11e9-8c53-0fc4020227b7.png)

Trying to rename "androidtv copy" to "sonoff"

**Comment by mcfrojd** [comment]
Could the new "autosave" of the files cause this problem?
I can see that some bits of the screen "refresh" constantly even if i do nothing.
And the intervall of that seems to be similar to when i see my file beeing "autosaved" when i edit it.

**Comment by frenck** [comment]
This has to do with the behavior of the file tree being changed while you are working on it. This can be any files.

This is an issue with code-server, out of control for the add-on.

you can reduce the issue, by adding more files to ignore for the watcher in your VSCode preferences.
