### ISSUE TITLE
FYI - issue with upstream Update keesschollaart81/vscode-home-assistant to v1.35.1 #606

### ISSUE THREAD

**Issue by regularguy01** [hassio-addons/addon-vscode#610]
# Problem/Motivation

>Update keesschollaart81/vscode-home-assistant to v1.35.1 #606
https://github.com/keesschollaart81/vscode-home-assistant/issues/2602

## Expected behavior

> not see schema errors

## Actual behavior

> Schema Not found

## Steps to reproduce

> Upgrade to 5.5.7 open any Yaml with schema entry like 
sensor:

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
No I revert from back up to 5.5.6

**Comment by sinclairpaul** [comment]
Not sure of the request here, the addon already has that version <https://github.com/hassio-addons/addon-vscode/releases/tag/v5.5.7>  If you have an issue with the extension please log it at the upstream repo.

**Comment by tzagim** [comment]
#611

**Comment by frenck** [comment]
@tzagim That is a different issue, I don't see a reason why you would comment that here. Additionally, you just pasted the issue ID without any context. IMHO that is just spamming to get attention and most certainly not appreciated. Please don't do shit like that.
