### ISSUE TITLE
Studio Code Server 5.5.7 unable to load schema from http://schemas.home-assistant.io/

### ISSUE THREAD

**Issue by TonyM1958** [hassio-addons/addon-vscode#611]
# Problem/Motivation

Error is reported when loading YAML files in HA:

![image](https://user-images.githubusercontent.com/63789168/233723529-0dc82cf1-bb4e-49c1-b6ee-5073371abfd7.png)

## Expected behavior

No error previous to the update today

**Comment by jack5mikemotown** [comment]
Want to confirm I'm seeing the same thing on my end

**Comment by budswarez** [comment]
I have the same problem after the last update.

**Comment by tzagim** [comment]
https://github.com/keesschollaart81/vscode-home-assistant/issues/2602

**Comment by frenck** [comment]
Closing this, as it is an upstream issue with the VSCode extension, not the add-on.

../Frenck

**Comment by excalbian** [comment]
If the add-on would `pin` to version 1.35.0 (before this issue was introduced) it would help those of us using the add-on (since we can't downgrade the extension within VS Code). If that would be considered, I can submit a PR for it.

**Comment by frenck** [comment]
I don't downgrade. If this causes issue for you, downgrade the add-on by restoring a backup.

**Comment by TonyM1958** [comment]
This issue seems to have resolved itself. Not sure exactly what changed, but I've done the following:

+ installed the latest HA update, now on 2023.4.6
+ configured the workspace url and long term access token in VS Code / Home Assistant Config Helper extension

Try these if you have problem?

**Comment by poudenes** [comment]
No extensions installed and have same issue

<img width="300" alt="Scherm­afbeelding 2023-04-23 om 19 06 51" src="https://user-images.githubusercontent.com/4399532/233854120-331a1eb6-c99b-4aa4-a97d-d8385cf43961.png">

**Comment by frenck** [comment]
@poudenes if you run the add-on the extension is installed as built-in. It won't show up in your own custom installed extensions list.

**Comment by TonyM1958** [comment]
Yes, the extension is installed and it's locked on my system so you cannot uninstall or roll it back. Very annoying.

**Comment by bcutter** [comment]
Seems like one has to wait for an upstream fix. Simply ignore that warning messages until than, at least that's what I continue to do for now.

**Comment by frenck** [comment]
> Yes, the extension is installed and it's locked on my system so you cannot uninstall or roll it back. Very annoying.

If you don't like it, please uninstall the addon and use something that better fits you.

Note that Home Assistant asks for backups (enabled by default) on each upgrade, allowing you to roll back to any situation.

../Frenck
