### ISSUE TITLE
Unable to load Schema

### ISSUE THREAD

**Issue by Friedi1970** [hassio-addons/addon-vscode#614]
# Problem/Motivation

Since the last HA update to 2023.4.6 in Studio Code Server add on an error is displayed as soon as I enter the file. The following message is displayed right to the first line in each yaml file I enter:
`Unable to load schema from 'http://schemas.home-assistant.io/integration-automation': No content.`
In file editor there is no error and there is no effect on any automation.

## Expected behavior

No error message.

## Actual behavior

Error message.

## Steps to reproduce

Just enter a yaml file in HA.

## Proposed changes

Please help.

**Comment by frenck** [comment]
Not an add-on issue, but an issue with the vscode extension. 

If you'd looked at the history of this issue tracker or used the search, you'd would have known and saved yourself the effort of creating an issue.

../Frenck

**Comment by poudenes** [comment]
Here no extensions installed. And have same issue

<img width="300" alt="Scherm­afbeelding 2023-04-23 om 19 06 51" src="https://user-images.githubusercontent.com/4399532/233854075-3c87fd2a-5d96-49af-98da-942359f2187a.png">

**Comment by frenck** [comment]
Please read the messages above before you continue posting. Thanks 👍
