### ISSUE TITLE
Unable to load schema from 'http://schemas.home-assistant.io/configuration'

### ISSUE THREAD

**Issue by noticeruby** [hassio-addons/addon-vscode#615]
# Problem/Motivation

> Since 5.5.7 many errors detected in configuration.yaml

![XPS-8940_20230423_115450_firefox](https://user-images.githubusercontent.com/110187529/233852201-bfb3d534-8bee-4579-ab82-ca0a9678e24a.jpg)

**Comment by sinclairpaul** [comment]
#611 
#614 

Please ensure you search issues before creating a new one.

**Comment by primeroz** [comment]
I must be missing something ... all those issues were closed with duplicate of each others :) is there an issue still open to track this ? 

thanks :pray:

**Comment by frenck** [comment]
@primeroz If you read the duplicates, you would have discovered it is not an add-on issue. So no, there is no issue open here to track this.

../Frenck

**Comment by primeroz** [comment]
I did read the duplicates ( or i would not have seen that they were all duplicates of each other ) I guess i missed that statement. 

thank you
