### ISSUE TITLE
Unable to load schema .. No Content showing in every yaml.

### ISSUE THREAD

**Issue by DerEmder** [hassio-addons/addon-vscode#620]
As described in the title.

All is working fine - but the message is as annoying as the window saying 'code-server is accessed in an unsecure way ...' 

Visual Code Server Add-On 5.5.7

Home Assistant 2023.4.6
Supervisor 2023.04.1
Operating System 10.0
Frontend 20230411.1 - latest

**Comment by frenck** [comment]
Please.. check for duplicates before creating new issues...

../Frenck

**Comment by DerEmder** [comment]
Sorry, issue was already closed so I did not see it. Will wait for an update then.
