### ISSUE TITLE
Unable to load schema

### ISSUE THREAD

**Issue by msl2424** [hassio-addons/addon-vscode#622]
# Problem/Motivation

> Getting "Unable to load schema from 'http://schemas.home-assistant.io/configuration': No content." in my configuration.yaml file since updating to Studio Code Server v.5.5.7. Others have reported this same issue in Home Assistant forums. 

<img width="651" alt="Capture" src="https://user-images.githubusercontent.com/101720996/234451733-4ea9e872-cf73-4889-a01b-db6efaa4dae2.PNG">

**Comment by frenck** [comment]
Please search before creating issues....

Thanks!

../Frenck
