### ISSUE TITLE
Problem with V5.5.7 Error in all yaml

### ISSUE THREAD

**Issue by jayjayvm** [hassio-addons/addon-vscode#623]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Empty issue without description, closing.
