### ISSUE TITLE
Problem with V5.5.7, error in all yaml

### ISSUE THREAD

**Issue by jayjayvm** [hassio-addons/addon-vscode#624]
The error is unable to load schemas from 'http://schemas.home-assistant.io/integrations......' no content.

There is already a discussion started in the forum on how to solve this and people are rolling back the latest version to V5.5.6.
So it seems there is a fault in the new code.

**Comment by frenck** [comment]
For the love of god, please check for duplicate before opening issues.

Closing.

**Comment by jayjayvm** [comment]
Waarom zo kort af en aangebrand Frenck, ik mag dan niet tot de goeores van HA behoren gebruik het wel sinds eind NODO ongeveer versie mmm 17.4 weet ik het. 
Het enige wat ik en anderen willen is dat het loopt zoals jullie cracks dat willen, zonder fouten, en gewoon een geweldig produkt.

Zie forum HA

https://community.home-assistant.io/t/unable-to-load-schema-from-http-schemas-home-assistant-io-integration-automation-no-content-yaml-768/557688/17

**Comment by jayjayvm** [comment]
![error templates](https://user-images.githubusercontent.com/130906355/234584271-7d8c8fbb-52fa-458d-936e-f55b1e32cfa3.png)

**Comment by jayjayvm** [comment]
Closed!

**Comment by frenck** [comment]
> Waarom zo kort af en aangebrand Frenck, ik mag dan niet tot de goeores van HA behoren gebruik het wel sinds eind NODO ongeveer versie mmm 17.4 weet ik het. Het enige wat ik en anderen willen is dat het loopt zoals jullie cracks dat willen, zonder fouten, en gewoon een geweldig produkt.
> 
> Zie forum HA
> 
> [community.home-assistant.io/t/unable-to-load-schema-from-http-schemas-home-assistant-io-integration-automation-no-content-yaml-768/557688/17](https://community.home-assistant.io/t/unable-to-load-schema-from-http-schemas-home-assistant-io-integration-automation-no-content-yaml-768/557688/17)

Please use the English language, using a different language violates the Code of conduct of this add-on.

If you don't take the effort to look, don't expect me to take further effort either.

../Frenck
