### ISSUE TITLE
Unable to load schema from ‘http://schemas.home-assistant.io/integration-automation’: No content.

### ISSUE THREAD

**Issue by CBPetrovic** [hassio-addons/addon-vscode#625]
# Problem/Motivation

After upgrading to V 5.5.7, opening any .yaml file to edit results in this message appended to the first executable .yaml statement:
Unable to load schema from ‘http://schemas.home-assistant.io/integration-automation’: No content.

## Expected behavior

No "error' messages in edit window

## Actual behavior
On the first executable statement in a ,yaml file the message below is displayed (simulated line to illustrate message placement):
#
alias: "example"               Unable to load schema from ‘http://schemas.home-assistant.io/integration-automation’: No content.

## Steps to reproduce

Open for edit any .yaml file.

Additional information:
This is the startup log of the 5.5.7 code-server
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[12:08:21] INFO: Configuring timezone (America/New_York)…
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
[12:08:23] INFO: Starting code-server…
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2023-04-21T16:08:26.383Z] info Wrote default config file to ~/.config/code-server/config.yaml
[2023-04-21T16:08:28.205Z] info code-server 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e3
[2023-04-21T16:08:28.208Z] info Using user-data-dir /data/vscode
[2023-04-21T16:08:28.289Z] info Using config file ~/.config/code-server/config.yaml
[2023-04-21T16:08:28.289Z] info HTTP server listening on http://0.0.0.0:1337/
[2023-04-21T16:08:28.290Z] info - Authentication is disabled
[2023-04-21T16:08:28.290Z] info - Not serving HTTPS
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Then, when an edit window is started, the log shows this:
[12:08:33]
[12:08:33] Extension host agent started.
[12:08:34] [172.30.32.2][9a00a88c][ManagementConnection] New connection established.
[12:08:35] [172.30.32.2][465c5cb6][ExtensionHostConnection] New connection established.
File not found: /usr/local/lib/code-server/lib/vscode/extensions/keesschollaart.vscode-home-assistant-1.35.1/jinja-language-configuration.json

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Other system information that may be relevant
Home Assistant 2023.4.6
Supervisor 2023.04.0
Operating System 10.0
Frontend 20230411.1 - latest

**Comment by frenck** [comment]
Please... search before opening issue, you are about the 10th person right now creating an issue in the wrong place AND above all not checking if the issue was already reported.

../Frenck
