### ISSUE TITLE
Unable to load schema from 'http://schemas.home-assistant.io/integration-script': No content

### ISSUE THREAD

**Issue by shawnhaywood** [hassio-addons/addon-vscode#630]
# Problem/Motivation

> (Why the issue was filed)

Started receiving the error message mentioned in the title after upgrading to 5.5.7.  Others have mentioned rolling back to 5.5.6 resolves the issue.  Just sharing in the event this is related to VScode.

I use a separate config file for light groups. In the file I designate a platform: switch, which returns an error, “Unable to load schema from ‘http://schemas.home-assistant.io/integration-light’: No content.” Also occurs in other similar files.

**Comment by frenck** [comment]
Don't worry! 👍
