### ISSUE TITLE
Unable to load schema from 'http://schemas.home-assistant.io/configuration': No content

### ISSUE THREAD

**Issue by UPEngineer** [hassio-addons/addon-vscode#635]
I have just noticed this error popping up at the top of any file I open in Studio Server Code to edit. It says:

Unable to load schema from 'http://schemas.home-assistant.io/configuration': No content

The add-on version is 5.5.7. I am running 2023.5.2 of HA as well. Not sure when the issue cropped up and I have not needed to edit configuration files in a while.

**Comment by tjorim** [comment]
Please look at previous issues.
