### ISSUE TITLE
JS scripts no longer loading in HA config -- Unable to load schema

### ISSUE THREAD

**Issue by ptrembly1966** [hassio-addons/addon-vscode#636]
# Problem/Motivation

> Lovelace card mods that relay on *.js files no longer loading in dashboard

## Expected behavior

> (What you expected to happen)

## Actual behavior

> Error message appears on both dashboard and within configuration.yaml   -- Unable to load schema from 'http://schemas.home-assistant.io/configuration' : No content   Within the dashboard the error is Custom element doesn't exist.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tjorim** [comment]
Please look at previous issues.
