### ISSUE TITLE
Syntax checker doesn't support attribute_templates: in sensor template

### ISSUE THREAD

**Issue by cyberjunky** [hassio-addons/addon-vscode#64]
# Problem/Motivation

Below is valid code supported by Home Assistant and documented on https://www.home-assistant.io/integrations/template/

## Expected behavior

Correct syntax check

## Actual behavior

False syntax check

## Steps to reproduce

```
 - platform: template
    sensors:
      aqi_nitrogen_dioxide:
        friendly_name: Stikstofdioxide
        icon_template: mdi:car
        unit_of_measurement: 'PPM'
        value_template: >
          {{ states.sensor.waqi_bamendaweg_dordrecht.attributes.nitrogen_dioxide }}
        attribute_templates:
          friendly: >-
            {% set nox = states('sensor.aqi_nitrogen_dioxide') | int(-1) %}
            {% if nox > 300 %}
              Schadelijk
            {% elif nox > 200 %}
              Erg slecht
            {% elif nox > 150 %}
              Slecht
            {% elif nox > 100 %}
              Slecht voor gevoelige mensen
            {% elif nox > 50 %}
              Matig
            {% elif nox >= 0 %}
              Goed
            {% else %}
              unknown
            {% endif %}
```
![Screenshot from 2019-11-07 11-51-21](https://user-images.githubusercontent.com/5447161/68383140-5d74b900-0155-11ea-871f-3c3203725608.png)

## Proposed changes

Add/fix support for syntax check of attribute_templates in sensor template

<blockquote><img src="https://www.home-assistant.io/images/default-social.png" width="48" align="right"><div><img src="/images/favicon-192x192.png" height="14"> Home Assistant</div><div><strong><a href="https://www.home-assistant.io/integrations/template/">Template Sensor</a></strong></div><div>Instructions on how to integrate Template Sensors into Home Assistant.</div></blockquote>

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with the vscode extension for Home Assistant. Please report it at that GitHub repository:

<https://github.com/keesschollaart81/vscode-home-assistant>

Thanks! 👍
