### ISSUE TITLE
Config schema not loading

### ISSUE THREAD

**Issue by jpillora** [hassio-addons/addon-vscode#644]
# Problem/Motivation

Config schema not loading

Quesiton: related to this maybe

<img width="443" alt="image" src="https://github.com/hassio-addons/addon-vscode/assets/633843/3d39544f-66c2-47c3-a31a-a5b2f7ba95c9">

?

## Expected behavior

Autocomplete working

## Actual behavior

Error

<img width="807" alt="image" src="https://github.com/hassio-addons/addon-vscode/assets/633843/5c4033c2-00da-4602-b0b9-daea0a761b07">

## Steps to reproduce

* Addons -> Install -> Open web UI -> open configuration file

**Comment by jpillora** [comment]
Update: looks like its related to https://github.com/keesschollaart81/vscode-home-assistant/issues/2602

**Comment by frenck** [comment]
Duplicate number 12 or something, also, just like all the others, in the wrong place.

../Frenck
