### ISSUE TITLE
weather.temperature_unit

### ISSUE THREAD

**Issue by haaino** [hassio-addons/addon-vscode#656]
# Problem/Motivation

When using the latest Studio Code Server 5.6.2 on HA 2023.6.2 I'm getting an error/ warning that there is something wrong in my configuration.yaml file.

I have created my own weather teamplate. And when I set the unit temperature_unit to "°C" the editors warns me that the accepted values are C and F, thus without the " ° ". Were as I do this, remove the °, the HA code validation check fails.

----
weather:
  - platform: template
    unique_id: mijnweerstation
    name: "Mijn weather station"
    condition_template: "{{ states('weather.knmi_knmi') }}"
    temperature_template: "{{ states('sensor.outdoor_temperature') }}"
    temperature_unit: "°C"
------
Best regards,
Haaino

**Comment by 10der** [comment]
Please, fix scheme according to RTFM
https://www.home-assistant.io/integrations/weather.template#temperature_unit

thank you

**Comment by haaino** [comment]
Thank you. I did, and it works.

However: providing the correct input gives a warning. See attached screenshot. Hope this may help :-)

<img width="584" alt="Screenshot 2023-06-30 at 13 48 07" src="https://github.com/hassio-addons/addon-vscode/assets/98317278/f5e9cd1b-2639-490f-8d0a-08cfd70ff775">

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with the vscode extension. Please report the issue upstream, once it is fixed there, the add-on will update.

../Frenck
