### ISSUE TITLE
LIFX Cloud in config

### ISSUE THREAD

**Issue by cableghost** [hassio-addons/addon-vscode#67]
# Problem/Motivation

LIFX Cloud-related data in config throws errors, when in-fact, the code works fine. See attached screenshot.

![lifx_token_errors](https://user-images.githubusercontent.com/5576447/69569801-090a6f80-0f84-11ea-9bf3-8d0ead8f1028.jpg)

## Expected behavior

No errors

## Actual behavior

errors reported

## Steps to reproduce

Follow the steps to add LIFX scenes to HA via the LIFX Cloud documentation.

## Proposed changes

Not sure.

**Comment by frenck** [comment]
That is caused by the Home Assistant config helper VSCode extension.

Please report this issue upstream (the source): <https://github.com/keesschollaart81/vscode-home-assistant>

Thanks! 👍
