### ISSUE TITLE
Addon died after update from 5.7.0 to 5.8.0.

### ISSUE THREAD

**Issue by LordArrin** [hassio-addons/addon-vscode#671]
log:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
parse error: Expected string key before ':' at line 1, column 4
[21:53:36] ERROR: Unknown HTTP error occured
 Add-on: 
 
-----------------------------------------------------------
 Add-on version: 
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[21:53:36] ERROR: Unknown HTTP error occured
 System:   ( / )
 Home Assistant Core: 
 Home Assistant Supervisor: 
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[21:53:36] INFO: Configuring timezone (Europe/Moscow)...
parse error: Expected string key before ':' at line 1, column 4
[21:53:36] ERROR: Unknown HTTP error occured
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
s6-rc: info: service legacy-services: starting
[21:53:37] INFO: Starting code-server...
s6-rc: info: service legacy-services successfully started
[2023-06-30T18:53:38.309Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2023-06-30T18:53:39.040Z] info  code-server 4.14.1 5c199629305a0b935b4388b7db549f77eae82b5a
[2023-06-30T18:53:39.041Z] info  Using user-data-dir /data/vscode
[2023-06-30T18:53:39.061Z] info  Using config file ~/.config/code-server/config.yaml
[2023-06-30T18:53:39.061Z] info  HTTP server listening on http://0.0.0.0:1337/
[2023-06-30T18:53:39.061Z] info    - Authentication is disabled
[2023-06-30T18:53:39.062Z] info    - Not serving HTTPS
[2023-06-30T18:53:39.062Z] info  Session server listening on /data/vscode/code-server-ipc.sock
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service init-mysql: stopping
s6-rc: info: service init-mosquitto: stopping
s6-rc: info: service code-server: stopping
s6-rc: info: service init-mysql successfully stopped
s6-rc: info: service init-mosquitto successfully stopped
[21:53:45] INFO: Service code-server exited with code 0 (by signal 0)
s6-rc: info: service code-server successfully stopped
s6-rc: info: service init-user: stopping
s6-rc: info: service init-code-server: stopping
s6-rc: info: service init-user successfully stopped
s6-rc: info: service init-code-server successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-timezone: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-timezone successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by phoenixswiss** [comment]
Same problem here on to different home assistant installations

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.8.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.6.3
 Home Assistant Supervisor: 2023.06.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[21:04:56] INFO: Configuring timezone (Europe/Zurich)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
[21:04:58] INFO: Starting code-server...
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2023-06-30T19:05:02.894Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2023-06-30T19:05:04.599Z] info  code-server 4.14.1 5c199629305a0b935b4388b7db549f77eae82b5a
[2023-06-30T19:05:04.602Z] info  Using user-data-dir /data/vscode
[2023-06-30T19:05:04.672Z] info  Using config file ~/.config/code-server/config.yaml
[2023-06-30T19:05:04.672Z] info  HTTP server listening on http://0.0.0.0:1337/
[2023-06-30T19:05:04.673Z] info    - Authentication is disabled
[2023-06-30T19:05:04.673Z] info    - Not serving HTTPS
[2023-06-30T19:05:04.673Z] info  Session server listening on /data/vscode/code-server-ipc.sock
```

**Comment by LordArrin** [comment]
Update: on my tablet with android 13 and ha app 2023.6.0-full all works perfectly. Problem stays on latest stable Chrome on pc.

**Comment by sinclairpaul** [comment]
@phoenixswiss Your issue isn't the same I would suggest looking at #666 

@LordArrin 
 The below errors suggest that the supervisor api cannot be reached, please let us know your system details.


```parse error: Expected string key before ':' at line 1, column 4
[21:53:36] ERROR: Unknown HTTP error occured
parse error: Expected string key before ':' at line 1, column 4

**Comment by LordArrin** [comment]
Oracle Virtualbox 7.0.9, Windows 11 25371, 2 core and 2 gb ram in virtual machine. But I repeat - addon crashes when I open it in Chrome on PC, in app all works perfectly.

**Comment by sinclairpaul** [comment]
The errors you linked aren't browser related, currently there is an issue with the Healthcheck, so would suggest you disable the watchdog.

If you do believe it is browser related, please post the output from the dev console.

**Comment by LordArrin** [comment]
I reboot the pc and problem disappears. So, lets deal with it.
