### ISSUE TITLE
Studio Code Server won't start

### ISSUE THREAD

**Issue by Sk1nk** [hassio-addons/addon-vscode#679]
# Problem/Motivation

It doesn't start

## Expected behavior

it should start, when I hit start (or after booting).

## Actual behavior

Seems like it is trying, but after some time the with the circle on top of it, the "start" button reapears in blue

## Steps to reproduce

Install and try to start (might be a problem on my end)
- tried to uninstall and reinstall 
- tried to start on boot
- tried Watchdog switched on and off (read #673 and #666 )

## Log

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.8.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.7.2
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[11:57:30] INFO: Configuring timezone (Europe/Berlin)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
s6-rc: info: service legacy-services: starting
[11:57:33] INFO: Starting code-server...
s6-rc: info: service legacy-services successfully started
[2023-07-19T09:57:35.225Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2023-07-19T09:57:36.777Z] info  code-server 4.14.1 5c199629305a0b935b4388b7db549f77eae82b5a
[2023-07-19T09:57:36.783Z] info  Using user-data-dir /data/vscode
[2023-07-19T09:57:36.861Z] info  Using config file ~/.config/code-server/config.yaml
[2023-07-19T09:57:36.861Z] info  HTTP server listening on http://0.0.0.0:1337/
[2023-07-19T09:57:36.861Z] info    - Authentication is disabled
[2023-07-19T09:57:36.861Z] info    - Not serving HTTPS
[2023-07-19T09:57:36.862Z] info  Session server listening on /data/vscode/code-server-ipc.sock
```

**Comment by frenck** [comment]
It is started according to your logs provided.

**Comment by Sk1nk** [comment]
If I choose it from "Addons" there is only a Start button, if I try to open it from the sidebar, it states, that the addon isn't running and if I wish to start it.
<img width="491" alt="Bildschirmfoto 2023-07-19 um 12 25 49" src="https://github.com/hassio-addons/addon-vscode/assets/13984365/db37aea7-2acb-4203-a41d-0806e959e49f">

**Comment by Sk1nk** [comment]
It didn't, I tried that on multiple times. Between the uninstall and reinstall, with "don't start on boot" to see if I could start it manually, with watchdog turned on and off. I'll do it again but I don't expect it to change anything.

**Comment by frenck** [comment]
🤷 Don't know what to tell you... the add-on logs shows it is started and nothing unusual.

**Comment by Sk1nk** [comment]
It didn't change anything. I have no idea either. Can't use the add-on in this state, even if it is running, I can't access it. You said it is a common issue with HA Supervisor. Is there a way to force him to check again, to reinstall him or anything, that allows me to access the addon?

**Comment by frenck** [comment]
Sorry, I don't have an answer for you.

**Comment by Sk1nk** [comment]
Found this in the supervisor log:
```
23-07-19 12:34:25 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-07-19 12:34:55 WARNING (MainThread) [supervisor.addons.addon] a0d7b954_vscode is already running!
23-07-19 12:36:55 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Studio Code Server to start, took more then 120 seconds
```

**Comment by frenck** [comment]
Sorry, doesn't ring a bell.

**Comment by Sk1nk** [comment]
Thanks for your time! I opened a topic at the official HA-page [here](https://community.home-assistant.io/t/ha-supervisor-doesnt-see-my-add-on-running/593424), maybe some-one over there has an idea.

**Comment by Sk1nk** [comment]
I am not sure what did the job, after I reSTARTed (not rebooted) the PI there was an update. I installed that as well and Studio Code Server is back. Should I close the issue?
