### ISSUE TITLE
Updating crashes my home assistant. 

### ISSUE THREAD

**Issue by spanner3003** [hassio-addons/addon-vscode#692]
# Problem/Motivation

> twice i have tryed updating sourcecode server addon in home assistant and twice its crashed the hole os

## Expected behavior

> update sourcecode server and restart it

## Actual behavior

> crash home assistant

## Steps to reproduce

> tryed to update

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
I cannot do much with "It doesn't work", or, as pointed here just "crashes".

Please provide appropriate logs and a reproduction scenario that anyone could apply.

../Frenck

**Comment by spanner3003** [comment]
Ok sorry never mind i've managed to update it now with the create backup check box, uncheck. I think theere is a problem making backup on my system. I'm running home-assistant on a raspi 3 with sd card and ssd usb, home-assistant is booting of this ssd. Sorry again i'm new to hassio running as an os finding it hard to locate the relivent log files/infomation or conifgure home-assistant to out the relivent log files/infomation.
