### ISSUE TITLE
Update Home Assistent because of one Byte changed in Code?

### ISSUE THREAD

**Issue by wildblue** [hassio-addons/addon-vscode#698]
If i read the changelog, i see only one byte changing. The vetsion number. Is that really necessary? One byte changed to let me have to update my Honeassistant instance every single week again and again? When does this nonsense end?

Or is there probably something behind the curtain, that i can't see yet?

**Comment by frenck** [comment]
Please consult the changelog. In this case esphome was updated. If you don't like this add-on, feel free to uninstall it. Nothing requires you to use it.

../Frenck
