### ISSUE TITLE
I can't log in to my account. 

### ISSUE THREAD

**Issue by Relax-87** [hassio-addons/addon-vscode#699]
Studio Code Server
Current version: 5.10.2 

Home Assistant 2023.9.2
Supervisor 2023.09.2
Operating System 10.5
webui： 20230911.0 - latest

 Click the avatar button and then choose to open the cloud account. The login authorization page cannot pop up.

**Comment by Skylinar** [comment]
same problem on my side, wanted to setup remote access to the vscode instance on HA

**Comment by sinclairpaul** [comment]
The Settings Sync/Cloud Sync is a service provided by Microsoft for use in the Visual Studio suite of products, I would doubt that they would allow access to other applications for it, so it's likely not supported in Code Server.

> same problem on my side, wanted to setup remote access to the vscode instance on HA

It isn't related in anyway to Remote Access.
