### ISSUE TITLE
Can see the add-on in Hass.io tab but can't install it

### ISSUE THREAD

**Issue by Notrial** [hassio-addons/addon-vscode#7]
# Problem/Motivation

Cannot install the add-on.

## Expected behavior

To be installed as any other add-on in the repo.

## Actual behavior

Add-on is greyed-out, with red icon, saying "not available".

## Steps to reproduce

....

## Proposed changes

...
![download](https://user-images.githubusercontent.com/36201754/55067825-b8ebae00-5080-11e9-823a-b917b06f37d9.png)

**Comment by r3mcos3** [comment]
Are you trying to run it on a raspberry pi? Because that's not gonna work

**Comment by Notrial** [comment]
of course I am :( didn't see the restrictions unfortunately...

**Comment by frenck** [comment]
This means your system is not amd64 based but something else (aarch64, amrhf, armv7 or i386), which is not supported by the add-on.

The most obvious case would be Raspberry Pi (armhf/armv7). VSCode cannot run on those architectures yet.
