### ISSUE TITLE
Code-Server Causing CPU Spike

### ISSUE THREAD

**Issue by pldmgg** [hassio-addons/addon-vscode#70]
# Problem/Motivation

> Running VSCode Add-On 1.2.1 on Ubuntu 18.04 Hassio docker (Intel NUC8i3BEK), code-server is spiking the CPU to 100% and keeping it there causing the entire system to slow to a crawl (and requiring a host restart).

## Expected behavior

> No CPU spike

## Actual behavior

> See Problem/Motivation

## Steps to reproduce

> Fresh Hassio docker install on Ubuntu 18.04, add the VSCode Add-On, view the VSCode GUI at least once, wait a few minutes, and code-server will spike the CPU. Verify via `ps aux | grep code-server` or `ps aux | grep server.js`

## Proposed changes

> Right now, I just have to uninstall the VSCode Add-On and edit config files via nano over ssh.

**Comment by ciechompl** [comment]
The same on Hassio installed as virtual machine running on vmware. Every time when I start VSCode  entire systems hangs with 100% CPU.
Everything if fully updated to the latest versions.

**Comment by mihma** [comment]
Same for Doker on Ubuntu, hassio with VS Code ver. 1.2.2  as add-on. CPU spikes to 100%.

**Comment by Kedryn** [comment]
SAme here... a bit after opening VSS, the system stop responding in a timely fashion, then  the only thing i can do is stopping the vscode docker container via ssh (and it takes nearly 10 minutes of waiting the ssh login to popup dodging connection timeouts)
Ubuntu with hassio, everything updated, but started doing that several versions ago.

**Comment by frenck** [comment]
VSCode is heavy and will use 100% CPU at start (indexing for example).

**Comment by frenck** [comment]
I can see some spikes at first start, but not extreme or worry some for me personally.

Nevertheless, add-ons wrap existing applications, in this code-server.

From an add-on perspective, there is nothing I can do about this.
