### ISSUE TITLE
Back button do not working on iPhone

### ISSUE THREAD

**Issue by L0bit0** [hassio-addons/addon-vscode#700]
Hi

I had to use Code editor on my phone and since then back button do not work anymore.

Additional info:
- I have an iPhone SE, IOS 16.1.1
- Home assistant versions and Add On are up-to-date (HA2023.9.2, Studio Code Server 5.10.2)
- I tried restarting Server and iPhone app
- I tried restarting the iPhone
- Every time I start Home Assistant App on the phone, i come back to Studio Code Server, so now I can not do anything with Home Assistant on my phone now.

Do you know how to fix this on the iPhone? Or at least how I can "reset"home Assistant on the iPhone to do not start directly on the Stdio Code screen?

Thanks!

**Comment by sinclairpaul** [comment]
There isn't anything the addon can do to fix this, I would suggest logging your issue at <https://github.com/home-assistant/iOS>

**Comment by L0bit0** [comment]
@sinclairpaul thank for the info, I will also open this there, but can you elaborate a bit more to property understand?

My thoughts:
- This is the only button failing on this add-on (as far as I know...) any other buttons (menu, close, tabs...) works.
- It is only failing on iOS (web works property)
- Not other add on have this issue

so for me is an issue on the code this button has it and compatibility with Home Assistant app.

thansk!
