### ISSUE TITLE
Explorer Missing Folder?

### ISSUE THREAD

**Issue by efaden** [hassio-addons/addon-vscode#710]
# Problem/Motivation

About 50 percent of the time now when I launch VS Code in the browser I am not getting a "folders" list in the Explorer.

## Expected behavior

It should open the folders.

## Actual behavior

The folders seem to be totally missing.

## Steps to reproduce

Unclear why/when it happens.

![Screenshot 2023-10-03 at 3 21 56 PM](https://github.com/hassio-addons/addon-vscode/assets/12599300/3ba884f1-24ca-4d57-8163-c7b77c9ae58b)

**Comment by blindguynar** [comment]
Same.  Not sure if it's the last update, but now no directory structure is shown.  Can't find a setting for this either.

**Comment by panhans** [comment]
Same problem here. I just reinstalled the add on. For now everything is fine again. Will report back if the issue appears again.
