### ISSUE TITLE
Add relevant keywords to language identifier

### ISSUE THREAD

**Issue by ThomDietrich** [hassio-addons/addon-vscode#716]
# Problem/Motivation

Please don't be mad at me. This is rather a silly suggestion. Would appreciate your consideration if you have no relevant counter-arguments.

## Expected behavior

The best language mode to select for home assistant configuration files is "Home Assistant", obviously.

![image](https://github.com/hassio-addons/addon-vscode/assets/2870104/4c6c9548-6436-48f0-b92e-8f69dd135e2c)

## Actual behavior

However, that is not the first thing that comes to mind. When I edit text files with home assistant syntax (temporary files, templates or README in dev) first thing that comes to mind is "must be some extended yaml syntax with jinja support".

![image](https://github.com/hassio-addons/addon-vscode/assets/2870104/ba765411-da6c-454e-84e6-2af15afa228b)

## Proposed changes

Please consider renaming the language to something like "Home Assistant YAML+jinja (home-assistant)" or similar. Thanks

**Comment by frenck** [comment]
Thanks for the suggest, however, I disagree, thus closing 👍 

../Frenck

**Comment by ThomDietrich** [comment]
No surprise here 😔 This would have been an easy improvement but I guess "I disagree" is your argument against everything. Thanks for the reminder that I decided to halt contributions wherever you are involved 😇 Cheers

**Comment by frenck** [comment]
>  This would have been an easy improvement

It would not... ad this repo doesn't handle that... 🙄 

>  Thanks for the reminder that I decided to halt contributions wherever you are involved 😇 

I don't think that is called for at all. Let me ban you from this org, just to make sure.

../Frenck
