### ISSUE TITLE
VSCode Addon Won't Start

### ISSUE THREAD

**Issue by tmorris0221** [hassio-addons/addon-vscode#724]
# Problem/Motivation
VS Code addon will not start
> (Why the issue was filed)

## Expected behavior
code server add on starting upon clicking start
> (What you expected to happen)

## Actual behavior
Nothing
> (What actually happened)
startup times out
## Steps to reproduce
Install Add on, click start
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Here are logs from both the AddOn and HA Supervisor:

**Add-On Logs:**

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.12.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.0  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.10.3
 Home Assistant Supervisor: 2023.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[13:01:24] INFO: Configuring timezone (America/Chicago)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
[13:01:27] INFO: Starting code-server...
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2023-10-19T18:01:28.755Z] info  Wrote default config file to /root/.config/code-server/config.yaml
[2023-10-19T18:01:30.018Z] info  code-server 4.17.1 2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa
[2023-10-19T18:01:30.021Z] info  Using user-data-dir /data/vscode
[2023-10-19T18:01:30.053Z] info  Using config file /root/.config/code-server/config.yaml
[2023-10-19T18:01:30.054Z] info  HTTP server listening on http://0.0.0.0:1337/
[2023-10-19T18:01:30.054Z] info    - Authentication is disabled
[2023-10-19T18:01:30.054Z] info    - Not serving HTTPS
[2023-10-19T18:01:30.055Z] info  Session server listening on /data/vscode/code-server-ipc.sock

**HA Supervisor Logs:**

23-10-19 13:03:22 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Studio Code Server to start, took more then 120 seconds

23-10-19 13:08:34 WARNING (MainThread) [supervisor.addons.addon] a0d7b954_vscode is already running!
23-10-19 13:10:34 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Studio Code Server to start, took more then 120 seconds
23-10-19 13:11:48 WARNING (MainThread) [supervisor.addons.addon] a0d7b954_vscode is already running!
23-10-19 13:12:15 WARNING (MainThread) [supervisor.addons.addon] a0d7b954_vscode is already running!

23-10-19 13:13:48 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Studio Code Server to start, took more then 120 seconds
23-10-19 13:14:15 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Studio Code Server to start, took more then 120 seconds
23-10-19 13:15:48 WARNING (MainThread) [supervisor.addons.addon] a0d7b954_vscode is already running!

23-10-19 13:17:48 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Studio Code Server to start, took more then 120 seconds
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
23-10-19 13:20:30 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-10-19 13:21:56 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token

23-10-19 13:27:10 WARNING (MainThread) [supervisor.addons.addon] a0d7b954_vscode is already running!

23-10-19 13:29:10 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Studio Code Server to start, took more then 120 seconds
23-10-19 13:32:16 WARNING (MainThread) [supervisor.addons.addon] a0d7b954_vscode is already running!

23-10-19 13:34:16 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Studio Code Server to start, took more then 120 seconds
23-10-19 13:34:31 WARNING (MainThread) [supervisor.addons.addon] a0d7b954_vscode is already running!
23-10-19 13:36:31 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Studio Code Server to start, took more then 120 seconds

**Comment by frenck** [comment]
The add-on is running perfectly fine:

```
s6-rc: info: service legacy-services successfully started
[2023-10-27T09:21:41.566Z] info Wrote default config file to /root/.config/code-server/config.yaml
[2023-10-27T09:21:43.087Z] info code-server 4.18.0 d7a2b4936af1bfd80cb96f2567af68badc2325e3
[2023-10-27T09:21:43.090Z] info Using user-data-dir /data/vscode
[2023-10-27T09:21:43.137Z] info Using config file /root/.config/code-server/config.yaml
[2023-10-27T09:21:43.137Z] info HTTP server listening on http://0.0.0.0:1337/
[2023-10-27T09:21:43.137Z] info - Authentication is disabled
[2023-10-27T09:21:43.138Z] info - Not serving HTTPS
[2023-10-27T09:21:43.138Z] info Session server listening on /data/vscode/code-server-ipc.sock
```

This is not something add-on related.

**Comment by JHPWBN** [comment]
yet, when I try to open it from the Side Bar I get the massage that it is not running.

Same issue with Home Assistant Add-on: File editor

Where to go from here?

**Comment by frenck** [comment]
> Same issue with Home Assistant Add-on: File editor

Right, it is not related to the add-ons themselves.

> Where to go from here?

HA community?

../Frenck

**Comment by JHPWBN** [comment]
Thxs, did some research there and found suggestion to reboot (not restart) the system.
Both add-ons work now.

Groetjes,
Joop

On 27. Oct 2023, at 11:41, Franck Nijhof ***@***.***> wrote:


Same issue with Home Assistant Add-on: File editor

Right, it is not related to the add-ons themselves.

Where to go from here?

HA community?

../Frenck
