### ISSUE TITLE
Delay reconnecting when Websocket connection fails

### ISSUE THREAD

**Issue by michaelarnauts** [hassio-addons/addon-vscode#73]
# Problem/Motivation

When updating Home Assistant, it goes down, but vscode is trying to reconnect to Home Assistant. There seems to be no delay between the reconnection attempts. Causing high CPU load during Home Assistant downtime.

## Expected behavior

Sleep a second or so between reconnection attempts.

## Actual behavior

```
20-01-17 18:34:47 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_vscode
20-01-17 18:34:47 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
20-01-17 18:34:47 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
20-01-17 18:34:47 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_vscode
20-01-17 18:34:47 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
20-01-17 18:34:47 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
20-01-17 18:34:47 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_vscode
...
```
Actually:
```
# docker logs hassio_supervisor 2>&1 | grep "18:34:47" | grep "WebSocket access" | wc -l
122 
```
It's trying to connect 122 times per second.

## Steps to reproduce

1. Run this addon.
2. Update Home Assistant.

## Proposed changes

Add a `time.sleep(1)` between reconnection attempts.

**Comment by frenck** [comment]
Add-ons wrap existing applications. This is powered by code-server. I cannot change the working of code-server. If you think the reconnect logic is to accessive, I would suggest filing an issue with code-server.

**Comment by michaelarnauts** [comment]
@frenck Okay, can you point me to the right repository then?

**Comment by frenck** [comment]
Actually, I think this is not caused by VSCode
it does not access the API by itself.

I think this is caused by the Home Assistant configuration helper vscode extension.

**Comment by michaelarnauts** [comment]
This repository? https://github.com/keesschollaart81/vscode-home-assistant

**Comment by frenck** [comment]
Yep
