### ISSUE TITLE
Addon is not starting

### ISSUE THREAD

**Issue by Str00pwafel** [hassio-addons/addon-vscode#733]
# Problem/Motivation

> Problem started after latest update to 5.14

## Expected behavior

> I'd expect it to start like normal

## Actual behavior

> Not starting

## Steps to reproduce

> Not sure, update? 

## Proposed changes

I will share the current logs;

 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.14.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.11.1
 Home Assistant Supervisor: 2023.11.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[11:16:29] INFO: Configuring timezone (Europe/Amsterdam)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
/etc/s6-overlay/s6-rc.d/init-user/run: line 79: unexpected EOF while looking for matching `"'
s6-rc: warning: unable to start service init-user: command exited 2
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-mosquitto successfully started
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service init-mysql: stopping
s6-rc: info: service init-mosquitto: stopping
s6-rc: info: service init-code-server: stopping
s6-rc: info: service init-mysql successfully stopped
s6-rc: info: service init-mosquitto successfully stopped
s6-rc: info: service init-code-server successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-timezone: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-timezone successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by frenck** [comment]
Shit! I released the wrong add-on 😢 

I meant to release the ssh add-on, I have to many tabs open 😟 

Going to fix it right away!

../Frenck

**Comment by frenck** [comment]
Shipped: https://github.com/hassio-addons/addon-vscode/releases/tag/v5.14.1

With a fix, should be available for update on your system in a few minutes after this message.

Sorry about that; I didn't mean to release that previous version yet, as it was untested (clearly). I've confirmed v5.14.1 to work on both amd64 & aarch64 architectures.

../Frenck

**Comment by Str00pwafel** [comment]
All good, thank you! Things like these happen, quick followup with a fix! Much appreciated.
