### ISSUE TITLE
Visual artifact?

### ISSUE THREAD

**Issue by terryhonn** [hassio-addons/addon-vscode#735]
# Problem/Motivation

> Strange vertical lines in editor pane

## Expected behavior

> No strange vertical lines in editor pane

## Actual behavior

> There are strange vertical lines in the editor pane

## Steps to reproduce

> Open a file in the editor pane

## Proposed changes

I'm a new user of the Visual Studio Code addon in HA, but use it as a stand alone app otherwise. I've never seen these lines in the editor window before, but I'm not sure if they have a purpose and can be turned off, or if something else is going on. I've tried uninstalling and reinstalling, restarting, etc., the addon, without change.

![image](https://github.com/hassio-addons/addon-vscode/assets/8404272/ccc3a25b-95e6-44ee-8130-d236da61655e)

**Comment by sinclairpaul** [comment]
They are rulers, you can find the Config for them under Editor:Rulers.

**Comment by terryhonn** [comment]
Rulers! Of course!  Thank you!
