### ISSUE TITLE
Studio Code wont start or uninstall

### ISSUE THREAD

**Issue by C-Kuro833** [hassio-addons/addon-vscode#737]
# Problem/Motivation

> Studio Code wont start or uninstall

## Expected behavior

> Studio Code to start 

## Actual behavior

> when pressing start or uninstall this error message comes: ("Another job is running for job group container_addon_a0d7b954_vscode"), 
the Log says: 
("Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 13:35:06 (3 occurrences)
Last logged: 13:35:27

>Failed to to call /addons/a0d7b954_vscode/start - Another job is running for job group container_addon_a0d7b954_vscode
>Failed to to call /addons/a0d7b954_vscode/uninstall - Another job is running for job group container_addon_a0d7b954_vscode")

## Steps to reproduce

> after installation this error occured.

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with the Home Assistant system/Supervisor (which raises this error as well).

From an add-on perspective there is nothing I can do. Please report your issue upstream with the Home Assistant project.

../Frenck
