### ISSUE TITLE
Update message - when trying to update, results in error

### ISSUE THREAD

**Issue by bouwew** [hassio-addons/addon-vscode#74]
# Problem/Motivation

I can see an update message when using Visual Studio Code in HA.
When I press the update button I get `Unable to write file (Error: unexpected end of file)`.
Is this supposed to happen?

**Comment by rpitera** [comment]
I get the same.  I would think this is because we don't have rights to the container and the add on itself simply needs to be updated.  It's annoying, but I just click later and ignore it.  Frenck will get to it soon I'm sure, probably been busy with the new job and the last release.

**Comment by sinclairpaul** [comment]
You should be able to change the update mode in your user preferences:

![image](https://user-images.githubusercontent.com/24625998/73128833-78600800-3fa3-11ea-90da-d739031ebba8.png)

May be worth changing this in the user config json for a default install?

**Comment by frenck** [comment]
We should disable this by default in the add-on, there is no reason for it to be enabled.

**Comment by frenck** [comment]
@rpitera The update is delayed because I'm testing against ARM support right now.
