### ISSUE TITLE
config_path

### ISSUE THREAD

**Issue by wernerhp** [hassio-addons/addon-vscode#742]
# Problem/Motivation
Setting `config_path: /root` doesn't work.  After restarting the setting is missing again and Studio Code still only shows `/config`.

Addon config moved out of `/config` to `/addon_config` but this can now not be accessed.

## Expected behavior

The setting to be persisted.

## Actual behavior

The setting was not persisted.

**Comment by sinclairpaul** [comment]
I believe what you are experiencing is a change in that the app remembers the last opened path.  You can select File, Open Folder, Select what you want, then restart and see if it persists.

**Comment by wernerhp** [comment]
Amazing!  Legend!
