### ISSUE TITLE
VS Code can't be installed on standard Raspberry Pie 4 due to incompatible CPU or OS

### ISSUE THREAD

**Issue by magune** [hassio-addons/addon-vscode#752]
I tried to install the VSCode add-on on a standard Raspberry Pie 4 with all HA software stack updated as of December 2023. It refuses due to "incompatible CPU or OS". I have had this problem a very long time, across many HA OS updates. Any ideas?

**Comment by HWiese1980** [comment]
Confirmed.

No idea what to do about it, other than asking the maintainers to make it compatible. VSCode itself should not be the problem, it runs on RasPi 4. 

So please, dear maintainers, with a cherry on top, take measures to make it compatible!

**Comment by HWiese1980** [comment]
An alternative might be a custom VSCodium build. But there's no addon for that.

**Comment by frenck** [comment]
It means you are running a 32-bits OS on your Raspberry Pi. This add-on requires a 64-bits OS.

Make a backup, install the latest 64-bits version of the Hone Assistant OS (as documented on their website), and restore your backup.

Now you can use and install this add-on.

Please note: the 32-bits version is not recommended and also no longer advertised or documented by the Home Assistant project.

../Frenck
