### ISSUE TITLE
vscode addon workspace folders don't load (most of the time) and needs addon restart

### ISSUE THREAD

**Issue by vaibhav2912** [hassio-addons/addon-vscode#753]
# Problem/Motivation

I have a custom workspace I created with /config folder and addon_configs/a0d7b954_appdaemon/ folder open in it. When I open the vscode from sidebar, most of the time the folders don't load properly. I have to close the workspace and open it again for it to work or sometimes I have to restart the addon. I see the clock icon on workspace which is a symbol for "still working on it" but this never goes away.

![image](https://github.com/hassio-addons/addon-vscode/assets/20019445/ae041ced-6439-424b-9292-b14babf7f4a0)

## Expected behavior

All the open folders in workspace load correctly.

## Actual behavior

Workspace folders don't load.

## Steps to reproduce

Happens randomly. I haven't been able to reproduce this intentionally.

**Comment by vaibhav2912** [comment]
Still a problem. I haven't found workaround or a fix.

**Comment by illuzn** [comment]
What hardware is your studio code server instance hosted on? VS Code is very resource hungry and I've found it runs out of memory very quickly with large workspaces on my RPi4 (causing this exact issue) and also explaining why its intermittent (depends what other addons are running etc and much more reliable with a fresh restart of the OS).

**Comment by vaibhav2912** [comment]
Mine is running on old laptop that has i5 processor (I forgot exactly which one) + 8GB of RAM.

Memory usage never goes above ~20%.
![image](https://github.com/hassio-addons/addon-vscode/assets/20019445/a97e9f19-f414-45fd-95c0-1cc466862ecb)
