### ISSUE TITLE
Can't install Visual Studio Addon

### ISSUE THREAD

**Issue by valantur** [hassio-addons/addon-vscode#76]
I get this error when installing the add-on:

<img width="1118" alt="Screen Shot 2020-01-31 at 11 07 53 AM" src="https://user-images.githubusercontent.com/2516392/73567079-6c000300-441a-11ea-87cf-1efbdf417e0a.png">

Any ideas how to fix this? Thanks!

**Comment by sinclairpaul** [comment]
Docker throwing a 404 is generally, name resolution (i.e. it cannot locate the image to download) or disk space (in that it doesn't have enough room to download and launch).

Please validate both of these, it's not an issue with the addon itself.

**Comment by valantur** [comment]
> Docker throwing a 404 is generally, name resolution (i.e. it cannot locate the image to download) or disk space (in that it doesn't have enough room to download and launch).
> 
> Please validate both of these, it's not an issue with the addon itself.

Right on man! not enough disk space. Thanks!
