### ISSUE TITLE
High CPU and MEM usage

### ISSUE THREAD

**Issue by bassho** [hassio-addons/addon-vscode#761]
# Problem/Motivation

Studio Code Server is using a very high CPU and RAM usage, which causes my Home Assistant VM running on very high resources.

## Expected behavior

Way lower usage, definitely when theres no VS oppen.

## Actual behavior

High resource usage (90% CPU and 90% (3G) mem total, which after a reboot is back to 6% CPU and 1G mem.

## Steps to reproduce

No idea. Seems to be happening after 2-3 days random.

## Proposed changes

![image](https://github.com/hassio-addons/addon-vscode/assets/27589134/a7898411-a7aa-433e-a24f-14c9c84e915e)

After restart:

**Comment by sinclairpaul** [comment]
The container is running, which means the application will be running file watchers etc.  My suggestion would be to stop the addon when not in use.

**Comment by bassho** [comment]
> The container is running, which means the application will be running file watchers etc. My suggestion would be to stop the addon when not in use.

Ok, if thats the fix then ill close this case.
