### ISSUE TITLE
High cpu load

### ISSUE THREAD

**Issue by JanosBerke** [hassio-addons/addon-vscode#766]
I see high cpu load since the last update. It was not using too much cpu before. After the start of this addon, cpu usage goes up to 80-90% without opening anything, just loading the web interface. High cpu usage remains after closing the web interface and keep running it.

**Comment by jnnsrctr** [comment]
Having the same issue. Raspberry Pi 4 reports very high RAM usage, too. Device gets very toasty. Have to disable the addon until fixed.

**Comment by mplinuxgeek** [comment]
Similar issue, seeing CPU and mem increasing while addon is running, once it gets into the 90's the system starts becoming unresponsive.

**Comment by DR-Apples** [comment]
I also experience the same problem. By opening VSCode, the CPU load of the addon goes to 95% + percent, to the point Home Assistant almost freezes. Using Raspberry Pi 4b 8 GB ram

**Comment by EsOmEs** [comment]
I do have the same issue. RPi5 8Gb at 90% CPU and 80% ram usage just for this AddOn. Very sad as I like the funktionality

**Comment by Ftown14** [comment]
Same issue as #565  that has been an issue for some since Jan 2023, mine started about 4 months ago. Have to keep it disabled or Pi will overhear and shutdown

**Comment by namadori** [comment]
![studio code](https://github.com/hassio-addons/addon-vscode/assets/10942270/42c9e2fe-96c9-4697-9efc-a65c4f474466)

Same here, the only workaround is to start the addon, do the changes and then stop it again.
Any alternatives out there?

**Comment by JulianBerkner** [comment]
Hi, just found this reddit thread, where there seems to be a solution. I did not try it in any way, just posting it to inform you.
https://www.reddit.com/r/homeassistant/comments/1amue9p/vscode_addon_burning_the_cpu_even_when_closed/

**Comment by Ftown14** [comment]
I tried that fix previously and it did not work for me, I tried again just to be sure. This led me to see what I could figure out. Go see my post in the issue thread #https://github.com/hassio-addons/addon-vscode/issues/565#issuecomment-1937079817 

This 100% fixed the problem for me, but creates it's own with the loss of features.
