### ISSUE TITLE
Visual Studio Code addon not available

### ISSUE THREAD

**Issue by masip85** [hassio-addons/addon-vscode#77]
# Problem/Motivation

Add-On not available

## Expected behavior

Being able to install it from Homeassistant in HassIO

## Actual behavior

A message appear in add-on HA menu:
This add-on is not available on your system.
 and install icon is not available

## Steps to reproduce

I don't have any idea, does it happen to everybody in which circumstances?

## Proposed changes

Add to the docs in which kind of system or circumstances is not available.

**Comment by sinclairpaul** [comment]
Did you look at the known issues?, will assume you have an ARM based system.

https://github.com/hassio-addons/addon-vscode#known-issues-and-limitations

**Comment by masip85** [comment]
Ok. I thought there would be a pre-requirements part. Normally known issues is left for exceptional cases.  rPI. I guess is one of the most common HA platforms used.

Or maybe I am wrong.

Thanks

**Comment by frenck** [comment]
It is listed as one of the first things right under the title:

![image](https://user-images.githubusercontent.com/195327/73617637-12b5f080-4621-11ea-973a-e4b49b37faaf.png)

Also added to that section referenced, to reduce the number of questions we get on this.

Secondly, if you looked at the closed issues or the Community forums topic for this add-on, you would have read it multiple times as well.

The add-on is not available for ARM devices, include the Pi.

**Comment by masip85** [comment]
Thanks. My eyes had never stopped at this labels. I didn't even know requirements could be done with this tags. Everyday something new can be learned :)

By the way, at community search results of:
vscode add-on
vscode add-on install
I did not found something related.
