### ISSUE TITLE
Auto-completion for keywords and parameters not working with VS Code v5.10.0

### ISSUE THREAD

**Issue by vumaddibly** [hassio-addons/addon-vscode#770]
# Problem/Motivation

Prior to Nov 2023 the HA VS Code Add-on used to provide auto-completion for keywords (eg alias, description, trigger, platform and mode), parameters (eg state, numeric_state, single) and entity ids/names. Today the only completion that works is for entity ids/names.

## Expected behavior

Auto-completion to work for keywords, parameters and entity ids/names.

## Actual behavior

When starting to write a new automation the pop-up list of potential auto-completions does not correspond to the current context (see screenshots). 

## Steps to reproduce

Start to write a new automation and type a single hypen, as though you were about to type '- alias: '. You will be presented with a list of completions that make no sense. Similar problems are experienced as each new keyword is entered.

## Proposed changes

Restore the pre-Nov 2023 functionality. Removing and re-installing the add-on does not affect the behaviour.
![Screenshot 2024-01-22 at 15 55 36](https://github.com/hassio-addons/addon-vscode/assets/95146141/f758dc1a-8509-4aea-a060-40e116fa2982)
![Screenshot 2024-01-22 at 15 55 12](https://github.com/hassio-addons/addon-vscode/assets/95146141/14a4ec21-be2d-48e4-86ba-c8359bfce95f)

**Comment by vumaddibly** [comment]
Several other people are experiencing the same problem due to the number of 'thumbs up' comments. I have repeatedly re-installed the VS Code Add-on but the problem remains.

**Comment by vumaddibly** [comment]
@frenck, would have a few minutes to look at this please? Despite removing and re-installing the VS Code Add-on several times the problem remains, ie the only auto-completions that work for me are entity names. Auto-completion for keywords and parameters is broken. I think I may have been the cause of the problem as I remember there being a .vscode-xxxxxx file or folder under /config and it looked to be a left-over temporary file and I deleted it - clearly it wasn't! It's strange that a re-install doesn't resolve the problem.
Thanks.

**Comment by nicolaufg** [comment]
> I think I may have been the cause of the problem as I remember there being a .vscode-xxxxxx file

I also see this problem and I never deleted such file or anything similar.

**Comment by vumaddibly** [comment]
@nicolaufg, I'm wondering what the common factor might be 🤔  Which browser(s) and OS(es) are you using? I only have Macs and iOS mobile devices to test with.

**Comment by nicolaufg** [comment]
> @nicolaufg, I'm wondering what the common factor might be 🤔 Which browser(s) and OS(es) are you using? I only have Macs and iOS mobile devices to test with.

I'm using Linux Mint 20.2; not sure the role of the browser here, but I use Brave. Hass is running dockerised on a Tinker 2 (Debian 10).

**Comment by vumaddibly** [comment]
The problem persists. I uninstalled the Add-on, upgraded HA Core from 2024.4.2 -> 2024.4.3 and then reinstalled the VSCode Add-on - no change

**Comment by vumaddibly** [comment]
> There hasn't been any activity on this issue recently, so we clean up some of the older and inactive issues. Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by leaving a comment 👍 This issue has now been marked as stale and will be closed if no further activity occurs. Thanks!

This issue is still there with Core 2024.5.3, OS 12.3 and Frontend 20240501.1

**Comment by Bartsz** [comment]
Same here, but it doesn't work for neither VS Code Server and regular VS Code connected to HA

HA OS 12.3
HA Core 2024.6.3
Running in VM VirtualBox

**Comment by Perchycs** [comment]
Same thing here running latest version of supervised HA OS.

**Comment by shimscharf** [comment]
same here using latest version of supervised HA OS

**Comment by vumaddibly** [comment]
This issue is not stale. I suffered a HDD failure recently, after which I did a fresh install and backup. I have no updates showing but the problem persists.

**Comment by shimscharf** [comment]
Issue persists

**Comment by shimscharf** [comment]
Still persists

**Comment by frenck** [comment]
Fix in [v5.16.0](https://github.com/hassio-addons/addon-vscode/releases/tag/v5.16.0)

**Comment by vumaddibly** [comment]
@frenck, many thanks for your work fixing this. Editing YAML is now soooo much easier! 👏 👏 👏
