### ISSUE TITLE
Does this offer an option to disable telemetry?

### ISSUE THREAD

**Issue by iamalsonothere** [hassio-addons/addon-vscode#774]
Preety much the title

Can the code server telemetey be completely disabled?

**Comment by frenck** [comment]
Even better, it disables it by default, and has no option to enable it.

See:

https://github.com/hassio-addons/addon-vscode/blob/6db56e8fcf66d5b52fd1b272dab6eabba2aaa93c/vscode/rootfs/etc/s6-overlay/s6-rc.d/code-server/run#L21
