### ISSUE TITLE
Pasted code indents not handled properly

### ISSUE THREAD

**Issue by macdroid53** [hassio-addons/addon-vscode#775]
# Problem/Motivation

> Installed the addon recently. When I paste properly indented lines, the indents are multiplied. For example, 2 spaces are made 4, 4 spaces are made 8, etc.
This happens when accessing HA in Firefox from a Debian 12/XFCE PC.
Accessing with Firefox from a PC with Ubuntu/GNOME or Manjaro/Plasma the indent works fine.

## Expected behavior

> When I paste lines they should have the same indentation as the source lines.
This should work the same from any PC and browser.

## Actual behavior

> See above

## Steps to reproduce

> Copy and paste from one file to another.

## Proposed changes

> Since the tab/indent settings in vscode don't seem to address the issue. I have no idea how to correct this on the Debian PC. Any ideas would be greatly appreciated.

**Comment by tjorim** [comment]
This is out of scope for the add-on, nothing we can do about it as we just package code-server in a nice add-on. It's either an issue with [code-server](https://github.com/coder/code-server) or (as you already concluded) the browser/OS combo.
