### ISSUE TITLE
Studio Code server will not load anymore.... Gets File not found error Help? 

### ISSUE THREAD

**Issue by JAFC-BandO** [hassio-addons/addon-vscode#776]
# Problem/Motivation

> Studio Code server is just stuck on black screen when I try to open 
Heres the Log I have from SCS

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.15.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.1.6
 Home Assistant Supervisor: 2023.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[14:47:49] INFO: Configuring timezone (Europe/Copenhagen)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
s6-rc: info: service legacy-services: starting
[14:47:52] INFO: Starting code-server...
s6-rc: info: service legacy-services successfully started
[2024-02-02T13:47:55.285Z] info  Wrote default config file to /root/.config/code-server/config.yaml
[2024-02-02T13:47:57.282Z] info  code-server 4.20.0 d0215eca8804d0be5d3551c39404e336032c3141
[2024-02-02T13:47:57.288Z] info  Using user-data-dir /data/vscode
[2024-02-02T13:47:57.373Z] info  Using config file /root/.config/code-server/config.yaml
[2024-02-02T13:47:57.374Z] info  HTTP server listening on http://0.0.0.0:1337/
[2024-02-02T13:47:57.374Z] info    - Authentication is disabled
[2024-02-02T13:47:57.375Z] info    - Not serving HTTPS
[2024-02-02T13:47:57.375Z] info  Session server listening on /data/vscode/code-server-ipc.sock
[14:48:17] 

[14:48:17] Extension host agent started.
File not found: /usr/local/lib/code-server/lib/vscode/out/vsda.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vsda_bg.wasm
[14:51:47] [xxxx][b9c03940][ManagementConnection] New connection established.
[14:51:48] [xxxx][2a38547d][ExtensionHostConnection] New connection established.
[14:51:56] [xxxx][2a38547d][ExtensionHostConnection] <570> Launched Extension Host Process.
File not found: /usr/local/lib/code-server/lib/vscode/extensions/keesschollaart.vscode-home-assistant-1.39.0/jinja-language-configuration.json`

## Expected behavior

> (It would load as expected)

## Actual behavior

> Studio code server is just stuck on the loading screen

## Steps to reproduce

> N/A Open Studio code server via HA, and it never loads, I just get the error that File not found:

**Comment by boby51** [comment]
I Have simular problem:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.15.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.2.2
 Home Assistant Supervisor: 2024.02.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[19:36:03] INFO: Configuring timezone (Australia/Sydney)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
s6-rc: info: service legacy-services: starting
[19:36:06] INFO: Starting code-server...
s6-rc: info: service legacy-services successfully started
[2024-02-25T08:36:07.652Z] info  Wrote default config file to /root/.config/code-server/config.yaml
[2024-02-25T08:36:08.955Z] info  code-server 4.20.0 d0215eca8804d0be5d3551c39404e336032c3141
[2024-02-25T08:36:08.960Z] info  Using user-data-dir /data/vscode
[2024-02-25T08:36:08.994Z] info  Using config file /root/.config/code-server/config.yaml
[2024-02-25T08:36:08.994Z] info  HTTP server listening on http://0.0.0.0:1337/
[2024-02-25T08:36:08.995Z] info    - Authentication is disabled
[2024-02-25T08:36:08.995Z] info    - Not serving HTTPS
[2024-02-25T08:36:08.995Z] info  Session server listening on /data/vscode/code-server-ipc.sock

**Comment by stefanes** [comment]
I see the same or a similar issue. The addon starts up just fine, no errors in the log until I open the web interface:

```
[15:15:24] Extension host agent started.
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/browser/browser.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/buffer.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/browser/window.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/event.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/marshalling.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/lifecycle.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/uri.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/strings.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/path.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/platform/window/common/window.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/network.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/platform/product/common/product.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vs/base/common/resources.js
```
