### ISSUE TITLE
401 - Unauthorized

### ISSUE THREAD

**Issue by cataseven** [hassio-addons/addon-vscode#777]
# Problem/Motivation

While connected to wifi I have no problem. When I change to 4G mobile connection and try to use HA app I am getting 401 error. However if I do not use HA app (android version) and I use Chrome on mobile phone my browser it is working fine. I am using dns for remote connection. Everything except VS are working fine on 4G via Mobile app

Summary;

Good via wifi on all platfroms
Good via 4G mobile connection on Chrome browser of my mobile phone
Not working via 4G on HA android Companion App

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Sorry, maybe I'm not reading it / understanding right, but... the "what" isn't working, is missing from the issue report.

../Frenck

**Comment by cataseven** [comment]
Hi Frenck.

I am accesing HA away from home vis XXX.XXX@keenetic.net DNS address. I am not using ssl certificate. I have no problem accessing HA vis Companion app or via chrome browser on my mobile phone. However, If i try to open VS in HA via Companion app then I am getting 401 Error. But If i try to open VSC in HA via chrome browser on my phone I have no problem. Why does Companion app not allow VSCode and getting error 401 while internet browser allows?

**Comment by frenck** [comment]
Sorry I can't reproduce that. It works fine for me on mobile and tablet (both iOS and Android) using local and over a remote address via NC).
