### ISSUE TITLE
Creating automations through the UI displays as errors in Visual Studio Code

### ISSUE THREAD

**Issue by stevearmitage** [hassio-addons/addon-vscode#78]
# Problem/Motivation
 V: 1.2.3 

When viewing the YAML of my automations that were created in the Home Assistant Automation editor, Visual Studio Code displays lots of errors
<img width="617" alt="Screenshot 2020-02-03 at 14 35 32" src="https://user-images.githubusercontent.com/29444933/73633670-3a956a80-469a-11ea-9071-269f58230cc4.png">

## Expected behavior

No Errors, as it was created in Home Assistant

## Actual behavior

Lots of Errors, as it was created in Home Assistant

## Steps to reproduce

Here is the source code of one of the automations

- id: '1580694077988'
  alias: Office-Lights-Turn off office lights if no presence detected
  description: ''
  trigger:
  - device_id: dd111ee92e3d4805b9bfbc59c78cf3cd
    domain: binary_sensor
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_b1463a03_occupancy
    platform: device
    type: not_occupied
  condition: []
  action:
  - device_id: fed88fbe20654c3ea0e45b59759ec230
    domain: switch
    entity_id: switch.shelly_shsw_1_b9d799
    type: turn_off
  - device_id: d1e0385d6a1b4da0839d159ffd07fc00
    domain: light
    entity_id: light.gledopto_gl_c_007_829d431d_level_light_color_on_off
    type: turn_off
  - device_id: d1e0385d6a1b4da0839d159ffd07fc00
    domain: light
    entity_id: light.gledopto_gl_c_007_829d431d_level_light_color_on_off_2
    type: turn_off

Here is the editor display
<img width="650" alt="Screenshot 2020-02-03 at 15 34 10" src="https://user-images.githubusercontent.com/29444933/73633853-abd51d80-469a-11ea-9092-2b6431a7ea42.png">

**Comment by frenck** [comment]
Please report upstream: <https://github.com/keesschollaart81/vscode-home-assistant>
