### ISSUE TITLE
"Speed" is being labelled as an invalid device_class for a sensor template

### ISSUE THREAD

**Issue by bartowski1182** [hassio-addons/addon-vscode#782]
# Problem/Motivation

Yaml schema not up to date with documentation, "speed" is a valid device_class for sensors according to https://www.home-assistant.io/integrations/sensor/ however the YAML in line editor marks it with an error and claims it isn't

## Expected behavior

Creating a sensor template I should be able to use "speed" as my device class

## Actual behavior

The syntax highlighter underlines "speed" and says it isn't a valid value

## Steps to reproduce

Create a new template sensor like so:

```
template:
  - sensor:
    - name: "My Speed"
      device_class: "speed"
```

## Proposed changes

Need some way to update the YAML schema so that it's using the latest available documentation

**Comment by frenck** [comment]
Hi there 👋 

This is not an issue caused by the add-on, but by the Home Assistant config helper extensions for VSCode. Please report this issue with them upstream.

Thanks! 👍 

../Frenck

**Comment by bartowski1182** [comment]
Ah dammit thanks, I appreciate the response! Couldn't figure it out
