### ISSUE TITLE
Studio Code Server add-on isn't able to start

### ISSUE THREAD

**Issue by HumanGear322** [hassio-addons/addon-vscode#789]
# Problem/Motivation
Studio Code Server add-on isn't able to start anymore.
I'm running HA Core: 2024.2.4, OS: 12.0 on a rpi3-64 1GB.

## Expected behavior

Add-on would just start, like before. :-)

## Actual behavior

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
s6-rc: warning: unable to start service base-addon-banner: command exited 139
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

## Steps to reproduce
Tried to restart HA, manually start the add-on, enable the watchdog, but noting works and results are the same every time (see "actual behavior"

**Comment by t0rdenf0d** [comment]
pull the power - wait a min or 2. 
Funny thing but this kind off "restart" solved the problem for me :-)
