### ISSUE TITLE
Unexpected error from Error Lens 2.9.0

### ISSUE THREAD

**Issue by Sudo-Rob** [hassio-addons/addon-vscode#79]
# Problem/Motivation

Flagged error in lovelace-ui.yaml when editing in VSC.

## Expected behavior

No flagged error for:

![image](https://user-images.githubusercontent.com/56487711/74097796-5bb4eb80-4ade-11ea-81f9-d0d83d1279e7.png)

## Actual behavior

(What actually happened)

![image](https://user-images.githubusercontent.com/56487711/74097757-fe209f00-4add-11ea-8edb-a4e5fd362d71.png)

Check Configuration reports "Configuration valid!".

According to...
[https://www.home-assistant.io/lovelace/picture-entity/#how-to-use-state_filter](url)
..."state_filter" is optional.

## Steps to reproduce

This happens when running Home Assistant 0.105.2 and Visual Studio Code 1.2.3.

## Proposed changes

Fix if reproducible.

**Comment by frenck** [comment]
Please report this issue with the extension that is used:

<https://github.com/keesschollaart81/vscode-home-assistant>

Thanks! 👍

**Comment by Sudo-Rob** [comment]
Thanks.  It's already an open issue.
