### ISSUE TITLE
VSCode seems to eat up a LOT of CPU and RAM.

### ISSUE THREAD

**Issue by fribse** [hassio-addons/addon-vscode#793]
# Problem/Motivation

Studio Code Server depleats CPU and Memory.
The VM is a 2 CPU 8 GB Ram with quite a few addons.
When Studio Code Server has run for half a day, it is using 57% CPU and 26% memory.
HA core-2024.3.0
Studio Code Server 5.15.0

## Expected behavior

When the editor is not open, it should use 0% cpu, and no memory

## Actual behavior

It seems to eat up all available memory and CPU
The CPU drop when the add on was stopped
![billede](https://github.com/hassio-addons/addon-vscode/assets/13660621/9ace8511-c042-4aa1-9455-dd1302a70b1b)
The memory drop when the add on was stopped
![billede](https://github.com/hassio-addons/addon-vscode/assets/13660621/c379d21c-ea07-443f-8beb-e54a946b229a)
The rise is because I stopped a lof of add-ons, and started them afterwards when I found the VSCode addon usage.

## Steps to reproduce

Install and run, and let it rest for a day.

**Comment by frenck** [comment]
Yup. Not much that can be done from an add-on perspective.

../Frenck

**Comment by fribse** [comment]
@frenck I see, so it has recently exploded in usage? I've had it running for years, and only now it shows this?
