### ISSUE TITLE
Markdown Preview blank page / empty

### ISSUE THREAD

**Issue by pandamouse84** [hassio-addons/addon-vscode#795]
# Problem/Motivation

It looks like the markdown preview is broken, could be the same issue as on windows pc with running elevated/sandboxed?

## Expected behavior

Show a preview of the markdown file I opened the preview for.

## Actual behavior

Preview is an empty/blank site

## Steps to reproduce

1. Create a markdown file
2. input some content
3. Click the Markdown Preview button or command.

## Proposed changes

If possible fix markdown preview to be working

**Comment by sinclairpaul** [comment]
Are you using SSL?

**Comment by sinclairpaul** [comment]
I would suggest looking at the errors posted in the browser console.

**Comment by pandamouse84** [comment]
Ok I further troubleshooted the problem. It seems like this problem only exists using the HomeAssitant App or Browser (Safari/Edge) in IPad. Only my Windows PC in Browser it works without any error and the markdown preview is shown correctly.

Sadly on IPad there is no Browser Console, any Ideas how debug this further?

**Comment by sinclairpaul** [comment]
Then it is likely an upstream issue between Webkit and Code Server which this addon installs (or even VSCode itself).

There is not much that can be done here.
