### ISSUE TITLE
files do not open , and hassio  was restarted.

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-vscode#8]
# Problem/Motivation
the file list is shown , but after selecting the send file , it wont open. it just stays in "waiting" mode.
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/data/vscode/Backups/workspaces.json'\n\nError: ENOENT: no such file or directory, open '/data/vscode/Backups/workspaces.json'\n    at Timeout.setTimeout [as _onTimeout] (eval at exports.requireModule (/usr/local/bin/code-server:468:27625), <anonymous>:56921:31)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)\n"}
INFO  WebSocket closed / {"client":1,"code":1006}
ERROR SHARED stderr {"data":"Uncaught Exception:  { Error: read ECONNRESET\n    at Pipe.onread (net.js:622:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }\n"}

after this , the whole hassio v machine crashes .

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by WagnerBeccard** [comment]
I think this is the same error 

```
INFO  Connected to shared process
ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/data/vscode/Backups/workspaces.json'\n\nError: ENOENT: no such file or directory, open '/data/vscode/Backups/workspaces.json'\n    at Timeout.setTimeout [as _onTimeout] (eval at exports.requireModule (/usr/local/bin/code-server:468:27625), <anonymous>:56921:31)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)\n"}```

Tred out the app for the first time and clicked `Show Files in the explorer` 
Tryed to uninstall it and re install but it would not load up. 
I belive a  `reset to defaults` would let the app reload.

**Comment by frenck** [comment]
@WagnerBeccard That error message is not related and not an issue for the add-on to function.

**Comment by ikirt** [comment]
I had similar issue, removing and reinstalling seems to have fixed.

**Comment by gnkarn** [comment]
ok, i have to remove it , as was not able to restart normally ,  will test later reinstalling .tks

**Comment by ikirt** [comment]
After uninstalling the plugin, HA became unresponsive, I had to restart HA, then reinstall the plugin.

**Comment by ressikanflute** [comment]
I can confirm this happened when I clicked `Show Files in the explorer`

This fixed the problem (in Chrome):
https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

**Comment by rschuiling** [comment]
I see the exact same errors logged as @WagnerBeccard. Difference is: he seems to have resolved it, but I haven't. I also 'reset to defaults' and uninstalled & reinstalled the add-on. But the errors remain and when i click 'Open WEB UI' nothing gets loaded.

**Comment by ressikanflute** [comment]
@rschuiling Have you tried this?
https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

**Comment by rschuiling** [comment]
@ressikanflute Yes I did, it doesn't seem to help. I also tried in Private Browsing mode (no cookies or cache), but no luck yet.

**Comment by frenck** [comment]
Just a guess (since I'm completely lost on the issue): Memory shortage?

**Comment by sinclairpaul** [comment]
The errors listed above aren't necessarily an issue, @rschuiling are you running SSL?, the link will default to an https url (its a limitation).  If not, can you access, http://youhassip:1337 ?

**Comment by frenck** [comment]
@sinclairpaul It does not default to an `https` URL. The URL of the open web ui buttons is in sync with the settings.

**Comment by sinclairpaul** [comment]
My apologies, I thought this was the previous behavior.

**Comment by gnkarn** [comment]
it installs and works , with version 0.40 , only code color highlighting is not working yet , not sure if  i need to install an additional extension or  find some  configuration option for it .
