### ISSUE TITLE
Config_path value does not have any effect

### ISSUE THREAD

**Issue by nathanielcutajar** [hassio-addons/addon-vscode#802]
# Problem/Motivation

I wanted to get access of the file system from the root directory without needing to use SSH

## Expected behavior

In the documentation it says that when entering `/root` in the `config_path` option, you would see all the top-level items

## Actual behavior

'Config' remains as the main and only directory

## Steps to reproduce

Enter `/root` in the `config_path`, and restart

## Proposed changes

Not sure if it is an issue with reading the value, but it would be good if there is a log that states that it is reading from a particular directory as 'info' level

**Comment by sinclairpaul** [comment]
Take a look at #742

**Comment by nathanielcutajar** [comment]
Oh perfect, thank you <3
