### ISSUE TITLE
VS Code Server is working but when clicking on the Launch GUI nothing is showing!

### ISSUE THREAD

**Issue by yabdali** [hassio-addons/addon-vscode#808]
# Problem/Motivation
VS Code Server is working but when clicking on the Launch GUI nothing is showing! Restarting the server and the addon service doesn't make any difference.
> (Why the issue was filed)

## Expected behavior
Given that no errors in the log file the GUI editor is expected to show.

## Actual behavior
![image](https://github.com/hassio-addons/addon-vscode/assets/30695308/ec78c27c-3512-4349-a329-a1c6a0ab331e)

`
Studio Code Server
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.15.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 12 (bookworm)  (amd64 / qemux86-64)
 Home Assistant Core: 2024.4.3
 Home Assistant Supervisor: 2024.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[07:35:40] INFO: Configuring timezone (Asia/Dubai)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
s6-rc: info: service legacy-services: starting
[07:35:41] INFO: Starting code-server...
s6-rc: info: service legacy-services successfully started
[2024-04-18T03:35:41.305Z] info  Wrote default config file to /root/.config/code-server/config.yaml
[2024-04-18T03:35:41.511Z] info  code-server 4.20.0 d0215eca8804d0be5d3551c39404e336032c3141
[2024-04-18T03:35:41.511Z] info  Using user-data-dir /data/vscode
[2024-04-18T03:35:41.517Z] info  Using config file /root/.config/code-server/config.yaml
[2024-04-18T03:35:41.517Z] info  HTTP server listening on http://0.0.0.0:1337/
[2024-04-18T03:35:41.517Z] info    - Authentication is disabled
[2024-04-18T03:35:41.517Z] info    - Not serving HTTPS
[2024-04-18T03:35:41.517Z] info  Session server listening on /data/vscode/code-server-ipc.sock
[07:36:56] 

[07:36:56] Extension host agent started.`

![chrome_iWNzvXRAd3](https://github.com/hassio-addons/addon-vscode/assets/30695308/77f7e43d-42d2-4201-ad2b-d7a93855d964)

**Comment by yabdali** [comment]
> I have 2 instances of Home Assistant Yellow working at different locations. Both are using VS code server version 5.15.0 and both work if i am on site. However, only one will work when remoting in with the Tailscale VPN, the other is just a black screen like you show above. Can you give me some guidance please?

I checked again after you mentioned in your post Tailscale. The problem I face seems to be related to using Tailscale to access the Web UI of HA. When I used RDP to access a Windows machine on the same network as HA, the problem disappeared. So I can conclude the issue is to do with Tailscale/VPN. As you already have one working behind Tailscale, I presume its to do with NAT rules where the IP of the Tailscale is blocked from accessing the one that goes black. Do you have identical configuration at the both locations for the Tailscale network? Do you use the same type of router/configs?

**Comment by mikefrantz** [comment]
You are correct, it only happens when signing in with a web browser. However, both will work if you are local, but only one will work if you are signing in remotely. I believe that both Tailscales are setup with  identical configuration. But I cannot tell you about the router setups and one is Deco and the other is Ring mesh systems.

**Comment by alvin96** [comment]
I faced similar issue while I am setting up my local SSL using Traefix v3.0. I am not sure if it's related to https or local DNS (I am using pi hole for my local server) due to I am an amateur in networking haha. 

And the console show these errors:
`Refused to execute script from 'https://[my.domain.name]/api/hassio_ingress/[some hashed string content]/stable-[some hashed string content]/static/out/vsda.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

![image](https://github.com/hassio-addons/addon-vscode/assets/20142859/83fd6653-c4d6-41bd-a667-dae8982a9a66)


After a minute or two, my VS Code UI shown, but it didn't connect to my HA config or any file
![image](https://github.com/hassio-addons/addon-vscode/assets/20142859/586b73d7-3622-4f80-bdcc-bb25e69c1e20)

**Comment by mikefrantz** [comment]
In my case, it still will not work on an iPad when trying to view the config files, etc.

**Comment by alvin96** [comment]
The issue still exist
