### ISSUE TITLE
Is ingress forced in v2.0?

### ISSUE THREAD

**Issue by chierichetto** [hassio-addons/addon-vscode#81]
# Problem/Motivation
I can't connect over the local port (default to 1337) after upgrading to 2.0. I'm using a chromebook, and installed code server as a progressive web app on it. When using it through Home Assistant in the browser i can't use shortcuts like ctrl+tab to navigate.

## Expected behavior
The port to accept connections.

## Actual behavior
VS Code does not load anymore without ingress. Also i can't see the network parameters for the addon anymore.

## Steps to reproduce
Upgrade to 2.0 and try without ingress.
## Proposed changes
Add the possibility to use without ingress.

**Comment by frenck** [comment]
Yes, see release notes:

<https://github.com/hassio-addons/addon-vscode/releases/tag/v2.0.0>

**Comment by chierichetto** [comment]
Sorry, didn't read the relase notes good enough after updating. Is it possible to downgrade an addon?

**Comment by frenck** [comment]
Backups
