### ISSUE TITLE
Add-on does not start - without error message

### ISSUE THREAD

**Issue by BeSt1979** [hassio-addons/addon-vscode#811]
I installed the addon without any issue, but when trying to start, nothing happens
The logfile does not show any errors:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.15.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.2  (amd64 / qemux86-64)
 Home Assistant Core: 2024.4.4
 Home Assistant Supervisor: 2024.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[22:57:19] INFO: Configuring timezone (Europe/Berlin)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
[22:57:20] INFO: Starting code-server...
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2024-04-23T20:57:20.667Z] info  Wrote default config file to /root/.config/code-server/config.yaml
[2024-04-23T20:57:21.028Z] info  code-server 4.20.0 d0215eca8804d0be5d3551c39404e336032c3141
[2024-04-23T20:57:21.029Z] info  Using user-data-dir /data/vscode
[2024-04-23T20:57:21.040Z] info  Using config file /root/.config/code-server/config.yaml
[2024-04-23T20:57:21.040Z] info  HTTP server listening on http://0.0.0.0:1337/
[2024-04-23T20:57:21.040Z] info    - Authentication is disabled
[2024-04-23T20:57:21.040Z] info    - Not serving HTTPS
[2024-04-23T20:57:21.040Z] info  Session server listening on /data/vscode/code-server-ipc.sock

The "start" button on the addon page "rolls" forever. If a change to logs and back to information page nothing happened. I just can - again - click "start".

**Comment by frenck** [comment]
Sounds like an Home Assistant issue. The logs look fine.

Try rebooting your entire installation (not to be confused with restarting Home Assistant).

**Comment by BeSt1979** [comment]
Perfect. Thank you for the lightning fast answer. Rebooting the whole system does the trick.
