### ISSUE TITLE
2.0 Not available on Pi4 custom install

### ISSUE THREAD

**Issue by jasonehines** [hassio-addons/addon-vscode#82]
# Problem/Motivation
2.0 is still showing as unavailable on my custom Pi4 install

## Expected behavior
To be able to install

## Actual behavior
Not available for install

## Steps to reproduce
Raspbian Buster installed on 4GB Pi4. dd'd /root to ssd. Installed docker, then installed with this script https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh

## Proposed changes
Not sure. I looked at the commits, but I don't see anything checking the hardware.

<blockquote></blockquote>

**Comment by jasonehines** [comment]
never mind. I just remembered I installed the regular Pi4 version because I couldn't get the 64 ver to run.

**Comment by niklaswa** [comment]
I installed the regular version too. 
But after adding `arm_64bit=1` to the /boot/config.txt (and rebooted), I got the addon to run flawlessly.

**Comment by frenck** [comment]
I would not recommend that method listed above, and strongly discourage anybody to that.
