### ISSUE TITLE
Icon property in script.yaml throws warning in VSC in HA 106.2

### ISSUE THREAD

**Issue by holdestmade** [hassio-addons/addon-vscode#83]
# Problem/Motivation

When entering the new icon property in version 106.2 in a script, VSC shows a warning that the property is not allowed.

## Expected behavior

Not showing a warning

## Actual behavior

VSC shows a warning that the property is not allowed.

## Steps to reproduce

Add:
`icon: mdi:bulb`
to a script

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is thrown by the vscode extension. Please report it upstream:

https://github.com/keesschollaart81/vscode-home-assistant

Thanks 👍
