### ISSUE TITLE
Using VSCode settings sync in the instance

### ISSUE THREAD

**Issue by carlba** [hassio-addons/addon-vscode#832]
# Problem/Motivation

I noticed that it is not possible to use the settings sync with the code-server that you are using. It would be very helpful to be able to get all my regular vscode settings into the instance instead of having to recreate them. If you think this is an abuse of the issue system please delete the issue. 

## Expected behaviour

I would expect the VSCode settings sync to be enabled

## Actual behaviour

It is not possible to access the settings sync.

**Comment by sinclairpaul** [comment]
Settings Sync isn't available in OSS version of VSCode (which Code Server is), their maybe extensions that could help, but it isn't something that can be enabled.
