### ISSUE TITLE
VS Code timing out when using local dns record and SWAG

### ISSUE THREAD

**Issue by muddro1** [hassio-addons/addon-vscode#840]
# Problem/Motivation

VS Code is inaccessible when utilizing the method in the title.

## Expected behavior

VS Code would be accessible

## Actual behavior

Having a weird issue. I am running HAOS with cloudflared and VS Code. When I access HA through homeassistant.local or remotely, I am able to access HA fine and access VS Code with no issue. However, I set up a local DNS record for my remote address on my pi.hole to go to a SWAG RP container I have running. However, when I access HA this way, everything works properly but I am not able to access VS Code. In the console I see the follow:

`Content-Security-Policy: The page’s settings blocked an inline script (script-src-elem) from being executed because it violates the following directive: “script-src 'self' 'unsafe-eval' 'some SHA256 strings'
`
I also get:

```
Source map error: Error: request failed with status 401
Resource URL: https://my_domain/api/hassio_ingress/PoyoPbNqw7nKwS08vLUSPm6ySk1lkzapuueKVcw_Zl4/stable-0b84523121d6302fbe30eda7899ec3b81810748e/static/out/vs/workbench/workbench.web.main.js
Source Map URL: workbench.web.main.js.map
```

and: 

  `ERR [remote-connection][Management   ][56d14…][initial][WebSocket(my_domain:443)] the handshake timed out. Error: workbench.web.main.js:643:3592`

The logs of VS Code say: 
```
File not found: /usr/local/lib/code-server/lib/vscode/out/vsda.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vsda_bg.wasm
File not found: /usr/local/lib/code-server/lib/vscode/extensions/git-base/dist/browser/extension.js
File not found: /usr/local/lib/code-server/lib/vscode/extensions/merge-conflict/dist/browser/mergeConflictMain.js
```

I am using the standard SWAG https://github.com/linuxserver/reverse-proxy-confs/blob/master/homeassistant.subdomain.conf.sample

## Steps to reproduce

Stated above

## Proposed changes

Dont have a workaround aside from accessing remotely through cloudflared addon or through local ip/homeassistant.local

**Comment by sinclairpaul** [comment]
Ensure you have websockets enabled on your proxy.

I would suggest seeking further help on the forums or Discord, as this is a configuration issue outside the scope of the addon itself.
