### ISSUE TITLE
Home Assistant 2024.8 renamed service to action

### ISSUE THREAD

**Issue by ManuFlosoYT** [hassio-addons/addon-vscode#844]
![{8F88AC86-ED34-4948-B7ED-FA0A24D8DD6D}](https://github.com/user-attachments/assets/225bdf4c-d7bd-43c6-bb68-b40033307d05)

**Comment by tjorim** [comment]
Hi there 👋

This is not an issue caused by the add-on, but by the Home Assistant config helper extensions for VSCode. Please report this issue with them upstream.

Thanks! 👍
