### ISSUE TITLE
can't find studio code server in add-on stores after update HA to latest version

### ISSUE THREAD

**Issue by liluojunroger** [hassio-addons/addon-vscode#845]
# Problem/Motivation
can't find studio coder server in add-on stores after update HA to latest version(Core 2024.8.1 Supervisor 2024.08.0 Operating System 12.4)
> (Why the issue was filed)
 after upgrade the HA version to latest version(Core 2024.8.1 Supervisor 2024.08.0 Operating System 12.4)
## Expected behavior

> (What you expected to happen)
find Studio code server in add-on store
## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The add-on store is not a feature of an add-on, but a feature of Home Assistant itself.

From an add-on perspective, there is nothing I can do. If you think this is an issue with Home Assistant; please report it with the Home Assistant project.

Thanks 👍 

../Frenck
