### ISSUE TITLE
Armv8 support (Raspberry Pi 3/4)?

### ISSUE THREAD

**Issue by andre2007** [hassio-addons/addon-vscode#85]
Armv7 is listed as not supported. Do you support Armv8 (Raspberry  Pi 3/4)?

**Comment by frenck** [comment]
It is listed in the readme:

![image](https://user-images.githubusercontent.com/195327/77820691-4cb4e780-70e4-11ea-89ad-c99c0a097b86.png)


Yes.

**Comment by andre2007** [comment]
Thanks. If I understand it correctly it is listed as not supported in Home Assistant because I used the 32 bit instead of the 64 bit raspberry image?

**Comment by frenck** [comment]
Running a 32 bits operating system on a 64 capable CPU, makes the device a 32 bits devices.

So, yeah, you have a 32 bits machine, which is not supported.
