### ISSUE TITLE
Using Schemas question

### ISSUE THREAD

**Issue by plug-it-in** [hassio-addons/addon-vscode#853]
# Problem/Motivation
I am wondering why I get an error message when I put this schema instruction on the first line of my file. This works fine in local VSCode

# yaml-language-server: $schema=http://frigate_host:5000/api/config/schema.json

## Expected behavior
To enable Frigate YAML config validation

## Actual behavior
I get an error message unable to load schema

## Steps to reproduce
Add this line to a YAML file

![2024-09-06_17-18-14](https://github.com/user-attachments/assets/b12a7bf5-d4a2-4af7-9bfb-8c7050174892)

**Comment by sinclairpaul** [comment]
This isn't an issue with the addon I would suggest referencing the documentation <https://docs.frigate.video/configuration/#vscode-configuration-schema>
