### ISSUE TITLE
Weather template still reports errors that are not errors according to the documentation

### ISSUE THREAD

**Issue by derMicro** [hassio-addons/addon-vscode#867]
# Problem/Motivation

> Weather template still reports errors that are not errors according to the documentation

Some examples
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/d4ceabf1-e55b-4935-a206-9a4a4bb0eba3">
<img width="1183" alt="image" src="https://github.com/user-attachments/assets/dbf65eba-b67d-4359-8cb8-6f1026355bd3">

## Expected behavior

> no "Errors" in Intellisense

## Actual behavior

> IntelliSense report "false positive" errors

## Steps to reproduce

> Create a Weather-Template and use the parameters from [home-assistant.io](https://www.home-assistant.io/integrations/weather.template/)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Fixed in https://github.com/hassio-addons/addon-vscode/releases/tag/v5.16.1
