### ISSUE TITLE
IntelliSense shows error 'Missing property platform' at 'trigger' property

### ISSUE THREAD

**Issue by NorbertHD** [hassio-addons/addon-vscode#868]
# Problem/Motivation

> I'm using Studio Code Server v5.16.0 and the IntelliSense shows an error 'Missing property platform' at the 'trigger' property.

![trigger](https://github.com/user-attachments/assets/55bbaec7-ffdc-4a06-8e88-71d00ce7eb44)

## Expected behavior

> no "Errors" in Intellisense

## Actual behavior

> IntelliSense report "false positive" errors

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by philipp-frank** [comment]
Same here (no problems with v5.15.0).

**Comment by frenck** [comment]
This is expected at this time, as `trigger` isn't valid in the current stable release of Home Assistant.

../Frenck
