### ISSUE TITLE
VS Code crashes Home Assistant on a Raspberry Pi 3

### ISSUE THREAD

**Issue by reesericci** [hassio-addons/addon-vscode#87]
# Problem/Motivation

My HA instant crashes or is rendered unusable when trying to use VS Code (Edit config files, etc), it then requires a restart to get things working again.

## Expected behavior

Me being able to do things in VS Code (Edit config files, etc) and use my HA instance.

## Actual behavior

HA crashes or is rendered unusable when trying to use VS Code. (Edit config files, etc)

## Steps to reproduce

Attempt to use VS Code on a Raspberry Pi 3 with other addons installed and a fair amount of integrations used.

## Proposed changes

I don't really know how to fix this.

**Comment by frenck** [comment]
From the add-on documentation:

![image](https://user-images.githubusercontent.com/195327/78766790-fff5ca00-7989-11ea-8930-4943dc216be9.png)

Since it is a Pi3, you have 1 Gb...
