### ISSUE TITLE
Error on copy/cut&paste

### ISSUE THREAD

**Issue by jorgwolski** [hassio-addons/addon-vscode#875]
# Problem/Motivation

> When copying/cutting and pasting Studio Code throws an error and does not perform the file action. Error occurs on Firefox as well as Chrome and seems to have started with one of the recent add-on updates. No new privacy settings have been set (by myself).

## Expected behavior

> Copy/cut and paste without further error messages.

## Actual behavior

> Error message whenever trying to copy, cut or paste:
> `Unable to read from the browser's clipboard. Please make sure you have granted access for this website to read from the clipboard.`

## Steps to reproduce

> Select a file or directory and copy it via the context menu or keyboard shortcuts.

## Proposed changes

> none

**Comment by frenck** [comment]
This is a browser security limitation. Not something any app can do anything about. Indeed as mentioned above, some browser features are only available on secure connections over https.
