### ISSUE TITLE
Errors shown in automation.yaml after HA Core 10.0 upgrade

### ISSUE THREAD

**Issue by vjbalex** [hassio-addons/addon-vscode#876]
# Problem/Motivation

> HA Core 10.0 eliminated the property "platform" and introduces new syntax (triggers:) as shown in the attachement below. Studio Code Server editing does not interpret the changes correctly.

## Expected behavior
Errors such as these examples should not appear:
triggers:
  - trigger: time_pattern **Missing Property "platform"**

  triggers:
  - entity_id: person.my_person   **Missing property "platform".**
    zone: zone.my_zone
    event: leave
    trigger: zone   **Property trigger is not allowed.**

## Actual behavior
The existing automation.yaml file was migrated to the new syntax during the upgrade and new automations use the new syntax as well so SCS shows many issues. Automations still seem to work though. This appears to be a Studio Code Server error reporting issue.

## Steps to reproduce
Review automation.yaml in Studio Code Server

Attachment:
Changes example from HA Core 10.0 release documentation:
![YAML-automation-syntax-changes10 0](https://github.com/user-attachments/assets/f8c94f63-e2d5-43c8-bc36-b702de2d49d9)

**Comment by frenck** [comment]
Fixed in the latest releases.
