### ISSUE TITLE
code-server is being accessed over an insecure domain. Some functionality may not work as expected

### ISSUE THREAD

**Issue by holdestmade** [hassio-addons/addon-vscode#88]
# Problem/Motivation

> Error pop up:
code-server is being accessed over an insecure domain. Some functionality may not work as expected.”

## Expected behavior

> Not to see it

## Actual behavior

> Error pop up:
code-server is being accessed over an insecure domain. Some functionality may not work as expected.”

**Comment by frenck** [comment]
Use HTTPS if you don't want to see it.
