### ISSUE TITLE
persistent_notification update_type updated shows error

### ISSUE THREAD

**Issue by philipp-frank** [hassio-addons/addon-vscode#880]
# Problem/Motivation

The persistent_notification update_type "updated" is marked as an error.

![image](https://github.com/user-attachments/assets/7ec0c237-62e3-43f2-ac8b-54f2603eaabf)

## Expected behavior

All possible values (added, removed, updated, current) should be accepted - https://www.home-assistant.io/integrations/persistent_notification/

**Comment by benjamin-dcs** [comment]
Got here for the same issue. I would like to add that `id` also is not accepted: `Property id is not allowed`, while it is

**Comment by frenck** [comment]
Made a PR upstream to fix both issues. Thanks for reporting 👍 

../Frenck
