### ISSUE TITLE
Syntax error for triggers of template sensors

### ISSUE THREAD

**Issue by wltng** [hassio-addons/addon-vscode#882]
# Problem/Motivation

After updating VS code to 5.17.0 I noticed that the triggers of trigger-based template sensors give several errors now.

## Expected behavior

Since the legacy syntax is not deprecated I would expect the same behavior as before (5.16.3 doesn't have this behavior)

## Actual behavior

![{0482E041-CA2F-4D6F-B039-0C5588597D2E}](https://github.com/user-attachments/assets/b35a7ecb-ceb6-431c-b498-44bb2f84218b)

Changing `platform:` to `trigger:` removes most of the errors:

![{EE7E6DAA-6428-4AA0-8185-AD64715A3E1E}](https://github.com/user-attachments/assets/8b0934e5-89d8-4745-be04-c8bdc643f818)

**Comment by frenck** [comment]
It is legacy syntax and not a deprecation indeed. Your screenshots are thus correct (otherwise you would get an deprecation error).

**Comment by wltng** [comment]
The error says “does NOT match”, but it does match “legacy” syntax, so it shouldn’t raise an error at all I think.
Besides, the expected string error is also correct syntax according to the documentation (and has never been marked as an error). An entity_id with an homeassistant event is also unnecessary.
The required syntax hasn’t changed, but the latest update marks a lot as error. 
I think triggers of template sensors aren’t parsed correctly.

**Comment by wltng** [comment]
@frenck 
I appreciate the work you put in this addon. I removed the other posts, but I only posted there because you didn't follow up on the extra information I added here.

If you can find the time, can you please have a look at all the errors I'm getting? Since all the yaml (in both screenshots) is correct syntax, the errors shouldn't be there in my opinion. Or can you point out the error I'm making?
Thanks.

**Comment by frenck** [comment]
There is nothing to follow up on; this is the intended error message. It triggers an error because it is using a legacy syntax.

**Comment by wltng** [comment]
But there is no error. Legacy syntax is still correct. According to the error the syntax is NOT legacy, but it is. It is parsed incorrectly.

And what about the other errors?
An entity_id with a homeassistant trigger?
Hours must be a string? (while minutes and seconds can be ints)

**Comment by frenck** [comment]
This is a legacy syntax format; it does work, but Home Assistant adopted a newer format in their latest release.

That format is recommend by the HA project. If you like to use the older syntax, be my guest and ignore it.

../Frenck

**Comment by wltng** [comment]
I know, but you’re still not reading the error message.The message says it is not legacy syntax, but it is. Also the other errors shouldn’t be there.But it’s ok, I hope someone else will come along that can explain it better than me.Thanks for your time.On 16 Oct 2024, at 08:48, Franck Nijhof ***@***.***> wrote:﻿
This is a legacy syntax format; it does work, but Home Assistant adopted a newer format in their latest release.
That format is recommend by the HA project. If you like to use the older syntax, be my guest and ignore it.
../Frenck

**Comment by frenck** [comment]
> The message says it is not legacy syntax, but it is.

I did read it, I get it... it is what it can do 🤷 

../Frenck
