### ISSUE TITLE
False errors are shown

### ISSUE THREAD

**Issue by galets** [hassio-addons/addon-vscode#883]
# Problem/Motivation

After upgrade to 5.17.1 I've started seeing following errors:

![image](https://github.com/user-attachments/assets/38d02e90-278f-4436-84ce-221a9cbd9b29)

* these were not shown as errors previously
* hassio itself does not see it as error. See http://schemas.home-assistant.io/integration-homeassistant-packages for allowed fields, and  `serial_number` and `hw_version` are explicitly present on one of examples
* error message "Property serial_number is not allowed.yaml-schema: http://schemas.home-assistant.io/integration-homeassistant-packages" does not make sense:. There's no content at provided URL.

## Expected behavior

No squigglies

## Actual behavior

Yes squigglies

## Steps to reproduce

Populate `serial_number` and `hw_version` fields in MQTT sensor definition

## Proposed changes

unsure. Since the errors seem to have been introduced with recent update, maybe revert?..

**Comment by galets** [comment]
Linking to [hassio forum discussion](https://community.home-assistant.io/t/property-serial-number-is-not-allowed-on-mqtt-sensor/779376/3) for reference

**Comment by frenck** [comment]
Opened up a PR downstream to fix the schema https://github.com/keesschollaart81/vscode-home-assistant/pull/3224
