### ISSUE TITLE
String does not match pattern of LEGACY_SYNTAX

### ISSUE THREAD

**Issue by gallarding** [hassio-addons/addon-vscode#892]
After upgrading to Studio Code Server v 5.17.2, every script in my script file contains the error "String does not match the pattern of "LEGACY_SYNTAX^"
![Screenshot 2024-10-28 135543](https://github.com/user-attachments/assets/326faf5a-91ec-432e-a2b2-1880125c5a5a)

Attempted to uninstall/reinstall.
Log indicates missing files, not sure if related or not.
File not found: /usr/local/lib/code-server/lib/vscode/out/vsda.js
File not found: /usr/local/lib/code-server/lib/vscode/out/vsda_bg.wasm

**Comment by sinclairpaul** [comment]
See <https://github.com/keesschollaart81/vscode-home-assistant/issues/3241>

**Comment by gallarding** [comment]
Got it.  Thanks Paul.
