### ISSUE TITLE
VS Code showing update notices again

### ISSUE THREAD

**Issue by rpitera** [hassio-addons/addon-vscode#90]
# Problem/Motivation

VS Code showing update notices again

## Expected behavior

This was fixed before in #75 and stopped showing notifications, but it's back again.

## Actual behavior

![Clipboard02](https://user-images.githubusercontent.com/19910294/78997557-d0bf9400-7b14-11ea-993a-0063dccc35ee.png)

## Steps to reproduce

Opened add on from side menu.  Shows once per session.  If closed or "Later" is pressed it goes away but returns on next session

## Proposed changes

N/A

**Comment by sinclairpaul** [comment]
The fix before was setting the update mode to none in the default settings, is yours set to that?

![image](https://user-images.githubusercontent.com/24625998/78999872-87be0e80-7b19-11ea-933b-609d3643be25.png)

**Comment by rpitera** [comment]
Yes, it is.

**Comment by frenck** [comment]
Update notification have been removed entirely in v2.3.0 of the add-on.

**Comment by rpitera** [comment]
Thank You Frenck!

**Comment by frenck** [comment]
You are welcome, sir @rpitera 😄
