### ISSUE TITLE
apt install manpages-dev isn't fully installed

### ISSUE THREAD

**Issue by Asmod4n** [hassio-addons/addon-vscode#904]
When installing manpages-dev in this container the directory /usr/share/man/man2 isn't created and filled, even when you create the directory manually.

You have to download it with apt download manpages-dev and cp the contents of man2 on your own to get it.
I am getting no errors during any step.

**Comment by frenck** [comment]
Yes, this is in general pretty much by design in containers, so save diskspace in distributing containers.

For that reason, I'll go ahead and close this issue 👍 

../Frenck
