### ISSUE TITLE
cant install Python extension

### ISSUE THREAD

**Issue by TechOnlyGamer** [hassio-addons/addon-vscode#91]
# Problem/Motivation
Hey Guys when i want to install the Python extension it gives me an error that the current version of VSCODE isnt compatible with this extension.

Is there a way i can Update vscode or do i have to wait that the addon gets updated??

**Comment by frenck** [comment]
The update of the add-on is currently blocked due to another factor.

As a workaround, an older version of the Python extension can be used.

Hoping to resolve this soon.
