### ISSUE TITLE
Indentation lost at each access

### ISSUE THREAD

**Issue by tamet83** [hassio-addons/addon-vscode#98]
# Problem/Motivation
With latest version 2.2.0 the addon doesn't keep the indentation based on the code.

Here a screenshot for VSC settings and log warnings:

![vsc_error](https://user-images.githubusercontent.com/7949570/79622189-89d62d80-8116-11ea-88f3-cdff2135c9d1.JPG)

> (Why the issue was filed)

## Expected behavior
When I hit enter I should have something like this:

![vsc_error_3](https://user-images.githubusercontent.com/7949570/79622590-2f3dd100-8118-11ea-9855-03a84870831f.JPG)

> (What you expected to happen)

## Actual behavior

Instead, when I hit return I have this:

![vsc_error_2](https://user-images.githubusercontent.com/7949570/79622297-f81af000-8116-11ea-9c3d-7d6916dccc1c.JPG)

> (What actually happened)

## Steps to reproduce
I tried to reset configuration as described in the guidelines but nothing happened.
Thankd for your help.
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Giancky79** [comment]
changed options configuration
  // Controls whether the editor should automatically adjust the indentation when users type, paste, move or indent lines.
  //  - none: The editor will not insert indentation automatically.
  //  - keep: The editor will keep the current line's indentation.
  //  - brackets: The editor will keep the current line's indentation and honor language defined brackets.
  //  - advanced: The editor will keep the current line's indentation, honor language defined brackets and invoke special onEnterRules defined by languages.
  //  - full: The editor will keep the current line's indentation, honor language defined brackets, invoke special onEnterRules defined by languages, and honor indentationRules defined by languages.
example  "editor.autoIndent": "full"

**Comment by tamet83** [comment]
It doesn't keep the values, each time I get back to the addon the problem persists.
I tried your solution, it works at first but then I get back the strange behavior.
Thanks for your trying!

**Comment by ryanjohnsontv** [comment]
Just wanted to add that I've also started to experience the same issue. Auto indent is set to full, however it is not reflected when starting a new line in the code editor.

**Comment by frenck** [comment]
This has been resolved in v2.3.0 of the add-on.

Please make sure to run a `reset-settings` in a VSCode terminal in order to get the new VSCode settings activated.

**Comment by tamet83** [comment]
I confirm it works perfectly after upgrading and settings reset. Thank you :)
